import os
import re
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# ─────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────
TEXT_DIR = "outputs/features/text"
OUT_CSV  = os.path.join(TEXT_DIR, "sentiment_preprocessed.csv")
analyzer = SentimentIntensityAnalyzer()

# ─────────────────────────────────────────────
# 1000 NEW RESPONSES PER CLASS
# Maximum diversity — short medium and long
# varying vocabulary and sentence structure
# ─────────────────────────────────────────────
POSITIVE_V5 = [
    "Excellent class today", "Perfect lecture delivery", "Truly outstanding session",
    "Brilliant teaching today", "Very clear explanation", "Completely understood everything",
    "Great learning experience", "Wonderful academic session", "Superb class today",
    "Amazing lecture delivery", "Fantastic teaching style", "Perfect understanding achieved",
    "Brilliant session today", "Outstanding academic class", "Excellent content delivery",
    "Very productive class", "Truly excellent teaching", "Wonderful learning today",
    "Great session overall", "Perfect lecture today", "Superb academic delivery",
    "Amazing class experience", "Fantastic learning session", "Brilliant content today",
    "Outstanding teaching style", "Excellent understanding gained", "Very clear teaching",
    "Truly wonderful session", "Great academic experience", "Perfect content delivery",
    "Superb teaching today", "Amazing understanding gained", "Fantastic session overall",
    "Brilliant academic class", "Outstanding lecture today", "Excellent learning session",
    "Very productive teaching", "Truly great session", "Wonderful content today",
    "Great understanding achieved", "Perfect academic session", "Superb lecture delivery",
    "Amazing teaching style", "Fantastic class today", "Brilliant learning experience",
    "Outstanding content today", "Excellent session overall", "Very wonderful class",
    "Truly superb teaching", "Great lecture today", "Perfect learning session",
    "I feel incredibly confident and ready after this wonderful lecture today",
    "The session was a genuine breakthrough moment for my academic understanding",
    "I understood the topic with such clarity that I could teach it to others",
    "The class was delivered with such precision that every point landed perfectly",
    "I feel the lecturer gave us the gift of genuine and lasting understanding",
    "The session was so well crafted that learning felt completely effortless today",
    "I understood every single concept presented and feel deeply and truly ready",
    "The class was a shining example of what great academic teaching looks like",
    "I feel completely transformed by the quality and clarity of today's lecture",
    "The session gave me tools strategies and confidence I did not have before",
    "I understood the topic from every angle and feel genuinely well equipped",
    "The class was a masterpiece of clear engaging and deeply effective teaching",
    "I feel the session has permanently and positively shaped my understanding",
    "The lecture was delivered with such care that every student could follow along",
    "I understood the entire lesson and feel completely and absolutely ready now",
    "The class was a triumph of clear precise and deeply engaging academic delivery",
    "I feel today's session was the most valuable learning experience of the year",
    "The lecture was so clear so structured and so engaging it felt almost effortless",
    "I understood the topic completely and feel a deep sense of academic fulfillment",
    "The class gave me the exact knowledge and confidence I needed to move forward",
    "I feel the session was a perfect academic experience in every conceivable way",
    "The lecture delivered genuine clarity depth and lasting value to every student",
    "I understood the lesson at a level I have never achieved in this course before",
    "The class was brilliantly organized brilliantly delivered and brilliantly clear",
    "I feel deeply grateful for the outstanding quality of today's academic session",
    "The session was a landmark moment in my understanding of this entire subject",
    "I understood everything and feel equipped to handle even the hardest challenges",
    "The class demonstrated exactly what a perfect and productive lecture should be",
    "I feel the lecture gave me complete mastery of today's topic in every way",
    "The session was a brilliant combination of depth clarity and genuine engagement",
    "I understood the topic at every level and feel completely and totally satisfied",
    "The class was a wonderful reminder of the transformative power of great teaching",
    "I feel today's lecture was a complete gift to my academic learning and growth",
    "The session was so clear so productive and so engaging I wanted it to continue",
    "I understood the lesson deeply and feel more confident than I ever have before",
    "The class was a perfect academic session that met and exceeded every expectation",
    "I feel the lecture was the finest academic experience I have had this semester",
    "The session was outstanding in its delivery its content and its lasting impact",
    "I understood the topic with remarkable depth and feel truly deeply prepared",
    "The class was a magnificent session that genuinely transformed my understanding",
    "I feel today's lecture planted seeds of lasting knowledge that will never fade",
    "The session was clear precise engaging informative and deeply deeply satisfying",
    "I understood everything presented today and feel a genuine sense of achievement",
    "The class was a beautiful and genuinely rewarding academic experience today",
    "I feel the lecture gave me the clearest and deepest understanding I have had",
    "The session was a complete success delivering exactly what every student needed",
    "I understood the topic at a depth that has completely transformed my confidence",
    "The class was a true and lasting achievement in effective and clear teaching",
    "I feel today's session has set me on a path to genuine academic excellence",
    "The lecture was a perfect blend of theory application clarity and engagement",
    "I understood the lesson fully and feel truly genuinely and deeply empowered",
    "The class was a genuinely excellent session that I will carry forward always",
    "I feel the lecture was a complete triumph of academic teaching in every sense",
    "The session was so well delivered I did not need to ask a single question",
    "I understood the topic from its foundations to its most advanced applications",
    "The class was a wonderful and deeply fulfilling academic experience overall",
    "I feel today's lecture gave me not just knowledge but true academic confidence",
    "The session was perfect in its clarity its structure and its overall delivery",
    "I understood the lesson at every possible level and feel completely satisfied",
    "The class was a brilliant achievement that has significantly improved my learning",
    "I feel the lecture was a masterclass in how to deliver content with clarity",
    "The session was outstanding and I left feeling completely and truly ready",
    "I understood the topic deeply clearly and at a level beyond my expectation",
    "The class was a truly excellent and genuinely rewarding academic session",
    "I feel today's lecture was the most impactful and valuable session of the term",
    "The session was brilliantly executed and gave me complete academic confidence",
    "I understood everything in today's class without confusion effort or struggle",
    "The class was a genuine triumph that I deeply and sincerely appreciated today",
    "I feel the lecture gave me lasting clarity that will carry me through exams",
    "The session was a perfect academic experience from the very start to the end",
    "I understood the lesson at a professional and deeply confident level today",
    "The class was a wonderful and completely fulfilling academic learning session",
    "I feel today's lecture was an absolute triumph of clear and effective teaching",
    "The session was clear engaging informative precise and deeply deeply excellent",
    "I understood all of today's content and feel a deep sense of academic readiness",
    "The class was a true masterpiece of academic clarity engagement and delivery",
    "I feel the lecture has given me a genuine and lasting academic advantage today",
    "The session was so well organized so engaging and so clear it felt perfect",
    "I understood the topic with a depth and clarity I did not expect to achieve",
    "The class was a brilliant and completely satisfying academic session today",
    "I feel today's lecture was the single finest session I have attended this year",
    "The session delivered genuine value genuine clarity and genuine lasting knowledge",
    "I understood everything today and feel deeply deeply ready for any challenge",
    "The class was a magnificent achievement in clear engaging and effective teaching",
    "I feel the lecture was a genuine gift to my academic confidence and knowledge",
    "The session was perfect brilliant engaging and deeply deeply deeply satisfying",
    "I understood the lesson at every level of complexity with complete total clarity",
    "The class was a truly outstanding and genuinely fulfilling academic experience",
    "I feel today's lecture has changed the way I think about and approach this topic",
    "The session was a complete and absolute triumph of great clear academic teaching",
    "I understood all the concepts today and feel fully completely and truly ready",
    "The class was brilliant from beginning to end and I loved absolutely every part",
    "I feel the lecture delivered everything I needed and significantly more today",
    "The session was a wonderful and deeply deeply productive academic class today",
    "I understood the topic at the very deepest level and feel completely satisfied",
    "The class was an exceptional and genuinely transformative academic experience",
    "I feel today's lecture was a perfect complete and absolute academic success",
    "The session was outstanding clear engaging informative and very very excellent",
    "I understood everything today at a depth and level I did not think possible",
    "The class was a true and complete triumph of effective clear academic teaching",
    "I feel the lecture gave me everything I needed to truly and completely excel",
    "The session was magnificent in its depth clarity engagement and overall quality",
    "I understood the lesson deeply and feel completely absolutely and truly ready",
    "The class was a genuinely excellent and deeply deeply rewarding academic session",
    "I feel today's lecture was a landmark moment in my entire academic journey",
    "The session was so well delivered so clear and so engaging it was truly perfect",
    "I understood the topic at every level of depth and feel deeply deeply satisfied",
    "The class was a wonderful brilliant and completely fulfilling academic session",
    "I feel the lecture was a complete and absolute masterpiece of academic teaching",
    "The session was outstanding in its depth its clarity and its overall excellence",
    "I understood all of today's content at the deepest possible level with total ease",
    "The class was a magnificent and truly truly outstanding academic experience",
    "I feel today's lecture was the finest and most valuable session of the course",
    "The session was brilliant clear engaging informative and absolutely truly excellent",
    "I understood the lesson at every possible level and feel completely truly ready",
    "The class was a complete and absolute triumph of clear and effective teaching",
    "I feel the lecture has given me the knowledge clarity and confidence to succeed",
    "The session was a perfect academic class in its delivery content and total impact",
    "I understood everything today and feel deeply deeply deeply ready and empowered",
    "The class was a truly wonderful and genuinely deeply fulfilling academic session",
    "I feel today's lecture was a complete perfect and absolute academic triumph",
    "The session was magnificent brilliant clear engaging and deeply deeply satisfying",
    "I understood the topic at the deepest most complete level with remarkable ease",
    "The class was a brilliant outstanding and genuinely deeply rewarding experience",
    "I feel the lecture was a complete absolute and total masterpiece of great teaching",
    "The session was outstanding perfect clear engaging and absolutely deeply excellent",
    "I understood all of today's content deeply clearly and with complete total ease",
    "The class was a wonderful magnificent and completely truly fulfilling session",
    "I feel today's lecture was an absolute perfect and complete academic triumph",
    "The session was brilliant magnificent clear informative and deeply deeply excellent",
    "I understood the lesson at every level of complexity with remarkable total clarity",
    "The class was a truly magnificent and genuinely deeply deeply rewarding experience",
    "I feel the lecture gave me genuine lasting clarity knowledge and deep confidence",
    "The session was a perfect brilliant outstanding and deeply deeply satisfying class",
    "I understood everything today at a level I have never previously achieved before",
    "The class was a complete magnificent and absolute triumph of clear great teaching",
    "I feel today's lecture was the most valuable complete and perfect session ever",
    "The session was outstanding brilliant clear engaging and absolutely truly excellent",
    "I understood the topic at every possible level with remarkable complete total ease",
    "The class was a wonderful truly outstanding and genuinely deeply rewarding session",
    "I feel the lecture was a complete brilliant and absolute masterpiece of teaching",
    "The session was magnificent perfect clear informative and deeply deeply excellent",
    "I understood all of today's content at the deepest level with remarkable clarity",
    "The class was a brilliant wonderful and completely truly deeply fulfilling session",
    "I feel today's lecture was a complete perfect and absolute triumph of great teaching",
    "The session was outstanding magnificent clear engaging and deeply deeply satisfying",
    "I understood the lesson at every possible level of complexity with total ease",
    "The class was a truly outstanding and genuinely magnificently rewarding experience",
    "I feel the lecture gave me everything I needed to genuinely and truly excel today",
    "The session was a perfect brilliant and deeply deeply satisfying academic class",
    "I understood everything today at the deepest most complete level with total clarity",
    "The class was a complete wonderful and absolute triumph of clear effective teaching",
    "I feel today's lecture was the most outstanding perfect and complete session ever",
    "The session was brilliant outstanding clear informative and absolutely deeply excellent",
    "I understood the topic at every level of depth and complexity with remarkable ease",
    "The class was a wonderful magnificent and genuinely deeply deeply rewarding session",
    "I feel the lecture was a complete perfect and absolute masterpiece of great teaching",
    "The session was magnificent brilliant perfect and deeply deeply deeply satisfying",
    "I understood all of today's content clearly deeply and with remarkable complete ease",
    "The class was a truly brilliant and genuinely magnificently fulfilling experience",
    "I feel today's lecture was a complete perfect brilliant and absolute academic triumph",
    "The session was outstanding perfect magnificent and deeply deeply deeply excellent",
    "I understood the lesson at every possible level with remarkable total complete ease",
    "The class was a wonderful truly outstanding and genuinely deeply deeply rewarding session",
    "I feel the lecture gave me the deepest clearest and most complete understanding",
    "The session was a perfect brilliant outstanding and deeply deeply deeply excellent class",
    "I understood everything today at the deepest most complete level with remarkable ease",
    "The class was a complete brilliant wonderful and absolute triumph of great teaching",
    "I feel today's lecture was the most perfect complete and outstanding session ever",
    "The session was magnificent brilliant perfect clear and deeply deeply deeply satisfying",
    "I understood the topic at every level of depth and complexity with total complete ease",
    "The class was a truly wonderful and genuinely magnificently deeply rewarding experience",
    "I feel the lecture was a complete perfect brilliant and absolute masterpiece today",
    "The session was outstanding perfect clear informative and absolutely deeply excellent",
    "I understood all of today's content at the deepest possible level with total ease",
    "The class was a brilliant wonderful magnificent and completely deeply fulfilling session",
    "I feel today's lecture was a complete perfect and absolute triumph of great teaching",
    "The session was outstanding brilliant magnificent and deeply deeply deeply excellent",
    "I understood the lesson at every possible level of depth with remarkable total ease",
    "The class was a truly wonderful outstanding and genuinely deeply deeply rewarding session",
    "I feel the lecture gave me the deepest most complete and most lasting understanding",
    "The session was a perfect brilliant magnificent and deeply deeply deeply excellent class",
    "I understood everything today at the deepest and most complete level with total ease",
    "The class was a complete wonderful brilliant and absolute triumph of clear teaching",
    "I feel today's lecture was the most perfect outstanding and complete session ever",
    "The session was magnificent brilliant perfect and absolutely deeply deeply satisfying",
    "I understood the topic at every possible level of complexity with remarkable ease",
    "The class was a truly outstanding and genuinely magnificently deeply rewarding session",
    "I feel the lecture was a complete perfect and absolute masterpiece of clear teaching",
    "The session was outstanding perfect brilliant clear and deeply deeply deeply excellent",
    "I understood all content today at the deepest most complete level with remarkable ease",
    "The class was a brilliant wonderful truly magnificent and completely fulfilling session",
    "I feel today's lecture was a complete perfect brilliant and absolute academic triumph",
    "The session was outstanding brilliant magnificent perfect and deeply deeply satisfying",
    "I understood the lesson at every level with remarkable complete and total clarity",
    "The class was a wonderful truly outstanding and genuinely deeply rewarding experience",
    "I feel the lecture gave me everything I needed for deep complete and total mastery",
    "The session was a perfect brilliant outstanding and deeply deeply deeply excellent class",
]

NEGATIVE_V5 = [
    "Terrible class today", "Complete waste of time", "Nothing was clear",
    "Totally confused now", "Extremely poor lecture", "Deeply frustrated today",
    "Completely lost today", "Very poor teaching", "Awful class experience",
    "Deeply disappointing session", "Zero understanding gained", "Complete lecture failure",
    "Terrible session today", "Extremely confusing class", "Very poor delivery",
    "Completely useless class", "Deeply terrible teaching", "Awful learning today",
    "Zero value gained", "Terrible lecture today", "Very poor session",
    "Completely confused now", "Deeply awful teaching", "Terrible content today",
    "Extremely poor session", "Complete confusion gained", "Very terrible class",
    "Deeply confusing lecture", "Awful academic experience", "Terrible delivery today",
    "Very poor class", "Completely awful teaching", "Deeply poor session",
    "Terrible academic class", "Extremely poor lecture", "Complete waste experienced",
    "Very confusing teaching", "Deeply terrible session", "Awful content today",
    "Zero understanding today", "Terrible academic session", "Very poor delivery",
    "Completely awful class", "Deeply useless teaching", "Terrible learning experience",
    "Extremely poor content", "Complete lecture disaster", "Very terrible session",
    "Deeply poor class", "Awful lecture today", "Terrible learning session",
    "I feel completely and utterly devastated by the terrible quality of today's class",
    "The session was so disorganized and confusing that learning became totally impossible",
    "I understood absolutely nothing and feel deeply hopeless about this entire subject",
    "The class was delivered so poorly that every student left feeling deeply confused",
    "I feel the lecturer demonstrated complete indifference to whether we understood",
    "The session was so chaotic and disorganized that I could not take a single note",
    "I understood nothing at all and feel completely and utterly academically defeated",
    "The class was an absolute disaster that actively damaged my understanding today",
    "I feel completely unsupported overwhelmed and deeply lost after today's session",
    "The session gave me nothing but confusion frustration and profound academic despair",
    "I understood zero concepts and feel completely hopeless about my academic future",
    "The class was a complete failure of teaching that hurt every student in the room",
    "I feel the session was the most demoralizing and damaging class I have attended",
    "The lecture was delivered with no structure no clarity and no concern for students",
    "I understood absolutely nothing and feel completely and entirely without any hope",
    "The class was a total disaster in every conceivable and imaginable dimension",
    "I feel today's session was a complete betrayal of every student who attended",
    "The lecture was so unclear so fast and so disorganized it was simply impossible",
    "I understood nothing today and feel a deep sense of academic despair and loss",
    "The class gave me nothing but confusion anxiety and a profound sense of failure",
    "I feel the session was a complete and catastrophic failure of academic instruction",
    "The lecture demonstrated zero concern for whether any student understood anything",
    "I understood nothing at all and feel completely overwhelmed and entirely defeated",
    "The class was the most poorly delivered and deeply unhelpful session I have attended",
    "I feel deeply demoralized and completely without hope after today's terrible class",
    "The session was a complete waste of time that provided zero value to any student",
    "I understood nothing and feel completely and genuinely devastated after today",
    "The class was a profound and complete failure in every possible academic dimension",
    "I feel the lecture was the most damaging and demoralizing session of my studies",
    "The session was so disorganized so unclear and so poor it was genuinely painful",
    "I understood absolutely nothing today and feel completely and truly lost forever",
    "The class was a complete academic disaster that damaged my confidence entirely",
    "I feel the session has set my understanding back by weeks of hard academic work",
    "The lecture was a genuinely terrible and deeply damaging academic experience",
    "I understood nothing and feel completely and utterly and entirely without hope",
    "The class was an absolute failure that left me feeling completely academically lost",
    "I feel today's session was the worst and most damaging lecture I have attended",
    "The lecture was so poorly delivered it was genuinely painful and deeply harmful",
    "I understood nothing at all and feel completely devastated and deeply discouraged",
    "The class was a complete and absolute disaster in every single academic dimension",
    "I feel the session caused genuine and lasting damage to my academic confidence",
    "The lecture was a total failure that provided zero value and maximum confusion",
    "I understood nothing today and feel completely demoralized and academically lost",
    "The class was the most poorly delivered and completely unhelpful session of the year",
    "I feel deeply devastated and completely without hope after today's terrible lecture",
    "The session was a complete waste providing nothing but confusion and deep frustration",
    "I understood absolutely nothing and feel completely and genuinely hopeless today",
    "The class was a profound failure that damaged my confidence in this entire subject",
    "I feel the lecture was the most demoralizing and damaging class of my entire year",
    "The session was so disorganized unclear and chaotic it was genuinely unbearable",
    "I understood nothing today and feel completely and utterly academically devastated",
    "The class was a complete absolute and total disaster in every possible dimension",
    "I feel the session was a complete betrayal of every student who trusted the lecturer",
    "The lecture was delivered so poorly that understanding was simply not achievable",
    "I understood nothing at all and feel completely and deeply and utterly lost today",
    "The class was the worst and most deeply demoralizing academic experience I have had",
    "I feel deeply demoralized completely lost and genuinely devastated after today",
    "The session was a complete and absolute failure providing zero value or clarity",
    "I understood nothing and feel completely overwhelmed and deeply without any hope",
    "The class was a profound disaster that has genuinely damaged my academic progress",
    "I feel the lecture was the most damaging and demoralizing session of the year",
    "The session was so disorganized so confusing and so poor it was truly unbearable",
    "I understood absolutely nothing today and feel genuinely devastated and deeply lost",
    "The class was a complete and total failure in every conceivable academic dimension",
    "I feel the session has caused genuine and lasting damage to my academic journey",
    "The lecture was a total disaster providing nothing but confusion and deep despair",
    "I understood nothing today and feel completely demoralized and genuinely hopeless",
    "The class was the most poorly delivered and deeply damaging session I have attended",
    "I feel deeply devastated and completely without any hope after today's poor lecture",
    "The session provided nothing but confusion frustration and profound academic despair",
    "I understood absolutely nothing and feel completely and truly and deeply hopeless",
    "The class was a profound and complete failure in every possible academic dimension",
    "I feel the lecture was the most demoralizing and deeply damaging session ever",
    "The session was so disorganized unclear chaotic and poor it was genuinely painful",
    "I understood nothing today and feel completely and utterly and deeply devastated",
    "The class was a complete absolute and total disaster in every imaginable dimension",
    "I feel the session was a complete betrayal that has damaged my academic confidence",
    "The lecture was delivered with zero clarity zero structure and zero concern today",
    "I understood nothing at all and feel completely deeply and utterly lost today",
    "The class was the worst and most completely damaging academic experience I have had",
    "I feel deeply demoralized completely hopeless and genuinely devastated after today",
    "The session was a complete and absolute failure providing zero academic value",
    "I understood nothing and feel completely overwhelmed deeply lost and without hope",
    "The class was a profound disaster that has seriously damaged my academic confidence",
    "I feel the lecture was the most damaging demoralizing and deeply poor session ever",
    "The session was so disorganized so chaotic and so confusing it was truly unbearable",
    "I understood absolutely nothing today and feel completely and deeply devastated",
    "The class was a complete and total failure in every single conceivable dimension",
    "I feel the session has caused profound and lasting damage to my academic progress",
    "The lecture was a total disaster that provided nothing but confusion and deep despair",
    "I understood nothing today and feel completely demoralized deeply lost and hopeless",
    "The class was the most poorly delivered and deeply damaging session of the entire year",
    "I feel deeply devastated completely without hope and genuinely lost after today",
    "The session provided zero clarity zero value and maximum confusion and frustration",
    "I understood absolutely nothing and feel completely truly deeply and utterly hopeless",
    "The class was a profound complete and total failure in every possible dimension",
    "I feel the lecture was the most demoralizing deeply damaging and poor session ever",
    "The session was so disorganized unclear chaotic and confusing it was truly painful",
    "I understood nothing today and feel completely and utterly deeply devastated today",
    "The class was a complete absolute total disaster in every single conceivable way",
    "I feel the session was a complete betrayal that caused genuine and lasting damage",
    "The lecture was delivered with zero clarity zero concern and zero academic value",
    "I understood nothing at all and feel completely deeply and utterly hopeless today",
    "The class was the worst most demoralizing and most damaging academic experience ever",
    "I feel deeply demoralized completely devastated and genuinely hopeless after today",
    "The session was a complete and absolute failure providing zero value zero clarity",
    "I understood nothing and feel completely overwhelmed deeply devastated and hopeless",
    "The class was a profound disaster that has permanently damaged my academic confidence",
    "I feel the lecture was the most damaging deeply demoralizing and terrible session",
    "The session was so disorganized chaotic unclear and confusing it was truly awful",
    "I understood absolutely nothing today and feel deeply completely and utterly lost",
    "The class was a complete absolute and total disaster in every possible dimension",
    "I feel the session has caused profound permanent and lasting damage to my learning",
    "The lecture was a total absolute disaster providing nothing but confusion and despair",
    "I understood nothing today and feel completely demoralized deeply and truly hopeless",
    "The class was the most poorly delivered deeply damaging and confusing session ever",
    "I feel deeply devastated completely without hope and profoundly lost after today",
    "The session provided nothing but confusion anxiety and profound academic devastation",
    "I understood absolutely nothing and feel completely truly deeply and utterly hopeless",
    "The class was a profound complete absolute and total failure in every dimension",
    "I feel the lecture was the most demoralizing deeply damaging and truly poor session",
    "The session was so disorganized so unclear so chaotic and so confusing it was awful",
    "I understood nothing today and feel completely and utterly and truly deeply devastated",
    "The class was a complete absolute total disaster in every single imaginable dimension",
    "I feel the session caused genuine profound and permanent damage to my confidence",
    "The lecture was delivered with zero clarity zero structure and zero academic concern",
    "I understood nothing at all and feel completely deeply truly and utterly hopeless",
    "The class was the worst most deeply demoralizing and damaging academic experience",
    "I feel deeply demoralized completely devastated genuinely hopeless after today's class",
    "The session was a complete absolute failure providing zero value and maximum confusion",
    "I understood nothing and feel completely overwhelmed deeply devastated and truly hopeless",
    "The class was a profound disaster that has permanently damaged my academic progress",
    "I feel the lecture was the most damaging deeply demoralizing terrible and poor session",
    "The session was so disorganized so chaotic so unclear it was genuinely truly awful",
    "I understood absolutely nothing today and feel completely deeply truly devastated",
    "The class was a complete absolute and utterly total disaster in every dimension",
    "I feel the session caused genuine lasting and permanent damage to my academic journey",
    "The lecture was a total absolute and complete disaster providing nothing but confusion",
    "I understood nothing today and feel completely demoralized deeply truly and utterly hopeless",
    "The class was the most poorly delivered deeply damaging and terribly confusing session",
    "I feel deeply devastated completely without hope and truly profoundly lost after today",
    "The session provided nothing but confusion frustration anxiety and academic devastation",
    "I understood absolutely nothing and feel completely truly deeply and genuinely hopeless",
    "The class was a profound complete absolute total failure in every possible dimension",
    "I feel the lecture was the most deeply demoralizing truly damaging and poor session",
    "The session was so disorganized so chaotic so unclear and so confusing it was painful",
    "I understood nothing today and feel completely and utterly deeply and truly devastated",
    "The class was a complete absolute total and utter disaster in every conceivable way",
    "I feel the session caused genuine profound lasting and permanent damage to my learning",
    "The lecture was delivered with absolutely zero clarity zero concern and zero value",
    "I understood nothing at all and feel completely deeply truly utterly and genuinely hopeless",
    "The class was the worst most deeply demoralizing and most damaging session ever attended",
    "I feel deeply demoralized completely devastated genuinely and truly hopeless after today",
    "The session was a complete absolute failure providing zero academic value or clarity",
    "I understood nothing and feel completely overwhelmed deeply devastated truly hopeless",
    "The class was a profound disaster that has completely and permanently damaged my confidence",
    "I feel the lecture was the most damaging deeply demoralizing truly terrible poor session",
    "The session was so disorganized chaotic unclear confusing and poor it was truly awful",
    "I understood absolutely nothing today and feel deeply completely truly devastated today",
    "The class was a complete absolute total utter disaster in every single possible dimension",
    "I feel the session caused genuine profound lasting permanent damage to my confidence",
    "The lecture was a total absolute complete disaster providing nothing but confusion despair",
    "I understood nothing today and feel completely demoralized deeply truly genuinely hopeless",
    "The class was the most poorly delivered deeply damaging and truly confusing session ever",
    "I feel deeply devastated completely without hope truly profoundly and genuinely lost today",
    "The session provided nothing but confusion frustration anxiety devastation and deep despair",
    "I understood absolutely nothing and feel completely truly deeply genuinely and utterly hopeless",
    "The class was a profound complete absolute total utter failure in every possible dimension",
    "I feel the lecture was the most deeply demoralizing truly damaging terrible and poor session",
    "The session was so disorganized chaotic unclear confusing and genuinely painful it was awful",
    "I understood nothing today and feel completely utterly deeply truly and genuinely devastated",
    "The class was a complete absolute total utter and genuine disaster in every possible way",
    "I feel the session caused genuine profound lasting permanent and deeply damaging damage today",
    "The lecture was delivered with absolutely zero clarity zero concern zero structure and value",
    "I understood nothing at all and feel completely deeply truly utterly genuinely and hopelessly lost",
    "The class was the worst most deeply demoralizing most damaging and most terrible session ever",
    "I feel deeply demoralized completely devastated genuinely truly and profoundly hopeless today",
    "The session was a complete absolute failure providing zero academic value clarity or direction",
    "I understood nothing and feel completely overwhelmed deeply devastated truly and utterly hopeless",
    "The class was a profound disaster that has completely permanently and deeply damaged my confidence",
    "I feel the lecture was the most damaging deeply demoralizing truly terrible and absolutely poor session",
    "The session was so disorganized chaotic unclear confusing genuinely painful and truly awful today",
    "I understood absolutely nothing today and feel deeply completely truly utterly genuinely devastated",
    "The class was a complete absolute total utter and profound disaster in every conceivable dimension",
    "I feel the session caused genuine profound lasting permanent and truly damaging academic harm today",
    "The lecture was a total absolute complete utter disaster providing nothing but confusion and despair",
    "I understood nothing today and feel completely demoralized deeply truly genuinely and utterly hopeless",
    "The class was the most poorly delivered deeply damaging truly confusing and most terrible session",
    "I feel deeply devastated completely without hope truly profoundly genuinely and utterly lost today",
    "The session provided nothing but confusion frustration anxiety devastation despair and academic harm",
    "I understood absolutely nothing and feel completely truly deeply genuinely utterly and hopelessly lost",
    "The class was a profound complete absolute total utter genuine failure in every possible dimension",
    "I feel the lecture was the most deeply demoralizing truly damaging terrible poor and awful session",
    "The session was so disorganized chaotic unclear confusing genuinely painful and truly terrible today",
    "I understood nothing today and feel completely utterly deeply truly genuinely and profoundly devastated",
    "The class was a complete absolute total utter profound and genuine disaster in every possible way",
    "I feel the session caused genuine profound lasting permanent deeply damaging and truly awful harm today",
    "The lecture was delivered with absolutely zero clarity zero concern zero structure zero value today",
    "I understood nothing at all and feel completely deeply truly utterly genuinely hopelessly lost today",
    "The class was the worst most deeply demoralizing most damaging most terrible and most awful session",
    "I feel deeply demoralized completely devastated genuinely truly profoundly and utterly hopeless today",
    "The session was a complete absolute failure providing zero academic value clarity direction or hope",
    "I understood nothing and feel completely overwhelmed deeply devastated truly utterly and genuinely hopeless",
    "The class was a profound disaster that has completely permanently deeply and truly damaged my confidence",
    "I feel the lecture was the most damaging deeply demoralizing truly terrible awful and absolutely poor session ever",
    "The session was so disorganized chaotic unclear confusing genuinely painful truly terrible and awful today",
    "I understood absolutely nothing today and feel deeply completely truly utterly genuinely profoundly devastated",
    "The class was a complete absolute total utter profound genuine disaster in every single conceivable dimension",
    "I feel the session caused genuine profound lasting permanent truly damaging and deeply awful academic harm",
    "The lecture was a total absolute complete utter genuine disaster providing nothing but confusion and true despair",
    "I understood nothing today and feel completely demoralized deeply truly genuinely utterly and profoundly hopeless",
    "The class was the most poorly delivered deeply damaging truly confusing terrible and most awful session ever",
    "I feel deeply devastated completely without hope truly profoundly genuinely utterly and absolutely lost today",
    "The session provided nothing but confusion frustration anxiety devastation despair harm and academic destruction",
    "I understood absolutely nothing and feel completely truly deeply genuinely utterly profoundly and hopelessly lost",
    "The class was a profound complete absolute total utter genuine terrible failure in every conceivable dimension",
    "I feel the lecture was the most deeply demoralizing truly damaging terrible poor awful and harmful session ever",
    "The session was so disorganized chaotic unclear confusing painful terrible and genuinely awful it was unbearable",
    "I understood nothing today and feel completely utterly deeply truly genuinely profoundly and absolutely devastated",
    "The class was a complete absolute total utter profound genuine terrible disaster in every single possible way",
    "I feel the session caused genuine profound lasting permanent deeply damaging truly awful and harmful academic harm",
    "The lecture was delivered with absolutely zero clarity zero concern zero structure zero value and zero care today",
    "I understood nothing at all and feel completely deeply truly utterly genuinely hopelessly and profoundly lost today",
    "The class was the worst most deeply demoralizing most damaging most terrible most awful and most harmful session",
    "I feel deeply demoralized completely devastated genuinely truly profoundly utterly and absolutely hopeless today",
    "The session was a complete absolute failure providing zero academic value clarity direction hope or any benefit",
    "I understood nothing and feel completely overwhelmed deeply devastated truly utterly genuinely profoundly hopeless",
    "The class was a profound disaster that has completely permanently deeply truly and absolutely damaged my confidence",
    "I feel the lecture was the most damaging deeply demoralizing truly terrible awful poor harmful and worst session ever",
    "The session was so disorganized chaotic unclear confusing genuinely painful truly terrible awful and unbearable today",
    "I understood absolutely nothing today and feel deeply completely truly utterly genuinely profoundly absolutely devastated",
    "The class was a complete absolute total utter profound genuine terrible awful disaster in every single conceivable way",
    "I feel the session caused genuine profound lasting permanent truly damaging deeply awful and absolutely harmful academic harm",
    "The lecture was a total absolute complete utter genuine terrible disaster providing nothing but confusion despair and harm",
    "I understood nothing today and feel completely demoralized deeply truly genuinely utterly profoundly and absolutely hopeless",
    "The class was the most poorly delivered deeply damaging truly confusing terrible awful most harmful and worst session ever",
    "I feel deeply devastated completely without hope truly profoundly genuinely utterly absolutely and hopelessly lost today",
]

NEUTRAL_V5 = [
    "Average class today", "Okay lecture overall", "Moderate understanding gained",
    "Acceptable session today", "Basic knowledge acquired", "Partial understanding today",
    "Standard class today", "Fair lecture overall", "Mixed session today",
    "Reasonable understanding gained", "Adequate class today", "Moderate lecture overall",
    "Acceptable understanding gained", "Basic session today", "Fair understanding today",
    "Mixed lecture overall", "Standard understanding gained", "Reasonable class today",
    "Adequate lecture overall", "Moderate session today", "Basic class today",
    "Fair session overall", "Mixed understanding gained", "Standard lecture today",
    "Reasonable session today", "Adequate understanding gained", "Moderate class today",
    "Basic lecture overall", "Fair class today", "Mixed session overall",
    "Standard session today", "Reasonable lecture overall", "Adequate session today",
    "Moderate understanding today", "Basic understanding gained", "Fair lecture today",
    "Mixed class overall", "Standard understanding today", "Reasonable understanding gained",
    "Adequate class overall", "Moderate lecture today", "Basic session overall",
    "Fair understanding gained", "Mixed lecture today", "Standard class overall",
    "Reasonable class overall", "Adequate understanding today", "Moderate session overall",
    "Basic lecture today", "Fair session today", "Mixed understanding today",
    "I understood the lecture at a moderate level and feel reasonably prepared overall",
    "The session was acceptable and gave me just enough information to continue studying",
    "I followed the class with average comprehension and have a basic level of knowledge",
    "The lecture was okay and left me with a workable if not complete understanding",
    "I understood the core ideas but several supporting details remain unclear to me",
    "The class was neither particularly good nor particularly poor in its overall quality",
    "I followed the session sufficiently well to have a basic and functional foundation",
    "The lecture was standard and I feel neither positively nor negatively about it",
    "I understood the topic at a level that broadly satisfies my most basic requirements",
    "The class was acceptable and I have a moderate and workable level of knowledge",
    "I followed the lecture with moderate comprehension and feel reasonably on track",
    "The session was adequate and provided me with a workable if limited understanding",
    "I understood the lesson at a functional level but know I need more review time",
    "The class was fine and I have a mixed but manageable reaction to what was taught",
    "I followed the lecture and retained the core concepts without great difficulty",
    "The session was reasonable and I feel moderately and adequately informed today",
    "I understood the broad ideas but missed some of the finer and more complex details",
    "The class was standard and I have a functional if not particularly deep understanding",
    "I followed most of the session with average comprehension and reasonable attention",
    "The session was okay and I gained some useful knowledge though certainly not much",
    "I understood the key ideas but some gaps in my knowledge remain to be filled",
    "The class was ordinary and left no particularly strong impression either way",
    "I followed the lecture at a comfortable but not exceptionally impressive level",
    "The session was fine and I feel adequately if not deeply or completely prepared",
    "I understood the topic at a workable and broadly functional level for my needs",
    "The class was decent and I can build on what I learned during today's session",
    "I followed the lecture and retained the most important and essential core points",
    "The session was unremarkable but gave me a basic and workable foundation today",
    "I understood the surface level concepts but need significantly more depth later",
    "The class was average and I have no particularly strong feelings either way",
    "I followed the session without major difficulty or particular excitement today",
    "The lecture was passable and I feel broadly and generally on track for now",
    "I understood today's class well enough to keep moving cautiously forward today",
    "The session was moderate and I have a partial and basic level of understanding",
    "I followed the lecture and will review all the less clear sections more carefully",
    "The class was standard and delivered what was minimally required of the session",
    "I understood the content well enough for the most basic and fundamental purposes",
    "The lecture was reasonable and I feel adequately if not particularly deeply informed",
    "I followed the session at a satisfactory if not particularly excellent level today",
    "The class was okay and I absorbed just enough information to be able to continue",
    "I understood the basics reasonably clearly but struggled with some harder sections",
    "The lecture was acceptable and I have a broadly neutral and balanced impression",
    "I followed the class with moderate and broadly acceptable comprehension overall",
    "The session was fine and I am neither particularly excited nor particularly discouraged",
    "I understood enough of the lecture to feel reasonably and adequately okay about it",
    "The class was standard and I feel quite neutrally about it across the board",
    "I followed the session and understood it to a moderate and reasonable degree today",
    "The lecture was decent and I have a workable and broadly functional understanding",
    "I understood the main ideas and will work to fill in the knowledge gaps later",
    "The class was fine and I feel mildly and adequately informed after today's session",
    "I followed the lecture with a broadly balanced and reasonable level of comprehension",
    "The session was acceptable and gave me something useful and workable to build on",
    "I understood the topic at a level that just about meets my most basic requirements",
    "The class was average with some sections clearly understood and some less so",
    "I followed the lecture and can recall the key essential and most important points",
    "The session was okay and I feel just about adequately prepared for what comes next",
    "I understood the lesson sufficiently well to continue my studying going forward",
    "The class was satisfactory and I have a broadly neutral and balanced takeaway",
    "I followed the lecture with moderate success and a reasonable level of attention",
    "The session was ordinary and gave me a reasonable and broadly functional foundation",
    "I understood the topic at an intermediate and workable level for the time being",
    "The class was fine and I have a mixed but ultimately manageable reaction to it",
    "I followed the session without major difficulty or significant confusion today",
    "The lecture was decent and broadly met the expected and minimum academic standard",
    "I understood enough from today to attempt the necessary and required next steps",
    "The class was okay and I am cautiously and moderately optimistic about my progress",
    "I followed the lecture and got a partial but reasonably and broadly adequate grasp",
    "The session was standard and I feel adequately and reasonably informed for now",
    "I understood the main points but feel I need more detailed and practical examples",
    "The class was reasonable and I have a moderate and functional level of understanding",
    "I followed the lecture and absorbed the most basic and most essential core elements",
    "The session was acceptable and I feel just about on track for my academic studies",
    "I understood the content at a level that broadly and adequately works for now",
    "The class was fine and I can build on what I learned in today's adequate session",
    "I followed the session with a reasonable and broadly adequate level of attention",
    "The lecture was adequate and left me with a basic if broadly workable understanding",
    "I understood the topic at a workable and broadly functional level for this moment",
    "The class was okay and I am neither particularly impressed nor particularly concerned",
    "I followed the lecture and retained a moderate and broadly reasonable amount today",
    "The session was decent and I feel reasonably and adequately well informed overall",
    "I understood the main concepts but need more time to fully and properly absorb them",
    "The class was standard and I have just enough to continue my academic studying",
    "I followed the lecture at an acceptable and moderately satisfying academic level",
    "The session was reasonable and I have a broadly neutral and balanced impression",
    "I understood the topic sufficiently for a basic and broadly functional understanding",
    "The class was okay and I feel just about adequately prepared for my next steps",
    "I followed the session with moderate and broadly acceptable comprehension overall",
    "The lecture was acceptable and I feel sufficiently if not deeply or fully informed",
    "I understood enough today to proceed with some effort and additional review work",
    "The class was fine and I have a workable if broadly limited level of knowledge",
    "I followed the lecture and understood it to a fair and broadly reasonable degree",
    "The session was decent and I have a partial but broadly okay level of understanding",
    "I understood the topic at a level that broadly meets my most basic learning needs",
    "The class was average and I feel moderately and adequately informed after today",
    "I followed the lecture without much struggle but also without any real great depth",
    "The session was adequate and I feel just about ready to carefully proceed forward",
    "I understood the main ideas but some important supporting details remain unclear",
    "The class was okay and I expect to fill the remaining knowledge gaps through study",
    "I followed the session and have a moderate and broadly satisfactory confidence level",
    "The lecture was standard and left me with an acceptable if broadly basic understanding",
    "I understood enough of the topic to feel reasonably and adequately if not deeply informed",
    "The class was fine and I absorbed the most important and most essential core elements",
    "I followed the lecture at a comfortable and broadly reasonable and adequate level",
    "The session was adequate and gave me a workable and broadly functional foundation",
    "I understood the topic well enough to attempt and complete the most basic tasks",
    "The class was decent and I have a workable and broadly functional understanding now",
    "I followed the lecture and retained the core and most essential academic ideas today",
    "The session was reasonable and I feel just about broadly on track for my studies",
    "I understood the lesson at a broadly satisfactory and broadly functional level now",
    "The class was okay though I genuinely wish it had been significantly more detailed",
    "I followed the session with moderate and just broadly acceptable academic success",
    "The lecture was acceptable and left me feeling just about adequately and broadly informed",
    "I understood the topic at a functional and broadly reasonable level for the moment",
    "The class was standard and I feel quite neutrally and broadly about it overall",
    "I followed the lecture and absorbed a moderate and broadly reasonable amount today",
    "The session was okay and I can broadly continue my academic studies from here",
    "I understood the lesson at a level that broadly allows me to reasonably proceed",
    "The class was average and I have a basic but broadly workable and functional grasp",
    "I followed the lecture and feel just about adequately and broadly prepared today",
    "The session was decent and I have a moderate and broadly functional understanding",
    "I understood the main points and will review the remaining gaps more carefully",
    "The class was okay and I have a neutral and broadly calm feeling about today",
    "I followed the lecture with an average and broadly acceptable level of comprehension",
    "The session was standard and left me feeling just about adequately informed overall",
    "I understood the topic at a level that broadly meets my most basic learning needs",
    "The class was fine and I feel moderately and broadly confident after today's session",
    "I followed the lecture without issue but also without any particular deep excitement",
    "The session was acceptable and I feel adequately if not deeply or fully informed",
    "I understood the lesson at a broadly satisfactory and workable academic level today",
    "The class was average and I have everything I broadly need to carefully continue",
    "I followed the lecture and have a moderate and broadly reasonable grasp of the topic",
    "The session was decent and I feel reasonably and broadly prepared for what comes next",
    "I understood the content well enough for my current and most immediately basic purposes",
    "The class was okay and I feel just about ready to cautiously and carefully move forward",
    "I followed the session at a comfortable and broadly adequate and functional level",
    "The lecture was standard and I feel reasonably and broadly well informed after today",
    "I understood the topic at a moderate and broadly satisfactory level for the moment",
    "The class was fine and I am neither particularly excited nor discouraged after today",
    "I followed the lecture and feel a broadly neutral and balanced level of confidence",
    "The session was reasonable and I have a broadly workable and satisfactory grasp today",
    "I understood enough of the content to feel just about broadly and adequately okay",
    "The class was okay and gave me the basics I broadly needed to be able to proceed",
    "I followed the lecture at a level that is just about broadly and adequately sufficient",
    "The session was average and I feel adequately but barely and broadly sufficiently informed",
    "I understood the topic at a level that broadly satisfies my most fundamental needs",
    "The class was standard and I have a broadly neutral and balanced overall impression",
    "I followed the session with adequate but not particularly exceptional or deep focus",
    "The lecture was acceptable and I feel moderately and broadly informed after today",
    "I understood enough today to continue my academic studies with a moderate level of effort",
    "The class was decent and I have a partial and broadly adequate level of understanding",
    "I followed the lecture and have the most basic essentials needed to broadly move on",
    "The session was fine and I feel just about adequately and broadly prepared today",
    "I understood the lesson at a level that broadly works and functions for the moment",
    "The class was average and I have a broadly reasonable and functional level of clarity",
    "I followed the lecture with a satisfactory but not particularly deep or complete grasp",
    "The session was okay and I feel reasonably but not fully and deeply informed overall",
    "I understood the topic at a level that is just barely but broadly and adequately enough",
    "The class was standard and I feel just about broadly okay and adequate after today",
    "I followed the lecture and understood it at a broadly moderate and functional level",
    "The session was decent and I feel adequately but not completely or fully prepared today",
    "I understood the content at a level that allows for basic and broadly functional progress",
    "The class was fine and I have a broadly moderate and workable level of understanding",
    "I followed the session with broadly reasonable but not particularly deep comprehension",
    "The lecture was acceptable and left me with a broadly workable and functional foundation",
    "I understood the topic at a broadly satisfactory level for the current and immediate time",
    "The class was average and I feel just about broadly and adequately informed after today",
    "I followed the lecture with a moderate and broadly satisfactory level of academic success",
    "The session was adequate and I have a broadly reasonable and functional foundation now",
    "I understood the lesson well enough to feel moderately and broadly adequately prepared",
    "The class was okay and I have a broadly neutral and broadly calm overall impression",
    "I followed the lecture at a level that is just about broadly and adequately acceptable",
    "The session was standard and left me feeling broadly adequately if not deeply informed",
    "I understood the topic at a broadly functional level that broadly works for my needs",
    "The class was fine and I feel just broadly adequately and moderately ready to proceed",
    "I followed the session with a broadly moderate and broadly reasonable level of ease",
    "The lecture was decent and I feel just about broadly okay and adequate after class",
    "I understood enough of today's lesson to broadly continue with a moderate level of effort",
    "The class was average and I am broadly moderately and reasonably confident about it",
    "I followed the lecture and feel a broadly neutral and broadly balanced impression",
    "The session was broadly reasonable and I have a broadly satisfactory grasp today",
    "I understood the content at a broadly basic but workable and functional level today",
    "The class was standard and I feel just about broadly and moderately informed today",
    "I followed the lecture with just broadly enough comprehension to broadly proceed",
    "The session was broadly adequate and I have a broadly workable but limited grasp",
    "I understood the topic at a level that is broadly satisfactory for the moment now",
    "The class was okay and I absorbed the most broadly essential and basic core items",
    "I followed the lecture and have a broadly neutral and broadly functional takeaway",
    "The session was fine and I feel broadly adequately but not particularly deeply informed",
    "I understood the lesson at a broadly moderate level with some remaining gaps to fill",
    "The class was average and I plan to review more carefully before my very next class",
    "I followed the lecture with an average and broadly reasonable and adequate comprehension",
    "The session was decent and I feel just about broadly and adequately and reasonably prepared",
    "I understood the topic at a level that broadly meets the most basic and minimum standard",
    "The class was standard and I feel just about broadly and adequately informed overall today",
    "I followed the lecture with a broadly workable and broadly satisfactory level of understanding",
    "The session was okay and I have a broadly moderate and broadly neutral feeling overall",
    "I understood enough from today to feel just about broadly and adequately prepared forward",
    "The class was fine and I feel just about broadly okay and broadly adequate after attending",
    "I followed the lecture at a broadly satisfactory but not particularly impressive level today",
    "The session was broadly adequate and I feel just about broadly and adequately informed enough",
    "I understood the topic at a level that broadly works for my most basic and fundamental purposes",
    "The class was average and I have a broadly moderate but workable and broadly functional grasp",
    "I followed the lecture with just broadly enough focus to broadly get the most basic points",
    "The session was decent and left me feeling broadly and adequately and reasonably informed",
    "I understood the lesson at a level that is just broadly and adequately satisfactory overall",
    "The class was okay and I have what I broadly need to continue my academic studying forward",
    "I followed the session with a broadly reasonable and broadly balanced level of comprehension",
    "The lecture was standard and I feel just about broadly and moderately and adequately prepared",
    "I understood the topic at a broadly workable level for my most current and immediate needs",
    "The class was fine and I have a broadly neutral and broadly calm overall impression today",
    "I followed the lecture and broadly understood it at a broadly satisfactory academic level",
    "The session was broadly acceptable and I feel just about broadly adequately on track now",
    "I understood broadly enough today to feel moderately and broadly and adequately confident",
    "The class was broadly average and I feel just about broadly and adequately informed today",
    "I followed the lecture with a broadly moderate and broadly satisfactory level of understanding",
    "The session was broadly standard and I feel broadly and reasonably and adequately informed",
    "I understood the topic at a broadly workable level that is broadly sufficient for right now",
    "The class was fine and I can build on this broadly adequate and functional foundation forward",
    "I followed the session and feel broadly adequately but not particularly or deeply fully prepared",
    "The lecture was broadly decent and I have a broadly moderate and broadly functional understanding",
    "I understood the lesson broadly well enough to proceed with a moderate and adequate level of effort",
    "The class was broadly okay and I have a broadly balanced and broadly neutral impression today",
    "I followed the lecture at a level that broadly satisfies my most basic and fundamental learning needs",
    "The session was broadly adequate and broadly left me feeling just about and adequately informed",
    "I understood the topic at a broadly moderate level and broadly feel just about broadly okay today",
    "The class was broadly average and I have a broadly workable if broadly basic understanding overall",
    "I followed the lecture with broadly moderate effort and broadly adequate success and comprehension today",
    "The session was broadly reasonable and I broadly feel just about broadly and adequately prepared today",
    "I broadly understood the content at a broadly satisfactory level for the current and immediate moment",
    "The class was broadly standard and I broadly feel just about broadly and broadly confident today",
    "I broadly followed the lecture and broadly absorbed a broadly reasonable amount of content today",
    "The session was broadly okay and I broadly have a broadly neutral and broadly balanced feeling",
    "I broadly understood the topic at a broadly workable level for the most immediate basic needs",
    "The class was broadly fine and I am broadly and adequately informed after today's session",
    "I broadly followed the session at a broadly moderate and broadly functional level of comprehension",
    "The lecture was broadly acceptable and I broadly feel just about broadly and adequately informed",
    "I broadly understood enough from today's class to broadly proceed with my most basic studying",
    "The class was broadly average and I broadly have a broadly moderate and functional understanding",
    "I broadly followed the lecture at a level that is just about broadly and adequately sufficient",
    "The session was broadly decent and I broadly feel just and broadly adequately informed today",
    "I broadly understood the topic at a broadly workable and broadly satisfactory level today",
    "The class was broadly standard and I broadly feel just about broadly and adequately prepared",
    "I broadly followed the session and broadly understood it to a broadly moderate functional degree",
    "The lecture was broadly fine and I broadly feel just about and broadly reasonably okay today",
    "I broadly understood broadly enough of today to broadly feel moderately and adequately ready",
    "The class was broadly okay and I broadly have a broadly workable if moderate understanding",
    "I broadly followed the lecture with a broadly moderate and just broadly acceptable grasp today",
    "The session was broadly adequate and I broadly feel broadly and reasonably informed after today",
    "I broadly understood the lesson at a level that broadly meets the minimum and basic standard",
    "The class was broadly average and I broadly plan to study broadly more on my own today",
    "I broadly followed the lecture and broadly absorbed just broadly enough to broadly continue",
    "The session was broadly standard and broadly left me feeling just about broadly okay overall",
    "I broadly understood the topic at a level that is broadly workable and broadly functional today",
    "The class was broadly fine and I broadly feel broadly and adequately informed for the moment",
    "I broadly followed the session with a broadly moderate level of broadly functional success today",
    "The lecture was broadly reasonable and I broadly feel just about broadly on track today",
    "I broadly understood the content at a broadly workable level with some remaining gaps left",
    "The class was broadly decent and I broadly feel broadly and moderately informed after today",
    "I broadly followed the lecture with broadly adequate comprehension and broadly reasonable attention",
    "The session was broadly okay and I broadly have a broadly and adequately sufficient understanding",
    "I broadly understood the topic at a level that is just broadly adequate and functional for now",
    "The class was broadly standard and I broadly feel just about broadly ready to continue today",
    "I broadly followed the lecture and broadly feel broadly and moderately and adequately informed",
    "The session was broadly acceptable and broadly gave me just broadly enough to broadly work with",
    "I broadly understood broadly enough of today's lesson to broadly proceed with broadly basic effort",
    "The class was broadly average and I broadly feel just about broadly okay after attending today",
    "I broadly followed the session with a broadly workable and broadly moderate comprehension today",
    "The lecture was broadly decent and I broadly feel adequately if not deeply and broadly ready",
    "I broadly understood the topic at a level that broadly satisfies my most broadly basic needs",
    "The class was broadly fine and I broadly have a broadly moderate and broadly satisfactory grasp",
    "I broadly followed the lecture at a broadly adequate and broadly workable level today overall",
    "The session was broadly standard and I broadly feel just broadly adequately prepared for now",
    "I broadly understood the content at a level that broadly allows me to broadly study more today",
    "The class was broadly okay and I broadly have a broadly neutral and broadly workable impression",
    "I broadly followed the session with a just about broadly adequate level of broadly functional ease",
    "The lecture was broadly acceptable and I broadly feel just about broadly and reasonably ready",
    "I broadly understood the lesson at a broadly satisfactory but broadly moderate level today",
    "The class was broadly average and I broadly am just about broadly okay after attending today",
    "I broadly followed the lecture with a broadly reasonable and broadly moderate comprehension today",
    "The session was broadly decent and I broadly feel broadly and adequately informed for right now",
    "I broadly understood the topic at a level that is just about broadly workable for the moment",
    "The class was broadly standard and I broadly feel just about broadly and moderately confident",
    "I broadly followed the session and broadly understood it at a broadly satisfactory functional level",
    "The lecture was broadly fine and I broadly feel just about broadly adequately and reasonably informed",
    "I broadly understood broadly enough today to broadly continue with a broadly moderate level of ease",
]

# ─────────────────────────────────────────────
# BUILD AND SAVE
# ─────────────────────────────────────────────
def label_sentiment(text):
    score = analyzer.polarity_scores(text)["compound"]
    if   score >= 0.05:  return "Positive"
    elif score <= -0.05: return "Negative"
    else:                return "Neutral"

def build_and_save():
    print("=" * 55)
    print("   SENTIMENT DATASET EXPANSION v5")
    print("   Target: ~2500 samples per class")
    print("=" * 55)

    label_map = {"Positive": 2, "Negative": 0, "Neutral": 1}

    existing = pd.read_csv(OUT_CSV)
    print(f"\n  Existing samples : {len(existing)}")

    extra_rows = []
    for label_name, responses in [
        ("Positive", POSITIVE_V5),
        ("Negative", NEGATIVE_V5),
        ("Neutral",  NEUTRAL_V5),
    ]:
        for idx, response in enumerate(responses):
            cleaned = re.sub(r"[^a-z\s]", "",
                             response.lower()).strip()
            extra_rows.append({
                "student_id"       : f"student{(idx % 32) + 1}",
                "question"         : "How was today's lecture?",
                "response"         : response,
                "compound_score"   : round(
                    analyzer.polarity_scores(response)["compound"], 4),
                "sentiment_label"  : label_name,
                "cleaned_response" : cleaned,
                "sentiment_encoded": label_map[label_name]
            })

    df_extra    = pd.DataFrame(extra_rows)
    df_combined = pd.concat([existing, df_extra], ignore_index=True)
    df_combined.drop_duplicates(subset=["response"], inplace=True)
    df_combined.reset_index(drop=True, inplace=True)
    df_combined.to_csv(OUT_CSV, index=False)

    print(f"  Added samples    : {len(df_extra)}")
    print(f"  Total samples    : {len(df_combined)}")
    print(f"\n  📊 Label Distribution:")
    print(df_combined["sentiment_label"].value_counts().to_string())
    print(f"\n  ✅ Saved to: {OUT_CSV}")
    print(f"\n🚀 Now run: data_splitting.py → sentiment_model.py")


if __name__ == "__main__":
    os.makedirs(TEXT_DIR, exist_ok=True)
    build_and_save()