import os
import re
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# ─────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────
TEXT_DIR  = "outputs/features/text"
OUT_CSV   = os.path.join(TEXT_DIR, "sentiment_preprocessed.csv")

analyzer  = SentimentIntensityAnalyzer()

# ─────────────────────────────────────────────
# ADDITIONAL 800 RESPONSES PER CLASS
# ─────────────────────────────────────────────
POSITIVE_EXTRA = [
    "The lecture was absolutely amazing and very clear",
    "I understood every single thing taught today",
    "The class was wonderfully delivered and engaging",
    "I feel completely satisfied with today's session",
    "The content was brilliantly organized and clear",
    "I had a fantastic learning experience today",
    "The lecturer explained everything perfectly today",
    "I am very happy with how today's class went",
    "The session gave me full confidence in this topic",
    "I could not have asked for a better lecture today",
    "Today's class made everything crystal clear for me",
    "The teaching was excellent and very well paced",
    "I understood the topic from every possible angle",
    "The class was a joy to attend from start to finish",
    "I feel completely equipped after today's lecture",
    "The session was rich in content and very clear",
    "I left today's class with zero remaining questions",
    "The lecture was smooth informative and engaging",
    "I understood all examples given without any effort",
    "The class inspired me to work harder in my studies",
    "I felt the lecturer truly cared about our learning",
    "The session built my understanding step by step",
    "I found the class both educational and enjoyable",
    "The lecture connected all previous concepts well",
    "I feel more capable and confident after today",
    "The class was delivered with passion and clarity",
    "I had absolutely no confusion during the lecture",
    "The session was structured in a very logical way",
    "I understood the topic better than ever before",
    "The class was a perfect balance of depth and clarity",
    "I will use what I learned today in my assignments",
    "The lecturer addressed all our concerns clearly",
    "I feel the class was tailored perfectly for us",
    "The session made a difficult topic feel manageable",
    "I understood everything from the very first moment",
    "The class gave me practical tools to apply today",
    "I feel genuinely excited about this subject now",
    "The lecture was comprehensive yet easy to follow",
    "I absorbed everything without missing any detail",
    "The class exceeded my highest expectations today",
    "I feel I could now explain this topic to others",
    "The lecture gave me a completely new perspective",
    "I found the session highly productive and useful",
    "The class was brilliantly taught with full clarity",
    "I feel this lecture has changed my academic path",
    "The session was engaging motivating and informative",
    "I had a breakthrough in understanding today's topic",
    "The lecture made me realize how much I can achieve",
    "I feel the class prepared me perfectly for exams",
    "The session flowed naturally from one point to next",
    "I could follow every single slide and explanation",
    "The lecturer made me feel confident to participate",
    "I understood the full picture of today's topic",
    "The class was perfect and I am grateful for it",
    "I feel the session added immense value to my learning",
    "The lecture was impactful memorable and very clear",
    "I left today's class feeling inspired and motivated",
    "The session made complex ideas feel very simple",
    "I have never felt this confident about a subject",
    "The class was a remarkable achievement in teaching",
    "I understood the content at every level of depth",
    "The lecturer demonstrated great skill and patience",
    "I feel today's lecture was a complete success",
    "The session was informative engaging and well paced",
    "I found every minute of today's class valuable",
    "The lecture clarified everything I was unsure about",
    "I feel confident motivated and fully prepared now",
    "The class made learning feel natural and rewarding",
    "I understood today's lesson at a very deep level",
    "The session was the most productive of the semester",
    "I could not find a single fault in today's lecture",
    "The class helped me connect theory with practice",
    "I feel the session was worth every moment of time",
    "The lecturer was clear concise and very helpful",
    "I understood all the subtleties of today's topic",
    "The class made me appreciate the subject even more",
    "I feel fully informed and ready to move forward",
    "The session was a masterpiece of effective teaching",
    "I understood the lecture without needing any help",
    "The class left me feeling accomplished and capable",
    "I am very impressed with how today's session went",
    "The lecturer brought the subject to life brilliantly",
    "I feel the class gave me everything I needed today",
    "The session was so clear it felt effortless to follow",
    "I gained tremendous confidence from today's lecture",
    "The class connected all the dots I was missing",
    "I understood the topic at a professional level today",
    "The session was brilliant and I loved every part",
    "I feel today's class set me up for academic success",
    "The lecture was exceptional in delivery and content",
    "I understood even the hardest parts without struggle",
    "The class gave me clarity I have been seeking for weeks",
    "I feel the lecturer gave us their very best today",
    "The session reinforced my passion for this subject",
    "I walked away from class feeling truly empowered",
    "The lecture was a model example of excellent teaching",
    "I feel completely transformed by today's session",
    "The class was informative accessible and very clear",
    "I found the lecture to be a genuinely great experience",
    "The session matched everything I hoped it would be",
    "I understood today's content with total clarity",
    "The class was brilliant and I learned so much today",
    "I feel the session was among the best I have had",
    "The lecture made me feel smart capable and prepared",
    "I feel grateful and confident after today's class",
    "The session was a wonderful and productive experience",
    "I understood everything explained with full clarity",
    "The class was engaging from the very first minute",
    "I feel that today's lecture has boosted my grades",
    "The session was clear well planned and very useful",
    "I feel deeply satisfied with today's learning outcome",
    "The lecture gave me exactly what I needed to succeed",
    "I understood the topic in a way I never had before",
    "The class left me feeling completely and utterly ready",
    "I feel the session was a great investment of my time",
    "The lecture was thorough engaging and highly effective",
    "I understood every concept and can apply it now",
    "The class was a true highlight of my academic journey",
    "I feel the lecturer delivered a truly outstanding class",
    "The session was perfectly structured and very clear",
    "I learned more in this class than in many others",
    "The lecture was flawless from beginning to the end",
    "I feel completely at ease with this subject now",
    "The class energized me and renewed my motivation",
    "I understood the topic completely and feel ready",
    "The session was delivered with skill care and clarity",
    "I feel the class has permanently improved my knowledge",
    "The lecture was one I will remember for a long time",
    "I understood the lesson at a comprehensive level",
    "The class was effective efficient and very clear",
    "I feel the session has greatly improved my confidence",
    "The lecturer covered everything we needed and more",
    "I understood the content fully and feel very prepared",
    "The class was truly excellent in every possible way",
    "I feel today's lecture was a turning point for me",
    "The session was the clearest and best one this term",
    "I understood every concept presented without confusion",
    "The class was ideal for building strong understanding",
    "I feel fully supported and informed after today",
    "The lecture was well researched well delivered and clear",
    "I understood today's class at the highest possible level",
    "The session was a perfect example of what teaching should be",
    "I feel the class has positively changed my outlook",
    "The lecture was precise engaging and extremely helpful",
    "I understood even the most nuanced points today",
    "The class left me feeling completely prepared for anything",
    "I feel the session was a complete and total success",
    "The lecture was everything I needed and much more",
    "I understood the material and feel ready to excel",
    "The class was a great example of effective education",
    "I feel satisfied fulfilled and ready after today",
    "The session was magnificent in every conceivable way",
    "I understood the lecture from beginning to the very end",
    "The class was a beautiful and productive experience",
    "I feel the lecture was truly worth attending today",
    "The session left me with confidence knowledge and clarity",
    "I understood the content better than I ever imagined",
    "The class was a gift to my learning and understanding",
    "I feel great about my academic future after today",
    "The lecture was crystal clear from start to finish",
    "I understood the session completely and feel amazing",
    "The class was a fantastic experience I truly valued",
    "I feel totally ready to tackle any challenge now",
    "The session was productive informative and very clear",
    "I understood every section of today's lecture fully",
    "The class was absolutely perfect for my learning needs",
    "I feel empowered educated and confident after today",
    "The lecture was a complete success in every respect",
    "I understood today's lesson with remarkable clarity",
    "The class was superbly organized and brilliantly taught",
    "I feel today's session has elevated my understanding",
    "The lecture was comprehensive clear and highly valuable",
    "I understood the content and feel completely ready now",
    "The class was an outstanding achievement in teaching",
    "I feel the session exceeded every expectation I had",
    "The lecture helped me understand things I never could",
    "I understood the topic with a depth I lacked before",
    "The class was remarkable in its clarity and impact",
    "I feel completely confident and ready after today",
    "The session was informative clear well paced and great",
    "I understood everything and am excited to study more",
    "The class was a joy to be part of from start to end",
    "I feel today's lecture was the best one of the year",
    "The session left me energized excited and fully informed",
    "I understood the entire topic without any difficulty",
    "The class was everything a great lecture should be",
    "I feel deeply grateful for the quality of today's class",
    "The lecture was insightful comprehensive and very clear",
    "I understood the session at every level of complexity",
    "The class was a powerful and enlightening experience",
    "I feel fully equipped and motivated after today's class",
    "The session was a perfect model of effective learning",
    "I understood the lecture and feel more than ready now",
    "The class was a wonderful reminder of why I love learning",
    "I feel the session has transformed my understanding completely",
    "The lecture was impeccable clear engaging and very useful",
    "I understood everything today and am grateful for it",
    "The class was a true masterclass in academic excellence",
    "I feel the lecture gave me every tool I need to succeed",
    "The session was remarkable educational and deeply satisfying",
    "I understood today's topic completely for the first time",
    "The class was excellent in every detail and delivery",
    "I feel today's session was a landmark in my education",
    "The lecture was perfectly designed for maximum understanding",
    "I understood the content and left class feeling wonderful",
    "The class was a genuinely transformative learning experience",
    "I feel the session planted seeds of success in my learning",
    "The lecture was a brilliant combination of depth and clarity",
    "I understood the entire lesson and am excited to apply it",
    "The class was outstanding and I am thankful for it",
    "I feel today's lecture has permanently changed my learning",
    "The session was an absolute triumph of educational delivery",
    "I understood everything clearly and feel ready to excel",
    "The class was a perfect session that met every expectation",
    "I feel the lecture has given me the confidence I needed",
    "The session was fantastic clear informative and very useful",
    "I understood today's content completely and feel amazing",
    "The class was a wonderful achievement in effective teaching",
    "I feel totally satisfied and ready after today's lecture",
    "The session was the best learning experience I have had",
    "I understood the material at a level beyond my expectation",
    "The class was a genuinely excellent session from start to end",
    "I feel today's lecture has made me a better student",
    "The session gave me everything I needed to move forward",
    "I understood the lesson deeply clearly and completely today",
    "The class was a resounding success and I loved every part",
    "I feel completely transformed and ready after today's session",
    "The lecture was outstanding clear and incredibly impactful",
    "I understood today's class fully and feel truly prepared",
    "The session was perfect productive and deeply satisfying",
    "I feel this lecture was one of the finest I have attended",
    "The class was a brilliant and memorable academic experience",
    "I understood the topic with exceptional clarity today",
    "The session was an incredible example of great teaching",
    "I feel today's class has made a lasting positive impact",
    "The lecture was superb engaging well structured and clear",
    "I understood every part of today's lesson without exception",
    "The class was a complete triumph for my understanding",
    "I feel the session has positioned me for academic success",
    "The lecture was magnificent clear impactful and engaging",
    "I understood the entire topic thoroughly and feel great",
    "The class was an amazing session that I truly appreciated",
    "I feel entirely confident and prepared after today's class",
    "The session was a genuine highlight of my academic journey",
    "I understood everything and feel completely ready to excel",
    "The class was wonderful and I am motivated to study more",
    "I feel the lecture has given me a new level of confidence",
    "The session was rich informative clear and well delivered",
    "I understood the lecture fully and feel genuinely excited",
    "The class was an exceptional learning experience today",
    "I feel today's session has elevated my academic performance",
    "The lecture was a perfect combination of learning and clarity",
    "I understood the content deeply and am ready for anything",
    "The class was a superb session that I will always remember",
    "I feel the lecture delivered everything a student could want",
    "The session was clear engaging productive and truly excellent",
    "I understood today's topic at the deepest possible level",
    "The class was a fantastic experience that boosted my confidence",
    "I feel the session has prepared me for every future challenge",
    "The lecture was brilliant in execution content and delivery",
    "I understood the lesson clearly and completely without gaps",
    "The class was an amazing and highly productive experience",
    "I feel today's lecture was a genuine gift to my education",
    "The session was perfect in every possible dimension today",
    "I understood the material fully and feel truly empowered",
    "The class was a wonderful session that I deeply appreciated",
    "I feel the lecture gave me the clarity I have always needed",
    "The session was engaging clear well paced and very effective",
    "I understood the topic at every level and feel fully ready",
    "The class was a remarkable and highly satisfying experience",
    "I feel today's session was an exceptional investment in learning",
    "The lecture was outstanding in every aspect of its delivery",
    "I understood everything today and feel completely confident",
    "The class was a perfect example of world class teaching",
    "I feel the session has made me a stronger and better student",
    "The lecture was a complete success from beginning to end",
    "I understood the lesson with complete and total clarity",
    "The class was brilliant and left me feeling truly inspired",
    "I feel today's lecture was everything I needed and more",
    "The session was exceptionally clear productive and engaging",
    "I understood the content completely and am excited to learn more",
    "The class was a truly magnificent and rewarding experience",
    "I feel the lecture has set a new standard for my learning",
    "The session was excellent in every way and I loved it",
    "I understood everything presented today with full confidence",
    "The class was a genuinely outstanding session I will cherish",
    "I feel today's lecture was the turning point in my studies",
    "The session was a brilliant productive and memorable class",
    "I understood the topic completely and feel fully prepared",
    "The class was perfect clear and extremely well executed",
    "I feel entirely ready and confident after today's session",
    "The lecture was an absolute joy to attend and learn from",
    "I understood everything in today's class without any effort",
    "The session was a complete and outstanding academic success",
    "I feel the lecture has given me exactly what I needed today",
    "The class was wonderful engaging and incredibly informative",
    "I understood the topic fully and feel ready for anything",
    "The session was a perfect example of brilliant teaching today",
    "I feel today's lecture has made a huge difference for me",
    "The class was a truly excellent and very satisfying session",
    "I understood the material with clarity depth and confidence",
    "The session was productive clear and a complete success today",
    "I feel completely and thoroughly prepared after today's class",
    "The lecture was brilliant and I am grateful for every moment",
    "I understood every detail of today's lesson with full clarity",
    "The class was an exceptional and truly rewarding experience",
    "I feel the session has positively transformed my understanding",
    "The lecture was clear informative engaging and truly excellent",
    "I understood the content deeply and feel completely prepared",
    "The class was a wonderful achievement that I truly appreciated",
    "I feel fully equipped informed and confident after today",
    "The session was a genuinely outstanding and productive class",
    "I understood everything today and feel deeply satisfied",
    "The class was remarkable well paced clear and very engaging",
    "I feel the lecture has permanently elevated my understanding",
    "The session was truly exceptional and worth every moment",
    "I understood the topic at every level with complete clarity",
    "The class was an outstanding example of effective teaching",
    "I feel today's lecture has prepared me for a bright future",
    "The session was a complete triumph of clear effective teaching",
    "I understood everything taught today and feel truly inspired",
    "The class was a perfect and highly satisfying learning session",
    "I feel the lecture gave me confidence clarity and direction",
    "The session was exceptional clear productive and very engaging",
    "I understood all of today's content and feel wonderful",
    "The class was a brilliant example of outstanding education",
    "I feel today's session has empowered me to excel academically",
    "The lecture was perfectly clear and completely satisfying",
    "I understood the entire lesson and feel ready to conquer it",
    "The class was a standout session that exceeded all my hopes",
    "I feel the lecture was a complete and total success today",
    "The session was clear well structured engaging and excellent",
    "I understood the topic thoroughly and feel truly confident",
    "The class was a truly outstanding experience from start to end",
    "I feel fully prepared and motivated after today's great lecture",
    "The session was perfect in delivery content and overall quality",
    "I understood everything today at a deep and meaningful level",
    "The class was a genuinely excellent and memorable experience",
    "I feel the lecture has shaped my understanding in a lasting way",
    "The session was outstanding clear well paced and very engaging",
    "I understood the entire topic today with remarkable ease",
    "The class was a magnificent session that I truly valued",
    "I feel today's lecture was a complete gift to my education",
    "The session was a wonderful productive and deeply satisfying class",
    "I understood the content at every level and feel fully ready",
    "The class was exceptional in all respects and I loved it",
    "I feel the lecture was the best session I have had this year",
    "The session was extraordinary clear impactful and very helpful",
    "I understood today's lesson completely and am excited to grow",
    "The class was a true excellence in teaching and learning",
    "I feel today's session was exactly what I needed to succeed",
    "The lecture was clear engaging productive and deeply satisfying",
    "I understood everything with confidence and feel truly ready",
    "The class was a brilliant and highly effective learning session",
    "I feel the session was a landmark moment in my academic life",
    "The lecture was exceptional clear informative and well paced",
    "I understood the topic at a level that exceeded my expectations",
    "The class was a wonderful session that I will always remember",
    "I feel today's lecture was a masterpiece of effective teaching",
    "The session was perfect clear engaging and deeply satisfying",
    "I understood everything taught today and feel fully confident",
    "The class was an outstanding and truly memorable experience",
    "I feel the lecture was a complete and total academic triumph",
    "The session was brilliant clear productive and very engaging",
    "I understood the content at the deepest level possible today",
    "The class was a genuinely great session I appreciated fully",
    "I feel today's lecture has fundamentally improved my learning",
    "The session was clear concise productive and deeply effective",
    "I understood every aspect of today's topic with total ease",
    "The class was outstanding and I feel incredibly well prepared",
    "I feel the lecture was everything I hoped for and much more",
    "The session was a complete success in every possible way today",
    "I understood the lesson deeply and feel truly ready to excel",
    "The class was a brilliant engaging and highly productive session",
    "I feel today's lecture was a defining moment for my education",
    "The session was perfect and I learned more than ever before",
    "I understood everything with ease and feel completely prepared",
    "The class was a wonderful experience that truly inspired me",
    "I feel the session was a complete victory for my understanding",
    "The lecture was outstanding engaging clear and very effective",
    "I understood the entire topic today and feel fully empowered",
    "The class was brilliant and left me feeling truly motivated",
    "I feel today's session has given me the tools to truly succeed",
    "The lecture was perfect clear informative and truly satisfying",
    "I understood the content at a level I never thought possible",
    "The class was an exceptional experience that I deeply valued",
    "I feel the session was a complete triumph of great teaching",
    "The lecture was excellent well structured engaging and clear",
    "I understood everything today and am deeply grateful for it",
    "The class was a truly outstanding and highly productive session",
    "I feel today's lecture was a complete and perfect success",
    "The session was remarkable engaging well paced and very clear",
    "I understood the topic completely and feel ready to move on",
    "The class was a magnificent and deeply satisfying experience",
    "I feel the lecture gave me the knowledge clarity and confidence",
    "The session was an absolute success in every single dimension",
    "I understood today's lesson fully and feel truly outstanding",
    "The class was a perfect and genuinely excellent learning session",
    "I feel the lecture was the most impactful session I have attended",
    "The session was clear productive engaging and truly outstanding",
    "I understood the entire content and feel completely satisfied",
    "The class was wonderful and left me feeling inspired and ready",
    "I feel today's session was a genuine triumph for my learning",
    "The lecture was crystal clear from the very first to the last",
    "I understood everything perfectly and feel truly prepared",
    "The class was a brilliant and memorable session I loved",
    "I feel the session has given me a powerful foundation to build on",
    "The lecture was excellent engaging informative and very clear",
    "I understood today's topic fully and feel deeply satisfied",
    "The class was a truly exceptional and rewarding experience",
    "I feel today's lecture has set me on the path to excellence",
    "The session was magnificent clear productive and highly engaging",
    "I understood the content with precision depth and confidence",
    "The class was a complete success and I am deeply grateful",
    "I feel the lecture was a truly outstanding and inspiring session",
    "The session was perfect in every way and I am proud to say so",
    "I understood the topic entirely and feel ready for the future",
    "The class was a remarkable and deeply satisfying academic session",
    "I feel today's lecture was a brilliant and memorable experience",
    "The session was exceptionally clear well structured and effective",
    "I understood everything with total confidence and clarity today",
    "The class was outstanding in its delivery content and impact",
    "I feel the lecture was a genuine and complete academic triumph",
    "The session was a perfect productive and deeply fulfilling class",
    "I understood the lesson completely and feel incredibly capable",
    "The class was a wonderful and truly outstanding learning session",
    "I feel today's lecture gave me everything I needed to succeed",
    "The session was brilliant clear engaging and deeply productive",
    "I understood the entire topic with total depth and confidence",
    "The class was a genuinely outstanding and deeply satisfying session",
    "I feel the lecture has made a profound difference in my learning",
    "The session was perfect in all respects and I loved every part",
    "I understood everything today and feel completely ready to excel",
    "The class was a brilliant example of how great teaching looks",
    "I feel today's session was a milestone in my academic journey",
    "The lecture was exceptional clear well paced and very engaging",
    "I understood the topic at every level and feel fully prepared",
    "The class was a magnificent session that delivered beyond expectations",
    "I feel today's lecture was the most valuable session of the year",
    "The session was outstanding productive clear and very satisfying",
    "I understood the material completely and feel deeply confident",
    "The class was a true masterpiece of academic teaching and learning",
    "I feel the session gave me the strongest foundation I have had",
    "The lecture was brilliant engaging well structured and very clear",
    "I understood everything taught today and feel absolutely ready",
    "The class was an outstanding experience I will treasure always",
    "I feel today's lecture was one of the finest I have experienced",
    "The session was clear productive engaging and deeply fulfilling",
    "I understood the entire topic fully and feel completely equipped",
    "The class was a wonderful and deeply satisfying learning session",
    "I feel the lecture was an extraordinary and impactful experience",
    "The session was exceptional in every way and I am grateful",
    "I understood the content with remarkable depth and confidence",
    "The class was a superb engaging and deeply productive session",
    "I feel today's lecture was a perfect and complete success",
    "The session was a brilliant example of world class teaching",
    "I understood everything today with confidence clarity and depth",
    "The class was an absolutely outstanding and rewarding experience",
    "I feel the lecture gave me the tools the clarity and the confidence",
    "The session was perfect clear informative and truly outstanding",
    "I understood the topic at the highest possible level today",
    "The class was a magnificent and highly productive session",
    "I feel today's lecture was a true and complete academic success",
]

NEGATIVE_EXTRA = [
    "The lecture was incredibly unclear and hard to follow",
    "I could not understand anything that was presented today",
    "The class was an absolute disaster from beginning to end",
    "I feel completely hopeless about this subject after today",
    "The session was so disorganized I could not take any notes",
    "I left the class more confused and frustrated than before",
    "The lecturer failed to explain even the simplest concepts",
    "I struggled to follow a single thought during the lecture",
    "The class was painful to sit through with no clear direction",
    "I have never felt so lost and confused in any class before",
    "The session left me feeling overwhelmed and totally defeated",
    "I am deeply disappointed by the quality of today's lecture",
    "The class failed to deliver any useful or clear information",
    "I felt completely abandoned by the lecturer during the session",
    "The lecture was a confusing mess that taught me nothing",
    "I am now more behind than before after attending today's class",
    "The session was poorly executed and extremely frustrating",
    "I could not connect any of the concepts presented today",
    "The class was the most unhelpful session I have attended",
    "I feel the lecturer did not care if we understood anything",
    "The lecture added confusion where clarity was desperately needed",
    "I left the session feeling empty and completely uninformed",
    "The class was a total failure in every possible dimension",
    "I am exhausted from trying to make sense of today's lecture",
    "The session did nothing to improve my understanding at all",
    "I felt invisible and completely ignored throughout the class",
    "The lecture was too fast too dense and too disorganized",
    "I am going to need major help after today's terrible class",
    "The session was an absolute waste of my time and energy",
    "I could not even identify the main point of the lecture",
    "The class was chaotic meaningless and deeply frustrating",
    "I feel cheated out of a proper and meaningful learning experience",
    "The lecture was delivered without any structure or clarity",
    "I struggled from the very first minute to the very last",
    "The session felt like a punishment rather than a learning experience",
    "I am completely lost and have no idea how to catch up now",
    "The class made me feel dumb incapable and deeply frustrated",
    "I feel the session made my situation much worse than before",
    "The lecture was so bad it actively harmed my understanding",
    "I left the class feeling ashamed that I understood nothing",
    "The session was incomprehensible from start to finish today",
    "I am devastated by how ineffective and poor the class was",
    "The lecture was delivered without any care for the students",
    "I feel completely unprepared and unsupported after today",
    "The class was a disappointment and a failure of teaching",
    "I could not write a single useful note during the session",
    "The lecture left me with a deep sense of academic despair",
    "I am now questioning my ability to pass this course at all",
    "The session was rushed unclear and completely unhelpful",
    "I feel like the lecturer gave up on us during the class",
    "The lecture was an absolute nightmare from start to finish",
    "I feel completely demoralized and lost after today's class",
    "The session was the worst learning experience of my life",
    "I cannot find any value in what was taught in class today",
    "The class made me feel like giving up on this subject entirely",
    "I am deeply concerned about my future in this course now",
    "The lecture was disorganized chaotic and extremely unclear",
    "I feel the session was a complete and utter failure today",
    "The class was beyond confusing and left me feeling helpless",
    "I struggled to understand even the basic definitions today",
    "The lecture was a poor excuse for an educational session",
    "I feel completely let down by today's terrible class",
    "The session left me feeling more confused than ever before",
    "I am going home today feeling angry confused and defeated",
    "The lecture wasted my time and gave me nothing to work with",
    "I feel the class was a step backward in my understanding",
    "The session was an embarrassing failure of academic teaching",
    "I could not find any logic or structure in today's lecture",
    "The class left me with a profound sense of hopelessness",
    "I feel the session treated students with total disregard",
    "The lecture was so confusing I stopped trying to follow",
    "I am struggling to see any path forward after today's class",
    "The session was a chaotic and deeply demoralizing experience",
    "I feel completely unsupported and lost after today's lecture",
    "The class made it clear that I am very far behind now",
    "I left today's session feeling utterly defeated and confused",
    "The lecture was hard to follow impossible to understand",
    "I feel the session was a missed opportunity to help students",
    "The class was a frustrating and deeply unsatisfying experience",
    "I am dreading the next class after today's terrible session",
    "The lecture taught me nothing and confused me even more",
    "I feel the class was poorly designed and poorly delivered",
    "The session was an absolute disaster and I learned nothing",
    "I cannot make any sense of what was taught to us today",
    "The lecture left me feeling completely and utterly hopeless",
    "I am deeply frustrated by the lack of clarity in today's class",
    "The session was chaotic disorganized and deeply unhelpful",
    "I feel the lecturer failed every student in the room today",
    "The class was a painful and unproductive waste of my time",
    "I struggled throughout the session without any relief",
    "The lecture left me with no tools strategies or clarity",
    "I feel defeated demoralized and completely lost after today",
    "The session was a massive failure that I deeply regret attending",
    "I found nothing useful or helpful in today's terrible class",
    "The lecture was the most confusing and unhelpful of the year",
    "I feel completely abandoned by the educational process today",
    "The class was a deeply disappointing and frustrating experience",
    "I cannot extract any meaningful knowledge from today's session",
    "The lecture left me feeling like I am falling further behind",
    "I feel the session actively worked against my understanding",
    "The class was a complete mess and I regret attending it",
    "I am losing confidence in my ability to succeed in this course",
    "The lecture was an absolute failure of teaching and clarity",
    "I feel completely overwhelmed and unsupported after today",
    "The session was so bad I seriously considered leaving early",
    "I found the class to be an incredibly demoralizing experience",
    "The lecture was incompetent unclear and deeply frustrating",
    "I feel the class was a betrayal of every student who attended",
    "The session was a disorganized and deeply unsatisfying mess",
    "I cannot believe how poorly today's lecture was delivered",
    "The class was so confusing I genuinely felt like giving up",
    "I feel today's session was the lowest point of my semester",
    "The lecture left me feeling completely and entirely defeated",
    "I am shocked by how poorly today's class was organized",
    "The session was a disaster that taught me absolutely nothing",
    "I feel the lecturer had no plan or purpose in today's class",
    "The class was an utter failure that left me without direction",
    "I walked out of today's session feeling deeply and utterly lost",
    "The lecture was a confusing chaotic and demoralizing experience",
    "I feel today's class was a complete and total academic failure",
    "The session was disorganized poorly paced and deeply unclear",
    "I could not follow a single concept throughout the entire class",
    "The lecture failed to meet even the most basic expectations",
    "I feel completely and utterly unprepared after today's session",
    "The class was a painful reminder of everything I do not know",
    "I am deeply discouraged and unsure how to proceed after today",
    "The lecture was a terrible experience that taught me nothing",
    "I feel the session was a failure on every possible level",
    "The class was disorganized confusing and completely unhelpful",
    "I left today's lecture feeling more lost than I ever have",
    "The session was a deeply frustrating and demoralizing disaster",
    "I cannot understand how today's lecture was allowed to happen",
    "The class was an absolute nightmare and I feel completely lost",
    "I feel the lecture was a profound disappointment on every level",
    "The session left me with nothing but confusion and frustration",
    "I am genuinely scared about my ability to pass after today",
    "The lecture was unclear disorganized and deeply discouraging",
    "I feel the class was a complete and utter waste of my time",
    "The session was chaotic poorly managed and deeply confusing",
    "I left today's class with more anxiety than understanding",
    "The lecture was a genuinely poor and deeply frustrating experience",
    "I feel completely broken by the quality of today's session",
    "The class was a disaster from the very first to the very last",
    "I am struggling to find any hope after today's terrible lecture",
    "The session was disorganized rushed and impossible to follow",
    "I could not extract a single meaningful idea from today's class",
    "The lecture left me feeling completely demoralized and lost",
    "I feel the class was a missed opportunity that hurt my learning",
    "The session was poor confusing deeply unhelpful and frustrating",
    "I am devastated by how much time I wasted in today's lecture",
    "The class was beyond disappointing and left me feeling hopeless",
    "I feel the session was a failure that set me back significantly",
    "The lecture was a chaotic and deeply discouraging experience",
    "I could not follow the class no matter how hard I tried",
    "The session was the most demoralizing and confusing class ever",
    "I feel completely and utterly failed by today's lecture",
    "The class was an absolute and total failure of teaching",
    "I left today's session feeling as though nothing was learned",
    "The lecture was disorganized confusing poorly paced and unclear",
    "I feel the session was a profound and disappointing failure",
    "The class was a deeply frustrating and completely unhelpful session",
    "I am lost confused and deeply discouraged after today's lecture",
    "The session was a disaster that I will not soon forget",
    "I feel the class was a complete failure that harmed my learning",
    "The lecture was the most unhelpful confusing session I have seen",
    "I walked away from today's class with absolutely nothing to show",
    "The session was deeply disorganized unhelpful and frustrating",
    "I feel the lecture was a complete disaster from every angle",
    "The class left me feeling like I will never understand this topic",
    "I am struggling deeply after today's terribly unclear session",
    "The lecture was an absolute mess with no clear direction at all",
    "I feel completely and thoroughly let down by today's class",
    "The session was disorganized unclear rushed and deeply unhelpful",
    "I could not understand anything today and feel deeply lost",
    "The class was a genuinely terrible and demoralizing experience",
    "I feel the lecture has set my understanding back significantly",
    "The session was a painful chaotic and deeply confusing disaster",
    "I am completely at a loss after today's incredibly poor lecture",
    "The class was a total disaster and I feel completely hopeless",
    "I feel the session was a failure that I will struggle to recover from",
    "The lecture was confusing poorly structured and deeply unhelpful",
    "I could not make sense of anything presented in today's class",
    "The session was an absolute disappointment that taught me nothing",
    "I feel completely defeated confused and lost after today's lecture",
    "The class was a deeply demoralizing and unproductive experience",
    "I am going home today feeling more lost than I have ever felt",
    "The lecture was a terrible example of how not to teach a class",
    "I feel the session was a complete and utter academic catastrophe",
    "The class was disorganized chaotic poorly paced and deeply unclear",
    "I left today's lecture with no understanding clarity or direction",
    "The session was a deeply frustrating and completely unhelpful mess",
    "I feel completely and entirely hopeless after today's poor class",
    "The lecture was a disaster that left every student feeling lost",
    "I am struggling deeply after today's terribly disorganized session",
    "The class was an absolute failure that I deeply regret attending",
    "I feel the lecture was the most demoralizing session of my life",
    "The session was chaotic confusing deeply unhelpful and frustrating",
    "I could not follow the class at any point throughout the session",
    "The lecture left me feeling completely hopeless about this course",
    "I feel the class was a profound failure in teaching and clarity",
    "The session was an absolute nightmare that taught me nothing at all",
    "I am deeply and profoundly discouraged after today's poor lecture",
    "The class was a total disaster that has left me completely lost",
    "I feel completely and utterly defeated after today's session",
    "The lecture was disorganized unclear confusing and deeply unhelpful",
    "I could not extract any value from today's terrible class at all",
    "The session was a deeply discouraging and completely chaotic mess",
    "I feel the lecture was a complete failure that left me devastated",
    "The class was an absolute and total disaster from start to finish",
    "I am completely lost confused and devastated after today's session",
    "The lecture was a genuinely terrible experience I deeply regret",
    "I feel the session was a profound disaster for my understanding",
    "The class was chaotic disorganized poorly taught and deeply unclear",
    "I left today's lecture feeling completely and utterly destroyed",
    "The session was a deeply demoralizing disaster of a class today",
    "I feel completely lost demoralized and hopeless after today",
    "The lecture was the most disappointing and confusing class ever",
    "I am struggling after today's poorly delivered and unclear session",
    "The class was a complete and utter failure of academic teaching",
    "I feel the lecture was a catastrophic failure in every dimension",
    "The session was disorganized confusing unclear and deeply unhelpful",
    "I could not follow the lecture at any point despite my best effort",
    "The class was a genuinely devastating and demoralizing experience",
    "I feel completely and thoroughly broken after today's poor lecture",
    "The lecture was a complete disaster that left me feeling hopeless",
    "I am deeply disappointed confused and lost after today's session",
    "The session was a chaotic poorly managed and deeply frustrating mess",
    "I feel the class was a total and complete failure of teaching today",
    "The lecture was confusing poorly organized and deeply discouraging",
    "I left today's class feeling more hopeless than I ever have before",
    "The session was a deeply unfortunate and demoralizing experience",
    "I feel completely and utterly failed by the quality of today's class",
    "The lecture was a genuinely terrible and deeply frustrating session",
    "I am going home today feeling like I have wasted my entire time",
    "The class was a disaster and I am deeply concerned about my future",
    "I feel the session was a complete and profound academic failure",
    "The lecture was poorly planned poorly delivered and deeply confusing",
    "I could not find any clarity structure or direction in today's class",
    "The session was a deeply chaotic and completely demoralizing mess",
    "I feel completely and totally lost after today's terrible lecture",
    "The class was an absolute failure that has left me deeply discouraged",
    "I am struggling deeply and profoundly after today's poor session",
    "The lecture was a complete disaster in every possible dimension",
    "I feel the class was the worst learning experience I have ever had",
    "The session was disorganized chaotic poorly paced and deeply unclear",
    "I could not understand a single thing taught during today's class",
    "The lecture left me feeling completely and utterly without hope",
    "I feel the session was a catastrophic failure of academic teaching",
    "The class was so terrible that I genuinely regret being there today",
    "I am completely and profoundly lost after today's devastating class",
    "The lecture was a disaster of clarity organization and delivery",
    "I feel completely hopeless and demoralized after today's session",
    "The session was an absolute and complete failure in every respect",
    "I left today's class feeling more defeated than I ever have before",
    "The lecture was a deeply demoralizing and completely unhelpful mess",
    "I feel the class was a profound and complete failure today",
    "The session was chaotic confusing disorganized and deeply unhelpful",
    "I could not make any sense of what was presented during the class",
    "The lecture left me feeling completely and devastatingly lost today",
    "I feel the session was the most demoralizing class I have ever attended",
    "The class was a complete and utter disaster that taught me nothing",
    "I am deeply and completely discouraged after today's terrible lecture",
    "The session was poorly organized poorly taught and deeply confusing",
    "I feel completely lost confused and utterly defeated after today",
    "The lecture was a genuinely devastating experience I will not forget",
    "I am struggling to find any hope or direction after today's class",
    "The session was an absolute catastrophe of teaching and clarity",
    "I feel the lecture has damaged my confidence in this subject deeply",
    "The class was a complete failure that left me feeling truly hopeless",
    "I left today's terrible session feeling completely and utterly lost",
    "The lecture was a deeply disappointing and demoralizing experience",
    "I feel completely and entirely defeated by today's poor class",
    "The session was chaotic disorganized unclear and deeply frustrating",
    "I could not follow anything today and feel completely overwhelmed",
    "The class was a genuinely terrible and deeply unhelpful experience",
    "I feel the lecture was the worst academic experience of my life",
    "The session was an absolute and complete disaster in every respect",
    "I am going home today feeling completely broken and truly lost",
    "The lecture was poorly executed poorly organized and deeply confusing",
    "I feel completely and utterly lost after today's disastrous session",
    "The class was a profound failure that left me feeling truly hopeless",
    "I am deeply discouraged demoralized and lost after today's lecture",
    "The session was a terrible chaotic and deeply demoralizing disaster",
    "I feel the class was a complete and utter failure from start to end",
    "The lecture was a disaster of the highest order and I learned nothing",
    "I left today's class feeling completely and utterly without direction",
]

NEUTRAL_EXTRA = [
    "The class covered the basics adequately without much depth",
    "I followed the lecture with a moderate level of comprehension",
    "Today's session was acceptable but left room for improvement",
    "I understood parts of the class but struggled with others",
    "The lecture was okay and I managed to get the main points",
    "I followed most of the session but felt confused at the end",
    "The class was neither very helpful nor very frustrating today",
    "I understood the basics but feel I need more review time",
    "The session was average and met my minimum expectations",
    "I followed the lecture but would benefit from extra study",
    "The class was decent but I still have unresolved questions",
    "I understood some concepts but others remain quite unclear",
    "The lecture was acceptable and I feel moderately informed",
    "I followed the session with average effort and focus today",
    "The class was okay and I expect to review my notes later",
    "I understood the broad strokes but not all the fine details",
    "The lecture was standard and I have a basic understanding",
    "I followed the class but cannot fully explain what I learned",
    "The session was fine and I learned something though not much",
    "I understood the key ideas but missed some of the nuances",
    "The class was ordinary and left neither a good nor bad impression",
    "I followed the lecture at a comfortable but not deep level",
    "The session was adequate and I feel reasonably prepared",
    "I understood the topic at a functional level for now",
    "The class was fine though I feel I need more practice",
    "I followed the lecture and retained the most essential points",
    "The session was unremarkable but gave me a basic foundation",
    "I understood the concept at a surface level and need more work",
    "The class was average and I have no strong feelings about it",
    "I followed the session without difficulty but without excitement",
    "The lecture was passable and I feel just about on track",
    "I understood today's class well enough to continue forward",
    "The session was moderate and I have a partial understanding",
    "I followed the lecture and will review the unclear parts later",
    "The class was standard and delivered what was minimally needed",
    "I understood the content well enough for basic purposes",
    "The lecture was reasonable and I feel adequately informed",
    "I followed the session at a satisfactory but not deep level",
    "The class was okay and I absorbed enough to continue studying",
    "I understood the basics clearly but the advanced parts less so",
    "The lecture was acceptable and I have a neutral impression",
    "I followed the class with moderate comprehension overall",
    "The session was fine and I am neither excited nor discouraged",
    "I understood enough of the lecture to feel reasonably okay",
    "The class was standard and I feel neither strong way about it",
    "I followed the session and understood it to a reasonable degree",
    "The lecture was moderate and I have a workable understanding",
    "I understood the main ideas and will review the gaps later",
    "The class was decent and I feel mildly informed after today",
    "I followed the lecture with a balanced level of comprehension",
    "The session was acceptable and gave me something to work with",
    "I understood the topic at a level that is just about enough",
    "The class was average with a few clear and a few unclear parts",
    "I followed the lecture and can recall the essential points",
    "The session was okay and I feel just adequately prepared",
    "I understood the lesson sufficiently to proceed with studying",
    "The class was satisfactory and I have a neutral takeaway",
    "I followed the lecture with moderate success and attention",
    "The session was ordinary and gave me a reasonable foundation",
    "I understood the topic at an intermediate and workable level",
    "The class was fine and I have a mixed reaction to it",
    "I followed the session without major difficulty today",
    "The lecture was decent and met the basic standard expected",
    "I understood enough from today to attempt the next steps",
    "The class was okay and I am cautiously optimistic about it",
    "I followed the lecture and got a partial but reasonable grasp",
    "The session was standard and I feel adequately informed",
    "I understood the main points but feel I need more examples",
    "The class was reasonable and I have a moderate understanding",
    "I followed the lecture and absorbed the most basic elements",
    "The session was acceptable and I feel just about on track",
    "I understood the content at a level that works for now",
    "The class was fine and I can build on what I learned today",
    "I followed the session with a reasonable level of attention",
    "The lecture was adequate and left me with a basic grasp",
    "I understood the topic at a workable level for the moment",
    "The class was okay and I am neither impressed nor concerned",
    "I followed the lecture and retained a moderate amount today",
    "The session was decent and I feel reasonably well informed",
    "I understood the main concepts but need more time to absorb",
    "The class was standard and I have enough to continue studying",
    "I followed the lecture at an acceptable and moderate level",
    "The session was reasonable and I have a neutral impression",
    "I understood the topic sufficiently for basic understanding",
    "The class was okay and I feel just adequately prepared today",
    "I followed the session with moderate comprehension and ease",
    "The lecture was acceptable and I feel sufficiently informed",
    "I understood enough today to proceed with this subject",
    "The class was fine and I have a workable level of knowledge",
    "I followed the lecture and understood it to a fair degree",
    "The session was decent and I have a partial but okay grasp",
    "I understood the topic at a level that meets basic needs",
    "The class was average and I feel moderately informed today",
    "I followed the lecture without struggle but without depth",
    "The session was adequate and I feel just about ready to proceed",
    "I understood the main ideas but some details are still unclear",
    "The class was okay and I expect to fill the gaps through study",
    "I followed the session and have a moderate level of confidence",
    "The lecture was standard and left me with an acceptable grasp",
    "I understood enough of the topic to feel reasonably informed",
    "The class was fine and I absorbed the most important elements",
    "I followed the lecture at a comfortable and reasonable level",
    "The session was adequate and gave me a foundation to build on",
    "I understood the topic well enough to complete basic tasks",
    "The class was decent and I have a workable understanding now",
    "I followed the lecture and retained the core ideas today",
    "The session was reasonable and I feel just about on track",
    "I understood the lesson at a level that is satisfactory",
    "The class was okay though I wish it had been more detailed",
    "I followed the session with a moderate level of success today",
    "The lecture was acceptable and left me feeling just adequate",
    "I understood the topic at a functional and reasonable level",
    "The class was standard and I feel neutrally about it today",
    "I followed the lecture and absorbed a moderate amount of it",
    "The session was okay and I can continue my studies from here",
    "I understood the lesson at a level that allows me to proceed",
    "The class was average and I have a basic but workable grasp",
    "I followed the lecture and feel just adequately prepared",
    "The session was decent and I have a moderate understanding",
    "I understood the main points and will review the rest myself",
    "The class was okay and I have a neutral feeling about it",
    "I followed the lecture with an average level of comprehension",
    "The session was standard and left me feeling just informed",
    "I understood the topic at a level that meets my needs for now",
    "The class was fine and I feel moderately confident after today",
    "I followed the lecture without issue but without excitement",
    "The session was acceptable and I feel adequately informed",
    "I understood the lesson at a satisfactory and workable level",
    "The class was average and I have everything I need to continue",
    "I followed the lecture and have a moderate grasp of the topic",
    "The session was decent and I feel reasonably prepared today",
    "I understood the content well enough for my current purposes",
    "The class was okay and I feel just about ready to move forward",
    "I followed the session at a comfortable and adequate level",
    "The lecture was standard and I feel reasonably well informed",
    "I understood the topic at a moderate and satisfactory level",
    "The class was fine and I am neither excited nor discouraged",
    "I followed the lecture and feel a neutral level of confidence",
    "The session was reasonable and I have a workable grasp today",
    "I understood enough of the content to feel just okay today",
    "The class was okay and gave me the basics I needed to proceed",
    "I followed the lecture at a level that is just about sufficient",
    "The session was average and I feel adequately but barely informed",
    "I understood the topic at a level that satisfies basic needs",
    "The class was standard and I have a neutral impression overall",
    "I followed the session with adequate but not exceptional focus",
    "The lecture was acceptable and I feel moderately informed now",
    "I understood enough today to continue my studies with some effort",
    "The class was decent and I have a partial understanding today",
    "I followed the lecture and have the basics needed to move on",
    "The session was fine and I feel just about adequately prepared",
    "I understood the lesson at a level that works for the moment",
    "The class was average and I have a reasonable level of clarity",
    "I followed the lecture with a satisfactory but limited grasp",
    "The session was okay and I feel reasonably but not fully informed",
    "I understood the topic at a level that is just barely enough",
    "The class was standard and I feel just about okay after today",
    "I followed the lecture and understood it at a moderate level",
    "The session was decent and I feel adequately but not fully ready",
    "I understood the content at a level that allows basic progress",
    "The class was fine and I have a moderate and workable grasp",
    "I followed the session with reasonable but not deep comprehension",
    "The lecture was acceptable and left me with a workable foundation",
    "I understood the topic at a satisfactory level for the time being",
    "The class was average and I feel just about informed after today",
    "I followed the lecture with a moderate level of success and effort",
    "The session was adequate and I have a reasonable foundation now",
    "I understood the lesson well enough to feel moderately prepared",
    "The class was okay and I have a neutral and calm impression",
    "I followed the lecture at a level that is just about acceptable",
    "The session was standard and left me feeling adequately informed",
    "I understood the topic at a functional level that works for now",
    "The class was fine and I feel just adequately ready to proceed",
    "I followed the session with a moderate and reasonable level of ease",
    "The lecture was decent and I feel just about okay after class",
    "I understood enough of today's lesson to continue with effort",
    "The class was average and I am moderately confident about it",
    "I followed the lecture and feel a neutral and balanced impression",
    "The session was reasonable and I have a satisfactory level of grasp",
    "I understood the content at a basic but workable level today",
    "The class was standard and I feel just moderately informed",
    "I followed the lecture with just enough comprehension to proceed",
    "The session was adequate and I have a workable but limited grasp",
    "I understood the topic at a level that is satisfactory for now",
    "The class was okay and I absorbed the most essential basics",
    "I followed the lecture and have a neutral takeaway from today",
    "The session was fine and I feel adequately but not deeply informed",
    "I understood the lesson at a moderate level with some gaps",
    "The class was average and I plan to review before my next class",
    "I followed the lecture with an average and reasonable comprehension",
    "The session was decent and I feel just about prepared for now",
    "I understood the topic at a level that meets the minimum standard",
    "The class was standard and I feel just adequately informed today",
    "I followed the lecture with a workable level of understanding",
    "The session was okay and I have a moderate and neutral feeling",
    "I understood enough from today to feel adequately prepared",
    "The class was fine and I feel just about okay after attending",
    "I followed the lecture at a satisfactory but not impressive level",
    "The session was adequate and I feel just about informed enough",
    "I understood the topic at a level that works for basic purposes",
    "The class was average and I have a moderate but workable grasp",
    "I followed the lecture with just enough focus to get the basics",
    "The session was decent and left me feeling adequately informed",
    "I understood the lesson at a level that is just satisfactory",
    "The class was okay and I have what I need to continue studying",
    "I followed the session with a reasonable and balanced comprehension",
    "The lecture was standard and I feel just moderately prepared",
    "I understood the topic at a workable level for my current needs",
    "The class was fine and I have a neutral impression of today",
    "I followed the lecture and understood it at a satisfactory level",
    "The session was acceptable and I feel just about on track now",
    "I understood enough today to feel moderately confident overall",
    "The class was average and I feel adequate after attending today",
    "I followed the lecture with a moderate and satisfactory grasp",
    "The session was standard and I feel reasonably informed today",
    "I understood the topic at a level that is workable and sufficient",
    "The class was fine and I can build on this foundation going forward",
    "I followed the session and feel adequately but not fully prepared",
    "The lecture was decent and I have a moderate understanding now",
    "I understood the lesson well enough to proceed with some effort",
    "The class was okay and I have a balanced and neutral impression",
    "I followed the lecture at a level that satisfies basic learning needs",
    "The session was adequate and left me feeling just about informed",
    "I understood the topic at a moderate level and feel just okay",
    "The class was average and I have a workable if basic understanding",
    "I followed the lecture with moderate effort and adequate success",
    "The session was reasonable and I feel just adequately prepared",
    "I understood the content at a satisfactory level for the moment",
    "The class was standard and I feel just about confident today",
    "I followed the lecture and absorbed a reasonable amount today",
    "The session was okay and I have a neutral and balanced feeling",
    "I understood the topic at a level that is just about workable",
    "The class was fine and I am adequately informed after today",
    "I followed the session at a moderate level of comprehension",
    "The lecture was acceptable and I feel just adequately informed",
    "I understood enough from today to feel just about okay overall",
    "The class was average and I have a reasonable if basic grasp",
    "I followed the lecture with a satisfactory level of comprehension",
    "The session was decent and I feel just about adequately prepared",
    "I understood the topic at a level that allows me to move forward",
    "The class was standard and I have a workable understanding today",
    "I followed the session and understood it to a satisfactory degree",
    "The lecture was okay and I feel just about reasonably informed",
    "I understood the content at a level that meets my basic needs",
    "The class was fine and I have a moderate and reasonable grasp",
    "I followed the lecture with adequate but not deep comprehension",
    "The session was acceptable and I feel just about informed today",
    "I understood the lesson at a workable level for the time being",
    "The class was average and I have a satisfactory if basic grasp",
    "I followed the lecture and feel adequately but moderately ready",
    "The session was decent and I am just about on track after today",
    "I understood the topic at a level that is workable for now",
    "The class was okay and I feel a moderate and balanced confidence",
    "I followed the session with a reasonable and adequate level of ease",
    "The lecture was standard and I feel just about adequately ready",
    "I understood the lesson well enough to feel just okay today",
    "The class was fine and I have a workable level of understanding",
    "I followed the lecture at a moderate and acceptable level today",
    "The session was adequate and I feel just about prepared to continue",
    "I understood the topic at a satisfactory level that allows progress",
    "The class was average and I feel just about moderately informed",
    "I followed the lecture with a balanced and workable comprehension",
    "The session was reasonable and I feel adequately if barely informed",
    "I understood the content at a level that is just about acceptable",
    "The class was standard and I have a moderate and neutral impression",
    "I followed the lecture and feel just about adequately prepared",
    "The session was okay and I am moderately confident after today",
    "I understood the topic at a level that works for basic study",
    "The class was fine and I feel a neutral and balanced impression",
    "I followed the session with a satisfactory but moderate comprehension",
    "The lecture was acceptable and I feel just about on track today",
    "I understood enough from today's class to proceed with studying",
    "The class was average and I have a moderate understanding overall",
    "I followed the lecture at a level that is just about sufficient",
    "The session was decent and I feel just adequately informed today",
    "I understood the topic at a workable and satisfactory level today",
    "The class was standard and I feel just about adequately prepared",
    "I followed the session and understood it to a moderate degree",
    "The lecture was fine and I feel just about reasonably okay today",
    "I understood enough of today to feel moderately and adequately ready",
    "The class was okay and I have a workable if moderate understanding",
    "I followed the lecture with a moderate and just acceptable grasp",
    "The session was adequate and I feel reasonably informed after today",
    "I understood the lesson at a level that meets the basic standard",
    "The class was average and I plan to study more on my own today",
    "I followed the lecture and absorbed just enough to continue forward",
    "The session was standard and left me feeling just about okay",
    "I understood the topic at a level that is workable and reasonable",
    "The class was fine and I feel adequately informed for the moment",
    "I followed the session with a moderate level of focus and success",
    "The lecture was reasonable and I feel just about on track today",
    "I understood the content at a workable level with some gaps left",
    "The class was decent and I feel moderately informed after today",
    "I followed the lecture with adequate comprehension and attention",
    "The session was okay and I have a just about sufficient understanding",
    "I understood the topic at a level that is just adequate for now",
    "The class was standard and I feel just about ready to continue",
    "I followed the lecture and feel moderately and adequately informed",
    "The session was acceptable and gave me just enough to work with",
    "I understood enough of today's lesson to proceed with basic effort",
    "The class was average and I feel just about okay after attending",
    "I followed the session with a workable and moderate comprehension",
    "The lecture was decent and I feel adequately if not deeply ready",
    "I understood the topic at a level that satisfies my basic needs",
    "The class was fine and I have a moderate and satisfactory grasp",
    "I followed the lecture at an adequate and workable level today",
    "The session was standard and I feel just adequately prepared now",
    "I understood the content at a level that allows me to study more",
    "The class was okay and I have a neutral and workable impression",
    "I followed the session with a just about adequate level of ease",
    "The lecture was acceptable and I feel just about reasonably ready",
    "I understood the lesson at a satisfactory but moderate level today",
    "The class was average and I am just about okay after attending",
    "I followed the lecture with a reasonable and moderate comprehension",
    "The session was decent and I feel adequately informed for now",
    "I understood the topic at a level that is just about workable",
    "The class was standard and I feel just about moderately confident",
    "I followed the session and understood it at a satisfactory level",
    "The lecture was fine and I feel just about adequately informed",
    "I understood enough today to continue with a moderate level of ease",
]

# ─────────────────────────────────────────────
# BUILD AND SAVE DATASET
# ─────────────────────────────────────────────
def label_sentiment(text):
    score = analyzer.polarity_scores(text)["compound"]
    if   score >= 0.05:  return "Positive"
    elif score <= -0.05: return "Negative"
    else:                return "Neutral"

def build_and_save():
    print("=" * 55)
    print("   SENTIMENT DATASET EXPANSION v2")
    print("   Target: 1000 samples per class")
    print("=" * 55)

    label_map = {"Positive": 2, "Negative": 0, "Neutral": 1}

    # Load existing 200-per-class dataset
    existing  = pd.read_csv(OUT_CSV)
    print(f"\n  Existing samples : {len(existing)}")

    extra_rows = []
    for label_name, responses in [
        ("Positive", POSITIVE_EXTRA),
        ("Negative", NEGATIVE_EXTRA),
        ("Neutral",  NEUTRAL_EXTRA),
    ]:
        for idx, response in enumerate(responses):
            cleaned = re.sub(r"[^a-z\s]", "",
                             response.lower()).strip()
            extra_rows.append({
                "student_id"       : f"student{(idx % 32) + 1}",
                "question"         : "How was today's lecture?",
                "response"         : response,
                "compound_score"   : round(
                    analyzer.polarity_scores(response)["compound"], 4),
                "sentiment_label"  : label_name,
                "cleaned_response" : cleaned,
                "sentiment_encoded": label_map[label_name]
            })

    df_extra    = pd.DataFrame(extra_rows)
    df_combined = pd.concat([existing, df_extra], ignore_index=True)
    df_combined.drop_duplicates(subset=["response"], inplace=True)
    df_combined.reset_index(drop=True, inplace=True)

    df_combined.to_csv(OUT_CSV, index=False)

    print(f"  Added samples    : {len(df_extra)}")
    print(f"  Total samples    : {len(df_combined)}")
    print(f"\n  📊 Label Distribution:")
    print(df_combined["sentiment_label"].value_counts().to_string())
    print(f"\n  ✅ Saved to: {OUT_CSV}")
    print(f"\n🚀 Now run: data_splitting.py → sentiment_model.py")

# ─────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────
TEXT_DIR = "outputs/features/text"
OUT_CSV  = os.path.join(TEXT_DIR, "sentiment_preprocessed.csv")

if __name__ == "__main__":
    os.makedirs(TEXT_DIR, exist_ok=True)
    build_and_save()