import os
import re
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# ─────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────
TEXT_DIR = "outputs/features/text"
OUT_CSV  = os.path.join(TEXT_DIR, "sentiment_preprocessed.csv")
analyzer = SentimentIntensityAnalyzer()

# ─────────────────────────────────────────────
# 500 FINAL RESPONSES PER CLASS
# Highly distinct from previous batches
# ─────────────────────────────────────────────
POSITIVE_V4 = [
    "Today's lecture was a masterpiece of academic delivery",
    "I walked into class uncertain and left feeling fully capable",
    "The session gave me a complete and lasting understanding",
    "I feel the lecturer genuinely cared about our comprehension",
    "The class was a turning point in my grasp of this subject",
    "I understood the topic in ways I never thought possible",
    "The lecture made every concept feel natural and achievable",
    "I feel grateful for the exceptional quality of today's class",
    "The session inspired me to push further in my studies",
    "I understood the full depth of today's topic with ease",
    "The class was a complete revelation from start to finish",
    "I feel today's lecture unlocked something important for me",
    "The session was a genuine highlight of my entire semester",
    "I understood everything without needing to ask a question",
    "The class reinforced my belief that I can master this subject",
    "I feel today's lecture was the most impactful of the course",
    "The session built my understanding systematically and clearly",
    "I understood the lesson and feel completely academically ready",
    "The class was a wonderful model of how teaching should work",
    "I feel the lecture delivered genuine and lasting academic value",
    "The session was thorough accessible engaging and very clear",
    "I understood every connection between concepts presented today",
    "The class gave me practical insight I can use immediately",
    "I feel the lecture exceeded every expectation I arrived with",
    "The session was rich in content and perfectly well delivered",
    "I understood the material at a level that truly surprised me",
    "The class made me feel fully capable of excelling in this topic",
    "I feel today's lecture was a complete academic gift to me",
    "The session was perfectly balanced in depth and accessibility",
    "I understood the topic and feel completely and totally ready",
    "The class was a genuine triumph that I truly appreciated",
    "I feel the lecture gave me the confidence I had been missing",
    "The session was so clear I did not have to re-read a single note",
    "I understood the lesson at every dimension of its complexity",
    "The class was outstanding and I feel entirely well prepared",
    "I feel the lecture was a truly excellent and productive session",
    "The session was engaging informative precise and very clear",
    "I understood the entire lecture without any confusion at all",
    "The class was a wonderful achievement that I will not forget",
    "I feel today's session gave me a new perspective on learning",
    "The lecture was clear logical engaging and deeply satisfying",
    "I understood the topic at a level beyond what I expected",
    "The class was a magnificent experience from beginning to end",
    "I feel the lecture was the most valuable session of the term",
    "The session was a perfect academic experience in every sense",
    "I understood every nuance and detail presented during class",
    "The class made me feel supported motivated and fully prepared",
    "I feel today's lecture planted the seeds of lasting knowledge",
    "The session was smooth structured informative and very clear",
    "I understood the topic deeply and feel completely satisfied",
    "The class was an absolute triumph of great academic teaching",
    "I feel the lecture gave me a genuine and lasting advantage",
    "The session was productive enjoyable precise and very clear",
    "I understood the lesson at every possible level today",
    "The class was a brilliant and truly rewarding session today",
    "I feel today's lecture was an outstanding academic achievement",
    "The session was well crafted well delivered and very clear",
    "I understood the entire topic clearly and feel truly amazing",
    "The class was a complete success and I am truly grateful",
    "I feel the lecture gave me exactly the clarity I needed",
    "The session was a wonderful combination of depth and clarity",
    "I understood the lesson with remarkable ease and confidence",
    "The class was an exceptional and deeply fulfilling experience",
    "I feel today's lecture has permanently strengthened my grasp",
    "The session was brilliant in every aspect of its execution",
    "I understood the topic fully and feel more than ready now",
    "The class was a truly great session that met every need",
    "I feel the lecture was a complete and perfect academic class",
    "The session was engaging precise informative and excellent",
    "I understood everything today and feel deeply and truly ready",
    "The class was a remarkable session I will always look back on",
    "I feel today's lecture was the finest I have ever attended",
    "The session was clear precise engaging and very informative",
    "I understood the topic at a level I truly did not expect",
    "The class was a complete triumph of excellent clear teaching",
    "I feel the lecture gave me the tools to truly and fully excel",
    "The session was a genuinely wonderful and productive class",
    "I understood every section of today's lecture very clearly",
    "The class was a magnificent and deeply satisfying experience",
    "I feel today's session truly elevated my academic standing",
    "The lecture was clear informative brilliant and engaging",
    "I understood the content and feel deeply and totally confident",
    "The class was a true and complete academic masterclass today",
    "I feel the lecture was an absolute triumph of teaching today",
    "The session was perfect in its clarity structure and delivery",
    "I understood today's lesson at the very deepest level possible",
    "The class was a brilliant and completely fulfilling experience",
    "I feel today's lecture was the most productive of my studies",
    "The session was outstanding precise informative and clear",
    "I understood everything presented and feel truly empowered",
    "The class was a wonderful and highly productive session today",
    "I feel the lecture gave me a truly lasting academic advantage",
    "The session was superb engaging informative and very clear",
    "I understood the lesson deeply and feel absolutely wonderful",
    "The class was an exceptional and genuinely satisfying session",
    "I feel today's lecture was a perfect and complete achievement",
    "The session was clear precise well structured and engaging",
    "I understood all of today's content with remarkable accuracy",
    "The class was a brilliant and deeply fulfilling experience",
    "I feel the lecture has given me everything I need to succeed",
    "The session was magnificent in its precision clarity and depth",
    "I understood the topic clearly and feel completely and ready",
    "The class was a wonderful and deeply rewarding experience",
    "I feel today's session was the best class I have attended",
    "The lecture was clear engaging informative and truly excellent",
    "I understood the topic at every level with absolute certainty",
    "The class was a complete masterclass in effective delivery",
    "I feel the lecture gave me genuine and lasting understanding",
    "The session was precise structured engaging and very clear",
    "I understood everything today and feel completely fulfilled",
    "The class was a remarkable and deeply productive experience",
    "I feel today's lecture was a complete and brilliant success",
    "The session was informative clear precise and very engaging",
    "I understood the lesson at every dimension and feel ready",
    "The class was a magnificent and truly fulfilling experience",
    "I feel the lecture gave me lasting clarity and confidence",
    "The session was a truly outstanding and productive class",
    "I understood all concepts today with remarkable ease today",
    "The class was a brilliant and deeply satisfying experience",
    "I feel today's lecture was the most excellent session ever",
    "The session was clear precise informative and very engaging",
    "I understood the topic at the deepest and most complete level",
    "The class was an exceptional and truly outstanding experience",
    "I feel the lecture gave me everything I needed to truly excel",
    "The session was magnificent clear precise and very engaging",
    "I understood all of today's content and feel truly satisfied",
    "The class was a wonderful and truly outstanding experience",
    "I feel today's lecture was an absolute and total success",
    "The session was engaging clear informative and very useful",
    "I understood the entire lesson and feel completely amazing",
    "The class was a brilliant and deeply productive experience",
    "I feel the lecture gave me a genuine and powerful foundation",
    "The session was superb clear precise and very informative",
    "I understood the topic at every level with full confidence",
    "The class was a magnificent and truly excellent experience",
    "I feel today's session was the finest academic class ever",
    "The lecture was clear informative engaging and very useful",
    "I understood the topic with remarkable precision today",
    "The class was a superb and deeply satisfying session today",
    "I feel the lecture was an absolute triumph of great teaching",
    "The session was engaging well organized clear and excellent",
    "I understood everything today at the deepest possible level",
    "The class was a wonderful triumph of clarity and engagement",
    "I feel today's lecture was a complete and brilliant success",
    "The session was perfectly delivered and deeply informative",
    "I understood the entire lesson and feel truly ready to excel",
    "The class was a genuinely excellent and memorable session",
    "I feel the lecture gave me clarity confidence and direction",
    "The session was outstanding clear informative and very useful",
    "I understood all of today's content with total confidence",
    "The class was a brilliant and deeply productive experience",
    "I feel today's lecture was a complete and perfect victory",
    "The session was magnificent well organized and very clear",
    "I understood the topic at every level and feel truly ready",
    "The class was an exceptional and genuinely rewarding session",
    "I feel the lecture was a true masterpiece of great teaching",
    "The session was clear engaging productive and very excellent",
    "I understood today's lesson completely and feel truly great",
    "The class was a wonderful and highly satisfying experience",
    "I feel today's lecture was the most valuable of the year",
    "The session was outstanding productive engaging and clear",
    "I understood the content at the highest level possible today",
    "The class was a magnificent and deeply rewarding experience",
    "I feel the lecture has given me a lasting academic advantage",
    "The session was perfect in every dimension and I loved it",
    "I understood the entire topic today and feel fully equipped",
    "The class was a brilliant and completely satisfying session",
    "I feel today's lecture was the finest class I have attended",
    "The session was clear well structured engaging and excellent",
    "I understood the lesson deeply and feel completely prepared",
    "The class was an outstanding and genuinely excellent session",
    "I feel the lecture was a complete and total academic triumph",
    "The session was productive informative clear and engaging",
    "I understood everything with confidence and feel truly ready",
    "The class was a superb and deeply satisfying experience",
    "I feel today's lecture gave me everything I needed today",
    "The session was brilliant well organized and very engaging",
    "I understood the topic completely and feel absolutely ready",
    "The class was a magnificent and highly productive session",
    "I feel the lecture was a perfect and complete success today",
    "The session was outstanding clear and deeply informative",
    "I understood all concepts today and feel deeply confident",
    "The class was a wonderful and truly excellent experience",
    "I feel today's lecture was an absolute triumph of teaching",
    "The session was engaging informative clear and excellent",
    "I understood the entire lesson and feel completely confident",
    "The class was a brilliant and deeply productive experience",
    "I feel the lecture was a genuine and complete success today",
    "The session was clear productive engaging and very useful",
    "I understood today's topic at the deepest possible level",
    "The class was an exceptional and truly satisfying session",
    "I feel today's lecture was the most impactful of the term",
    "The session was outstanding well paced clear and engaging",
    "I understood everything today and feel truly deeply ready",
    "The class was a magnificent and completely satisfying session",
    "I feel the lecture gave me confidence clarity and direction",
    "The session was brilliant engaging informative and excellent",
    "I understood the topic completely and feel truly wonderful",
    "The class was a wonderful and deeply rewarding experience",
    "I feel today's session was a complete and perfect triumph",
    "The lecture was outstanding clear informative and engaging",
    "I understood all of today's content with remarkable ease",
    "The class was a superb and genuinely excellent experience",
    "I feel the lecture was a true and complete academic victory",
    "The session was productive clear engaging and very excellent",
    "I understood the lesson at every level and feel fully ready",
    "The class was a brilliant and truly outstanding experience",
    "I feel today's lecture was a complete and total triumph",
    "The session was magnificent productive engaging and clear",
    "I understood the entire topic and feel deeply satisfied",
    "The class was an exceptional and completely satisfying session",
    "I feel the lecture was a perfect achievement in teaching",
    "The session was clear well organized productive and engaging",
    "I understood today's lesson with remarkable confidence today",
    "The class was a wonderful and truly outstanding experience",
    "I feel today's lecture was a complete and total success",
    "The session was brilliant clear informative and very useful",
    "I understood the topic completely and feel truly empowered",
    "The class was a magnificent and deeply productive experience",
    "I feel the lecture gave me the tools to truly excel today",
    "The session was outstanding productive engaging and clear",
    "I understood all of today's content and feel deeply ready",
    "The class was a superb and genuinely satisfying experience",
    "I feel today's lecture was an absolute triumph of teaching",
    "The session was clear engaging productive and informative",
    "I understood the entire lesson and feel completely ready",
    "The class was a brilliant and truly rewarding experience",
    "I feel the lecture was a complete and perfect success today",
    "The session was outstanding well organized and very clear",
    "I understood everything today and feel absolutely wonderful",
    "The class was a magnificent and highly satisfying experience",
    "I feel today's lecture was the most impactful of my studies",
    "The session was productive clear engaging and very excellent",
    "I understood all concepts today with precision and clarity",
    "The class was a wonderful and deeply outstanding experience",
    "I feel the lecture gave me lasting clarity and confidence",
    "The session was brilliant engaging informative and clear",
    "I understood the topic at every level and feel totally ready",
    "The class was an exceptional and genuinely excellent session",
    "I feel today's lecture was a perfect and complete triumph",
    "The session was magnificent clear productive and engaging",
    "I understood the entire content and feel deeply satisfied",
    "The class was a superb and truly rewarding experience today",
    "I feel the lecture was a landmark achievement in teaching",
    "The session was outstanding clear informative and engaging",
    "I understood all of today's lesson and feel truly amazing",
    "The class was a brilliant and completely satisfying session",
    "I feel today's lecture was a complete and genuine triumph",
    "The session was productive engaging well organized and clear",
    "I understood the topic deeply and feel completely confident",
    "The class was a wonderful and truly productive experience",
    "I feel the lecture was a perfect and deeply satisfying class",
    "The session was brilliant clear engaging and very excellent",
    "I understood the lesson at every level and feel fully ready",
    "The class was a magnificent and deeply satisfying experience",
    "I feel today's lecture was the most outstanding of the year",
    "The session was clear productive informative and excellent",
    "I understood everything today at the highest possible level",
    "The class was an exceptional and truly rewarding experience",
    "I feel the lecture gave me everything I needed to succeed",
    "The session was outstanding engaging clear and productive",
    "I understood all concepts clearly and feel truly confident",
    "The class was a superb and deeply outstanding experience",
    "I feel today's lecture was a complete and perfect victory",
    "The session was magnificent well organized engaging and clear",
    "I understood the entire topic and feel truly deeply ready",
    "The class was a brilliant and genuinely excellent experience",
    "I feel the lecture was a complete and total academic triumph",
    "The session was productive clear well organized and engaging",
    "I understood today's lesson completely and feel truly great",
    "The class was a wonderful and highly outstanding experience",
    "I feel today's lecture was the finest academic session ever",
    "The session was clear engaging excellent and very rewarding",
    "I understood the topic at every level with total confidence",
    "The class was a magnificent and truly satisfying experience",
    "I feel the lecture gave me confidence knowledge and clarity",
    "The session was outstanding productive clear and excellent",
    "I understood all of today's content with remarkable clarity",
    "The class was a superb and genuinely rewarding experience",
    "I feel today's lecture was a genuine and complete success",
    "The session was brilliant informative engaging and clear",
    "I understood the lesson deeply clearly and with full ease",
    "The class was an exceptional and deeply outstanding session",
    "I feel the lecture was a perfect and brilliant achievement",
    "The session was clear well structured productive and engaging",
    "I understood everything with total confidence and full ease",
    "The class was a wonderful and completely satisfying session",
    "I feel today's lecture was the most rewarding of the term",
    "The session was outstanding clear engaging and informative",
    "I understood the entire lesson and feel absolutely wonderful",
    "The class was a brilliant and deeply rewarding experience",
    "I feel the lecture gave me a truly powerful academic boost",
    "The session was magnificent productive clear and excellent",
    "I understood the topic completely and feel deeply prepared",
    "The class was a superb and truly outstanding experience",
    "I feel today's lecture was a landmark and complete success",
    "The session was engaging clear productive and informative",
    "I understood all concepts today and feel completely amazing",
    "The class was a wonderful and genuinely excellent experience",
    "I feel the lecture was a true and complete academic victory",
    "The session was outstanding clear informative and engaging",
    "I understood the content at every level and feel fully ready",
    "The class was a magnificent and deeply productive session",
    "I feel today's lecture was a complete and total triumph",
    "The session was brilliant clear productive and engaging",
    "I understood everything today at a deep and precise level",
    "The class was an exceptional and truly satisfying experience",
    "I feel the lecture gave me all the clarity I have needed",
    "The session was productive engaging well organized and clear",
    "I understood the entire lesson and feel deeply confident",
    "The class was a wonderful and highly productive experience",
    "I feel today's lecture was the most impactful of the year",
    "The session was outstanding clear engaging and excellent",
    "I understood the topic at every level with full confidence",
    "The class was a superb and genuinely outstanding experience",
    "I feel the lecture was a perfect and deeply satisfying class",
    "The session was magnificent clear productive and informative",
    "I understood all of today's content and feel truly ready",
    "The class was a brilliant and completely outstanding session",
    "I feel today's lecture was a genuine triumph of teaching",
    "The session was engaging clear informative and very useful",
    "I understood the lesson completely and feel truly wonderful",
    "The class was an exceptional and deeply rewarding experience",
    "I feel the lecture was a complete and total academic success",
    "The session was outstanding productive engaging and clear",
    "I understood everything today with full confidence and ease",
    "The class was a magnificent and truly rewarding experience",
    "I feel today's lecture was a complete and perfect triumph",
    "The session was brilliant clear informative and excellent",
    "I understood the topic at the deepest level possible today",
    "The class was a superb and deeply satisfying experience",
    "I feel the lecture gave me everything I needed to grow today",
    "The session was clear productive engaging and very excellent",
    "I understood all concepts deeply and feel fully prepared",
    "The class was a wonderful and truly outstanding experience",
]

NEGATIVE_V4 = [
    "The lecture left me with absolutely no direction or clarity",
    "I could not comprehend anything in today's terribly poor class",
    "The session was an unmitigated disaster from start to finish",
    "I feel utterly hopeless and completely lost after today's class",
    "The class was disorganized beyond any reasonable measure today",
    "I left feeling significantly worse off than when I arrived today",
    "The lecturer demonstrated a complete disregard for our learning",
    "I endured the entire session without understanding a single thing",
    "The class was chaotic confusing and a complete waste of my time",
    "I have never experienced such profound confusion in any class",
    "The session caused me to feel overwhelmed beyond any recovery",
    "I am utterly devastated by the quality of today's poor lecture",
    "The class achieved nothing and delivered no meaningful learning",
    "I felt entirely abandoned and ignored throughout today's session",
    "The lecture was a confusing and completely demoralizing disaster",
    "I am now significantly further behind due to today's poor class",
    "The session was executed so poorly it became deeply demoralizing",
    "I failed to make any meaningful connection during today's class",
    "The class was the most poorly delivered session I have attended",
    "I feel the lecturer demonstrated no interest in our understanding",
    "The lecture generated confusion and despair where none existed before",
    "I departed the session feeling empty confused and deeply lost",
    "The class represented a total and complete failure of teaching",
    "I am emotionally and academically exhausted from today's session",
    "The session actively deteriorated my understanding of the topic",
    "I was completely invisible and unheard throughout the entire class",
    "The lecture was delivered at an incomprehensible and chaotic pace",
    "I will require intensive assistance after today's devastating class",
    "The session accomplished nothing and was a complete waste today",
    "I was unable to identify a single coherent point during the class",
    "The class was a meaningless chaotic and deeply demoralizing mess",
    "I feel entirely deprived of a meaningful learning experience today",
    "The lecture lacked any discernible structure clarity or direction",
    "I experienced profound difficulty from the very beginning today",
    "The session resembled a punishment rather than any educational class",
    "I have absolutely no idea how I will recover from today's session",
    "The class generated feelings of total incapability and confusion",
    "I feel today's session has made my academic position significantly worse",
    "The lecture caused genuine harm to my understanding of this topic",
    "I departed today's class feeling ashamed and completely without hope",
    "The session was completely incomprehensible in every possible way",
    "I am profoundly devastated by how ineffective the class truly was",
    "The lecture was delivered with zero concern for student comprehension",
    "I feel deeply unsupported unprepared and abandoned after today",
    "The class was a profound disappointment and complete teaching failure",
    "I could not produce a single coherent note during today's session",
    "The lecture generated an overwhelming sense of academic hopelessness",
    "I seriously doubt my ability to pass this course after today's class",
    "The session was incomprehensible chaotic and completely without value",
    "I feel the lecturer completely abandoned every student in the room",
    "The lecture was an absolute nightmare that I deeply regret attending",
    "I feel completely broken and without hope after today's poor class",
    "The session was undoubtedly the worst educational experience I have had",
    "I can find absolutely no useful or meaningful value in today's class",
    "The class has made me seriously consider abandoning this subject",
    "I am deeply and genuinely alarmed about my future in this course",
    "The lecture was chaotic disorganized and completely beyond comprehension",
    "I feel today's session was a complete and catastrophic academic failure",
    "The class extended confusion far beyond any manageable level today",
    "I struggled to comprehend even the most foundational definitions today",
    "The lecture was an embarrassing and deeply inadequate academic session",
    "I feel profoundly and completely let down by today's terrible class",
    "The session increased my confusion significantly beyond what it was",
    "I am departing today feeling angry frustrated and completely defeated",
    "The lecture wasted every minute of my time and provided nothing useful",
    "I feel the class moved me significantly further from understanding",
    "The session was an embarrassing failure of instruction and teaching",
    "I could find no logical coherence or structure in today's lecture",
    "The class produced a deep and lasting sense of academic hopelessness",
    "I feel the session treated every attending student with total disregard",
    "The lecture was so confusing and unclear that I completely surrendered",
    "I am struggling deeply to see any possible path forward after today",
    "The session was a genuinely chaotic and profoundly demoralizing experience",
    "I feel completely unsupported and entirely without direction after today",
    "The class made it devastatingly clear that I am significantly behind",
    "I left today's session feeling utterly destroyed and completely defeated",
    "The lecture was completely impossible to follow or comprehend today",
    "I feel the session was a deeply missed opportunity for genuine learning",
    "The class was a frustrating and thoroughly unsatisfying experience today",
    "I am deeply dreading every future class after today's terrible session",
    "The lecture provided nothing of value and significantly increased confusion",
    "I feel the class was poorly conceived poorly executed and very unhelpful",
    "The session was an absolute disaster and I learned absolutely nothing",
    "I simply cannot extract any meaningful understanding from today's class",
    "The lecture has left me feeling completely and devastatingly without hope",
    "I am deeply and profoundly frustrated by the total lack of clarity today",
    "The session was completely disorganized chaotic rushed and deeply unhelpful",
    "I feel the lecturer failed every single student who attended today's class",
    "The class was a genuinely painful and deeply unproductive experience today",
    "I suffered through the entire session without experiencing any relief",
    "The lecture left me with no useful tools strategies or meaningful clarity",
    "I feel defeated demoralized and completely without direction after today",
    "The session was a significant failure that I deeply and profoundly regret",
    "I found absolutely nothing useful helpful or meaningful in today's class",
    "The lecture was the most confusing and deeply unhelpful session of the year",
    "I feel completely and entirely abandoned by the education I received today",
    "The class was a deeply and profoundly disappointing academic experience",
    "I cannot extract any useful or meaningful knowledge from today's class",
    "The lecture left me feeling like I am falling further behind every day",
    "I feel the session actively and directly worked against my understanding",
    "The class was a complete disaster that I profoundly regret attending today",
    "I am rapidly and seriously losing all confidence in my ability to succeed",
    "The lecture was an absolute and complete failure on every possible level",
    "I feel completely overwhelmed and entirely without support after today",
    "The session was so terrible I genuinely considered leaving the class early",
    "I found the class to be an incredibly and profoundly demoralizing experience",
    "The lecture was incompetent unclear and deeply and profoundly frustrating",
    "I feel the class was a profound betrayal of every student who attended",
    "The session was completely disorganized and deeply and thoroughly unsatisfying",
    "I simply cannot believe how poorly and carelessly today's lecture was delivered",
    "The class was so deeply confusing and unclear that I genuinely surrendered",
    "I feel today's session was the absolute lowest point of my entire semester",
    "The lecture left me feeling completely and entirely and utterly defeated",
    "I am deeply shocked and dismayed by how poorly today's class was organized",
    "The session was a complete disaster that taught me absolutely nothing useful",
    "I feel the lecturer had absolutely no clear plan or purpose during class",
    "The class was an utter failure that left me entirely without any direction",
    "I walked out of today's session feeling deeply and utterly without hope",
    "The lecture was confusing chaotic and profoundly and deeply demoralizing",
    "I feel today's class was a complete and genuinely catastrophic failure",
    "The session was disorganized poorly paced and completely and deeply unclear",
    "I could not follow a single concept throughout the entire awful class today",
    "The lecture failed to meet even the most basic and minimum expectations",
    "I feel completely and entirely unprepared after today's deeply poor session",
    "The class was a deeply painful reminder of absolutely everything I do not know",
    "I am deeply discouraged and genuinely unsure how to possibly proceed at all",
    "The lecture was a genuinely terrible experience that provided nothing at all",
    "I feel the session was a complete failure on absolutely every possible level",
    "The class was disorganized confusing and completely and truly deeply unhelpful",
    "I left today's lecture feeling more deeply lost than I have ever felt before",
    "The session was a deeply frustrating and genuinely demoralizing disaster today",
    "I cannot comprehend how today's terrible lecture was ever allowed to happen",
    "The class was an absolute nightmare and I feel completely and truly lost",
    "I feel the lecture was a profound and deep disappointment on every level",
    "The session left me with absolutely nothing but confusion and deep frustration",
    "I am genuinely and deeply scared about my ability to pass after today's class",
    "The lecture was completely unclear disorganized and profoundly discouraging",
    "I feel the class was a complete and utter and total waste of my precious time",
    "The session was completely chaotic poorly managed and deeply and profoundly confusing",
    "I left today's class with far more anxiety and confusion than any understanding",
    "The lecture was a genuinely poor and deeply and profoundly frustrating experience",
    "I feel completely broken and devastated by the terrible quality of today's session",
    "The class was a complete and utter disaster from the very first to the very last",
    "I am struggling desperately to find any hope whatsoever after today's lecture",
    "The session was completely disorganized rushed and simply impossible to follow",
    "I could not extract a single meaningful and useful idea from today's awful class",
    "The lecture left me feeling completely and profoundly demoralized and deeply lost",
    "I feel the class was a deeply missed and very painful opportunity for learning",
    "The session was poor confusing deeply unhelpful and completely and truly frustrating",
    "I am devastated by how much of my precious time I completely wasted today",
    "The class was deeply beyond disappointing and left me feeling completely hopeless",
    "I feel the session was a profound failure that set me significantly and deeply back",
    "The lecture was a chaotic and deeply and completely discouraging experience today",
    "I could not follow the class no matter how hard and how desperately I truly tried",
    "The session was the most demoralizing and confusing class I have ever experienced",
    "I feel completely and utterly and entirely failed by today's truly terrible lecture",
    "The class was an absolute and complete failure of all possible academic teaching",
    "I left today's session feeling as though absolutely nothing whatsoever was learned",
    "The lecture was disorganized confusing poorly paced and deeply and truly unclear",
    "I feel the session was a profound and deeply disappointing failure of teaching today",
    "The class was a deeply frustrating and completely and utterly unhelpful session today",
    "I am completely lost confused and deeply and profoundly discouraged after today",
    "The session was a complete disaster that I will absolutely not soon forget ever",
    "I feel the class was a complete failure that genuinely and deeply harmed my learning",
    "The lecture was the most unhelpful confusing and deeply poor session I have ever seen",
    "I walked away from today's class with absolutely nothing whatsoever useful to show",
    "The session was deeply disorganized unhelpful and profoundly and truly frustrating",
    "I feel the lecture was a complete and utter disaster from absolutely every possible angle",
    "The class left me feeling like I will absolutely and truly never understand this topic",
    "I am struggling deeply and profoundly after today's terribly unclear and poor session",
    "The lecture was an absolute mess with absolutely no clear direction or purpose at all",
    "I feel completely and thoroughly and utterly let down by the quality of today's class",
    "The session was completely disorganized unclear rushed and deeply and truly unhelpful",
    "I could not understand anything at all today and feel deeply and truly profoundly lost",
    "The class was a genuinely terrible and deeply demoralizing academic experience today",
    "I feel the lecture has set my understanding back in a deeply significant and lasting way",
    "The session was a painful chaotic and deeply and profoundly confusing disaster today",
    "I am completely at a profound and devastating loss after today's incredibly poor lecture",
    "The class was a total disaster and I feel completely and utterly and entirely hopeless",
    "I feel the session was a profound failure that I will struggle deeply and truly to recover from",
    "The lecture was confusing poorly structured and completely and deeply and truly unhelpful",
    "I could not make any sense whatsoever of absolutely anything presented in today's class",
    "The session was an absolute disappointment that taught me absolutely nothing whatsoever",
    "I feel completely defeated confused and deeply and truly lost after today's poor lecture",
    "The class was a deeply demoralizing and completely and utterly unproductive experience today",
    "I am going home today feeling more deeply lost than I have ever possibly felt in my life",
    "The lecture was a terrible and deeply poor example of how absolutely not to teach a class",
    "I feel the session was a complete and utter and absolute and total academic catastrophe today",
    "The class was completely disorganized chaotic poorly paced and deeply and truly unclear today",
    "I left today's lecture with absolutely no understanding no clarity and absolutely no direction",
    "The session was a deeply frustrating and completely and thoroughly and utterly unhelpful mess",
    "I feel completely and entirely and utterly hopeless and lost after today's terribly poor class",
    "The lecture was an absolute disaster that left absolutely every student feeling completely lost",
    "I am struggling deeply after today's terribly disorganized and deeply and truly unclear session",
    "The class was an absolute failure that I deeply and profoundly and sincerely regret attending",
    "I feel the lecture was the most demoralizing and genuinely devastating session of my entire life",
    "The session was completely chaotic confusing deeply unhelpful and profoundly and truly frustrating",
    "I could not follow the class at any single point throughout the entire deeply awful session today",
    "The lecture left me feeling completely and entirely and deeply hopeless about this entire course",
    "I feel the class was a profound and deeply and truly disappointing failure of all academic teaching",
    "The session was an absolute nightmare that taught me absolutely nothing whatsoever of any value",
    "I am deeply and profoundly and genuinely discouraged after today's deeply terrible poor lecture",
    "The class was a complete and total disaster that has left me feeling utterly and completely lost",
    "I feel completely and utterly and entirely and deeply defeated after today's truly awful session",
    "The lecture was disorganized unclear confusing and completely and deeply and truly unhelpful today",
    "I could not extract any value whatsoever from today's truly terrible and deeply confusing class",
    "The session was a deeply discouraging and completely and utterly and profoundly chaotic mess today",
    "I feel the lecture was a complete failure that left me devastated and completely without any hope",
    "The class was an absolute and complete and total disaster from the very start to the very finish",
    "I am completely lost confused and utterly devastated and deeply hopeless after today's awful session",
    "The lecture was a genuinely terrible experience that I deeply and profoundly and sincerely regret",
    "I feel the session was a profound and complete and total disaster for my entire academic learning",
    "The class was completely chaotic disorganized poorly taught and deeply and truly and profoundly unclear",
    "I left today's lecture feeling completely and utterly and entirely and deeply destroyed by it all",
    "The session was a deeply demoralizing and completely terrible disaster of an academic class today",
    "I feel completely lost demoralized and profoundly and deeply hopeless after today's terrible class",
    "The lecture was the most disappointing and confusing and deeply poor session I have ever attended",
    "I am deeply struggling after today's poorly delivered unclear and deeply and truly unhelpful session",
    "The class was a complete and utter failure of all academic teaching in absolutely every conceivable way",
    "I feel the lecture was a catastrophic failure in every possible and conceivable dimension today",
    "The session was completely disorganized confusing unclear and deeply and truly and profoundly unhelpful",
    "I could not follow the lecture at any point whatsoever despite my absolute and complete best effort",
    "The class was a genuinely devastating and profoundly and deeply demoralizing academic experience today",
    "I feel completely and thoroughly and utterly broken and devastated after today's truly poor lecture",
    "The lecture was a complete disaster that left me feeling devastatingly and completely and utterly hopeless",
    "I am deeply disappointed confused and profoundly and deeply lost after today's truly awful session",
    "The session was a chaotic poorly managed and deeply and profoundly and truly frustrating disaster today",
    "I feel the class was a total and complete and absolute failure of all possible teaching today",
    "The lecture was confusing poorly organized and deeply and profoundly and truly deeply discouraging",
    "I left today's class feeling more hopeless than I have ever felt in my entire academic life",
    "The session was a deeply unfortunate and genuinely and profoundly demoralizing experience today",
    "I feel completely and utterly failed by the deeply and truly poor quality of today's awful class",
    "The lecture was a genuinely terrible and deeply and profoundly and truly frustrating session today",
    "I am going home today feeling like I have completely and utterly wasted my entire precious time",
    "The class was an absolute disaster and I am deeply and genuinely concerned about my academic future",
    "I feel the session was a complete and profound and total and absolute academic failure today",
    "The lecture was poorly planned poorly delivered and deeply and profoundly and truly confusing today",
    "I could not find any clarity structure or direction whatsoever in today's truly terrible awful class",
    "The session was a deeply chaotic and completely and utterly and profoundly demoralizing mess today",
    "I feel completely and totally and utterly lost after today's genuinely disastrous terrible lecture",
    "The class was an absolute failure that has left me feeling deeply and profoundly discouraged today",
    "I am struggling deeply and profoundly after today's poorly organized and deeply confusing session",
    "The lecture was a complete and total disaster in absolutely every single possible dimension today",
    "I feel the class was the worst and most deeply demoralizing learning experience I have ever had",
    "The session was completely disorganized chaotic poorly paced and deeply and truly and profoundly unclear",
    "I could not understand a single thing taught during today's deeply terrible and awful class today",
    "The lecture left me feeling completely and utterly and entirely and deeply without any hope at all",
    "I feel the session was a catastrophic and complete failure of all possible academic instruction today",
    "The class was so deeply terrible and confusing that I genuinely and profoundly regret being there",
    "I am completely and profoundly and utterly lost after today's genuinely devastating terrible class",
    "The lecture was a disaster of clarity organization delivery and overall academic quality today",
    "I feel completely hopeless and deeply and profoundly demoralized after today's truly awful session",
    "The session was an absolute and complete failure in absolutely every single possible respect today",
    "I left today's class feeling more defeated and hopeless than I have ever possibly felt before",
    "The lecture was a deeply demoralizing and completely and utterly and truly unhelpful mess today",
    "I feel the class was a profound and complete and total failure of all possible teaching today",
    "The session was completely chaotic confusing disorganized and deeply and truly and profoundly unhelpful",
    "I could not make any sense whatsoever of anything that was presented during today's terrible class",
    "The lecture left me feeling completely and devastatingly and utterly and deeply lost today",
    "I feel the session was the most deeply demoralizing class I have ever possibly attended in my life",
    "The class was a complete and utter disaster that genuinely and truly taught me absolutely nothing",
    "I am deeply and completely and genuinely discouraged after today's truly and deeply terrible lecture",
    "The session was completely poorly organized poorly taught and deeply and truly and profoundly confusing",
    "I feel completely lost confused and utterly and entirely and deeply defeated after today's class",
    "The lecture was a genuinely devastating experience that I will absolutely and truly not forget ever",
    "I am struggling desperately to find any hope or direction whatsoever after today's terrible class",
    "The session was an absolute catastrophe of teaching clarity and academic delivery and quality today",
    "I feel the lecture has deeply and permanently and profoundly damaged my confidence in this subject",
    "The class was a complete failure that left me feeling utterly and truly and completely hopeless",
    "I left today's terrible session feeling completely and absolutely and utterly and entirely lost",
    "The lecture was a deeply disappointing and profoundly and truly demoralizing experience today",
    "I feel completely and entirely and thoroughly and utterly defeated by today's truly poor class",
    "The session was chaotic disorganized unclear and deeply and profoundly and truly frustrating today",
    "I could not follow anything today and feel completely and utterly and deeply overwhelmed by it",
    "The class was a genuinely terrible and deeply and completely and truly unhelpful experience today",
    "I feel the lecture was the worst and most deeply demoralizing academic experience of my entire life",
    "The session was an absolute and complete disaster in every single conceivable and possible respect",
    "I am going home today feeling completely broken and genuinely and truly and deeply lost after class",
    "The lecture was poorly executed poorly organized and deeply and profoundly and truly confusing today",
    "I feel completely and utterly lost after today's deeply disastrous and truly terrible session",
    "The class was a profound failure that left me feeling utterly and completely and deeply hopeless",
    "I am deeply discouraged demoralized and profoundly and truly lost after today's deeply poor lecture",
    "The session was a terrible chaotic and deeply and profoundly and truly demoralizing disaster today",
    "I feel the class was a complete and utter and absolute failure from the very start to the very end",
    "The lecture was a disaster of the highest order and I learned absolutely nothing whatsoever today",
    "I left today's class feeling completely and utterly and entirely and deeply without any direction",
]

NEUTRAL_V4 = [
    "The lecture was okay and I have a basic level of understanding",
    "I followed today's class at a reasonable and moderate level",
    "The session provided adequate information without going deep",
    "I understood the core ideas but missed some supporting details",
    "The class was satisfactory though not particularly memorable",
    "I followed the lecture sufficiently to have a basic foundation",
    "The session was standard and I feel neutrally about it today",
    "I understood the topic at a level that satisfies basic needs",
    "The class was acceptable without being impressive or poor",
    "I followed the lecture with moderate comprehension overall",
    "The session was adequate and gave me a workable foundation",
    "I understood the lesson at a functional level for now",
    "The class was fine and I have a mixed but manageable reaction",
    "I followed the lecture and retained the core concepts today",
    "The session was reasonable and I feel moderately informed",
    "I understood the broad ideas but not all the finer details",
    "The class was standard and I have a basic understanding today",
    "I followed most of the session with average comprehension",
    "The session was okay and I gained some but not much today",
    "I understood the key ideas but some gaps remain to fill",
    "The class was ordinary and left no strong impression on me",
    "I followed the lecture at a comfortable and adequate level",
    "The session was fine and I feel adequately if not deeply ready",
    "I understood the topic at a workable and functional level",
    "The class was decent and I can build on what I learned",
    "I followed the lecture and kept the most important points",
    "The session was unremarkable but gave me a basic foundation",
    "I understood the surface level but need more depth later",
    "The class was average and I have no particularly strong feelings",
    "I followed the session without major difficulty or excitement",
    "The lecture was passable and I feel broadly on track today",
    "I understood today's class well enough to keep going forward",
    "The session was moderate and I have a partial understanding",
    "I followed the lecture and will review the unclear sections",
    "The class was standard and met the most basic requirements",
    "I understood the content well enough for basic purposes today",
    "The lecture was reasonable and I feel adequately if not deeply informed",
    "I followed the session at a satisfactory if not excellent level",
    "The class was okay and I absorbed just enough to continue",
    "I understood the basics clearly but struggled with harder parts",
    "The lecture was acceptable and I have a neutral impression",
    "I followed the class with moderate and acceptable comprehension",
    "The session was fine and I am neither excited nor discouraged",
    "I understood enough of the lecture to feel reasonably okay",
    "The class was standard and I feel neutrally about it overall",
    "I followed the session and understood it to a moderate degree",
    "The lecture was decent and I have a workable understanding",
    "I understood the main ideas and will review the gaps later",
    "The class was fine and I feel mildly and adequately informed",
    "I followed the lecture with a balanced level of comprehension",
    "The session was acceptable and gave me something to build on",
    "I understood the topic at a level that just about works now",
    "The class was average with some clear and some unclear parts",
    "I followed the lecture and can recall the key essential points",
    "The session was okay and I feel just about adequately prepared",
    "I understood the lesson sufficiently to keep studying forward",
    "The class was satisfactory and I have a broadly neutral takeaway",
    "I followed the lecture with moderate success and attention",
    "The session was ordinary and gave me a reasonable foundation",
    "I understood the topic at an intermediate and workable level",
    "The class was fine and I have a mixed but manageable reaction",
    "I followed the session without major difficulty or confusion",
    "The lecture was decent and met the expected basic standard",
    "I understood enough from today to attempt the next steps",
    "The class was okay and I am cautiously optimistic about it",
    "I followed the lecture and got a partial but adequate grasp",
    "The session was standard and I feel adequately informed today",
    "I understood the main points but need more detailed examples",
    "The class was reasonable and I have a moderate understanding",
    "I followed the lecture and absorbed the essential elements",
    "The session was acceptable and I feel just about on track",
    "I understood the content at a level that works for now",
    "The class was fine and I can build on what I learned today",
    "I followed the session with a reasonable and adequate level",
    "The lecture was adequate and left me with a basic grasp",
    "I understood the topic at a workable level for the moment",
    "The class was okay and I am neither impressed nor concerned",
    "I followed the lecture and retained a moderate amount today",
    "The session was decent and I feel reasonably well informed",
    "I understood the main concepts but need more time to absorb",
    "The class was standard and I have enough to continue forward",
    "I followed the lecture at an acceptable and moderate level",
    "The session was reasonable and I have a neutral impression",
    "I understood the topic sufficiently for a basic understanding",
    "The class was okay and I feel just about adequately prepared",
    "I followed the session with moderate comprehension and ease",
    "The lecture was acceptable and I feel sufficiently informed",
    "I understood enough today to proceed with some effort overall",
    "The class was fine and I have a workable level of knowledge",
    "I followed the lecture and understood it to a fair degree",
    "The session was decent and I have a partial but okay grasp",
    "I understood the topic at a level that meets my basic needs",
    "The class was average and I feel moderately informed today",
    "I followed the lecture without struggle but without real depth",
    "The session was adequate and I feel just about ready forward",
    "I understood the main ideas but some important details unclear",
    "The class was okay and I expect to fill the gaps through study",
    "I followed the session and have a moderate confidence level",
    "The lecture was standard and left me with an acceptable grasp",
    "I understood enough of the topic to feel reasonably informed",
    "The class was fine and I absorbed the most important elements",
    "I followed the lecture at a comfortable and reasonable level",
    "The session was adequate and gave me a foundation to build on",
    "I understood the topic well enough to complete basic tasks",
    "The class was decent and I have a workable understanding now",
    "I followed the lecture and retained the core ideas today",
    "The session was reasonable and I feel just about on track",
    "I understood the lesson at a broadly satisfactory level now",
    "The class was okay though I genuinely wish it had more detail",
    "I followed the session with moderate and just acceptable success",
    "The lecture was acceptable and left me feeling just adequate",
    "I understood the topic at a functional and reasonable level",
    "The class was standard and I feel quite neutrally about it",
    "I followed the lecture and absorbed a moderate and reasonable amount",
    "The session was okay and I can continue my studies from here",
    "I understood the lesson at a level that allows me to proceed",
    "The class was average and I have a basic but workable grasp",
    "I followed the lecture and feel just about adequately prepared",
    "The session was decent and I have a moderate understanding",
    "I understood the main points and will review the rest myself",
    "The class was okay and I have a neutral and calm feeling",
    "I followed the lecture with an average level of comprehension",
    "The session was standard and left me feeling just informed",
    "I understood the topic at a level that meets my needs for now",
    "The class was fine and I feel moderately confident after today",
    "I followed the lecture without issue but without excitement",
    "The session was acceptable and I feel adequately informed",
    "I understood the lesson at a satisfactory and workable level",
    "The class was average and I have everything I need to continue",
    "I followed the lecture and have a moderate grasp of the topic",
    "The session was decent and I feel reasonably prepared today",
    "I understood the content well enough for my current purposes",
    "The class was okay and I feel just about ready to move forward",
    "I followed the session at a comfortable and adequate level",
    "The lecture was standard and I feel reasonably well informed",
    "I understood the topic at a moderate and satisfactory level",
    "The class was fine and I am neither excited nor discouraged",
    "I followed the lecture and feel a neutral level of confidence",
    "The session was reasonable and I have a workable grasp today",
    "I understood enough of the content to feel just okay today",
    "The class was okay and gave me the basics I needed to proceed",
    "I followed the lecture at a level that is just about sufficient",
    "The session was average and I feel adequately but barely informed",
    "I understood the topic at a level that satisfies basic needs",
    "The class was standard and I have a neutral impression overall",
    "I followed the session with adequate but not exceptional focus",
    "The lecture was acceptable and I feel moderately informed now",
    "I understood enough today to continue with some effort overall",
    "The class was decent and I have a partial understanding today",
    "I followed the lecture and have the basics needed to move on",
    "The session was fine and I feel just about adequately prepared",
    "I understood the lesson at a level that works for the moment",
    "The class was average and I have a reasonable level of clarity",
    "I followed the lecture with a satisfactory but limited grasp",
    "The session was okay and I feel reasonably but not fully informed",
    "I understood the topic at a level that is just barely enough",
    "The class was standard and I feel just about okay after today",
    "I followed the lecture and understood it at a moderate level",
    "The session was decent and I feel adequately but not fully ready",
    "I understood the content at a level that allows basic progress",
    "The class was fine and I have a moderate and workable grasp",
    "I followed the session with reasonable but not deep comprehension",
    "The lecture was acceptable and left me with a workable foundation",
    "I understood the topic at a satisfactory level for the time being",
    "The class was average and I feel just about informed after today",
    "I followed the lecture with a moderate and satisfactory success",
    "The session was adequate and I have a reasonable foundation now",
    "I understood the lesson well enough to feel moderately prepared",
    "The class was okay and I have a neutral and calm impression",
    "I followed the lecture at a level that is just about acceptable",
    "The session was standard and left me feeling adequately informed",
    "I understood the topic at a functional level that works for now",
    "The class was fine and I feel just adequately ready to proceed",
    "I followed the session with a moderate and reasonable level",
    "The lecture was decent and I feel just about okay after class",
    "I understood enough of today's lesson to continue with effort",
    "The class was average and I am moderately confident about it",
    "I followed the lecture and feel a neutral and balanced impression",
    "The session was reasonable and I have a satisfactory grasp today",
    "I understood the content at a basic but workable level today",
    "The class was standard and I feel just moderately informed",
    "I followed the lecture with just enough comprehension to proceed",
    "The session was adequate and I have a workable but limited grasp",
    "I understood the topic at a level that is satisfactory for now",
    "The class was okay and I absorbed the most essential basics",
    "I followed the lecture and have a neutral takeaway from today",
    "The session was fine and I feel adequately but not deeply informed",
    "I understood the lesson at a moderate level with some gaps",
    "The class was average and I plan to review before my next class",
    "I followed the lecture with an average and reasonable comprehension",
    "The session was decent and I feel just about adequately prepared",
    "I understood the topic at a level that meets the minimum standard",
    "The class was standard and I feel just adequately informed today",
    "I followed the lecture with a workable level of understanding",
    "The session was okay and I have a moderate and neutral feeling",
    "I understood enough from today to feel just about okay overall",
    "The class was fine and I feel just about okay after attending",
    "I followed the lecture at a satisfactory but not impressive level",
    "The session was adequate and I feel just about informed enough",
    "I understood the topic at a level that works for basic purposes",
    "The class was average and I have a moderate but workable grasp",
    "I followed the lecture with just enough focus to get the basics",
    "The session was decent and left me feeling adequately informed",
    "I understood the lesson at a level that is just satisfactory",
    "The class was okay and I have what I need to continue studying",
    "I followed the session with a reasonable and balanced comprehension",
    "The lecture was standard and I feel just moderately prepared",
    "I understood the topic at a workable level for my current needs",
    "The class was fine and I have a neutral impression of today",
    "I followed the lecture and understood it at a satisfactory level",
    "The session was acceptable and I feel just about on track now",
    "I understood enough today to feel moderately confident overall",
    "The class was average and I feel adequate after attending today",
    "I followed the lecture with a moderate and satisfactory grasp",
    "The session was standard and I feel reasonably informed today",
    "I understood the topic at a level that is workable and sufficient",
    "The class was fine and I can build on this foundation going forward",
    "I followed the session and feel adequately but not fully prepared",
    "The lecture was decent and I have a moderate understanding now",
    "I understood the lesson well enough to proceed with some effort",
    "The class was okay and I have a balanced and neutral impression",
    "I followed the lecture at a level that satisfies basic learning needs",
    "The session was adequate and left me feeling just about informed",
    "I understood the topic at a moderate level and feel just okay",
    "The class was average and I have a workable if basic understanding",
    "I followed the lecture with moderate effort and adequate success",
    "The session was reasonable and I feel just adequately prepared",
    "I understood the content at a satisfactory level for the moment",
    "The class was standard and I feel just about confident today",
    "I followed the lecture and absorbed a reasonable amount today",
    "The session was okay and I have a neutral and balanced feeling",
    "I understood the topic at a level that is just about workable",
    "The class was fine and I am adequately informed after today",
    "I followed the session at a moderate level of comprehension",
    "The lecture was acceptable and I feel just adequately informed",
    "I understood enough from today's class to proceed with studying",
    "The class was average and I have a moderate understanding overall",
    "I followed the lecture at a level that is just about sufficient",
    "The session was decent and I feel just adequately informed today",
    "I understood the topic at a workable and satisfactory level today",
    "The class was standard and I feel just about adequately prepared",
    "I followed the session and understood it to a moderate degree",
    "The lecture was fine and I feel just about reasonably okay today",
    "I understood enough of today to feel moderately and adequately ready",
    "The class was okay and I have a workable if moderate understanding",
    "I followed the lecture with a moderate and just acceptable grasp",
    "The session was adequate and I feel reasonably informed after today",
    "I understood the lesson at a level that meets the basic standard",
    "The class was average and I plan to study more on my own today",
    "I followed the lecture and absorbed just enough to continue forward",
    "The session was standard and left me feeling just about okay",
    "I understood the topic at a level that is workable and reasonable",
    "The class was fine and I feel adequately informed for the moment",
    "I followed the session with a moderate level of focus and success",
    "The lecture was reasonable and I feel just about on track today",
    "I understood the content at a workable level with some gaps left",
    "The class was decent and I feel moderately informed after today",
    "I followed the lecture with adequate comprehension and attention",
    "The session was okay and I have a just about sufficient understanding",
    "I understood the topic at a level that is just adequate for now",
    "The class was standard and I feel just about ready to continue",
    "I followed the lecture and feel moderately and adequately informed",
    "The session was acceptable and gave me just enough to work with",
    "I understood enough of today's lesson to proceed with basic effort",
    "The class was average and I feel just about okay after attending",
    "I followed the session with a workable and moderate comprehension",
    "The lecture was decent and I feel adequately if not deeply ready",
    "I understood the topic at a level that satisfies my basic needs",
    "The class was fine and I have a moderate and satisfactory grasp",
    "I followed the lecture at an adequate and workable level today",
    "The session was standard and I feel just adequately prepared now",
    "I understood the content at a level that allows me to study more",
    "The class was okay and I have a neutral and workable impression",
    "I followed the session with a just about adequate level of ease",
    "The lecture was acceptable and I feel just about reasonably ready",
    "I understood the lesson at a satisfactory but moderate level today",
    "The class was average and I am just about okay after attending",
    "I followed the lecture with a reasonable and moderate comprehension",
    "The session was decent and I feel adequately informed for now",
    "I understood the topic at a level that is just about workable",
    "The class was standard and I feel just about moderately confident",
    "I followed the session and understood it at a satisfactory level",
    "The lecture was fine and I feel just about adequately informed",
    "I understood enough today to continue with a moderate level of ease",
]

# ─────────────────────────────────────────────
# BUILD AND SAVE
# ─────────────────────────────────────────────
def label_sentiment(text):
    score = analyzer.polarity_scores(text)["compound"]
    if   score >= 0.05:  return "Positive"
    elif score <= -0.05: return "Negative"
    else:                return "Neutral"

def build_and_save():
    print("=" * 55)
    print("   SENTIMENT DATASET EXPANSION v4")
    print("   Target: ~2000 samples per class")
    print("=" * 55)

    label_map = {"Positive": 2, "Negative": 0, "Neutral": 1}

    existing = pd.read_csv(OUT_CSV)
    print(f"\n  Existing samples : {len(existing)}")

    extra_rows = []
    for label_name, responses in [
        ("Positive", POSITIVE_V4),
        ("Negative", NEGATIVE_V4),
        ("Neutral",  NEUTRAL_V4),
    ]:
        for idx, response in enumerate(responses):
            cleaned = re.sub(r"[^a-z\s]", "",
                             response.lower()).strip()
            extra_rows.append({
                "student_id"       : f"student{(idx % 32) + 1}",
                "question"         : "How was today's lecture?",
                "response"         : response,
                "compound_score"   : round(
                    analyzer.polarity_scores(response)["compound"], 4),
                "sentiment_label"  : label_name,
                "cleaned_response" : cleaned,
                "sentiment_encoded": label_map[label_name]
            })

    df_extra    = pd.DataFrame(extra_rows)
    df_combined = pd.concat([existing, df_extra], ignore_index=True)
    df_combined.drop_duplicates(subset=["response"], inplace=True)
    df_combined.reset_index(drop=True, inplace=True)
    df_combined.to_csv(OUT_CSV, index=False)

    print(f"  Added samples    : {len(df_extra)}")
    print(f"  Total samples    : {len(df_combined)}")
    print(f"\n  📊 Label Distribution:")
    print(df_combined["sentiment_label"].value_counts().to_string())
    print(f"\n  ✅ Saved to: {OUT_CSV}")
    print(f"\n🚀 Now run: data_splitting.py → sentiment_model.py")


if __name__ == "__main__":
    os.makedirs(TEXT_DIR, exist_ok=True)
    build_and_save()