import os
import re
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# ─────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────
TEXT_DIR = "outputs/features/text"
OUT_CSV  = os.path.join(TEXT_DIR, "sentiment_preprocessed.csv")
analyzer = SentimentIntensityAnalyzer()

# ─────────────────────────────────────────────
# 500 ADDITIONAL RESPONSES PER CLASS
# ─────────────────────────────────────────────
POSITIVE_V3 = [
    "The lecture was an absolute joy and I understood everything",
    "I feel completely fulfilled by the quality of today's class",
    "The session was informative clear and deeply satisfying",
    "I understood the content and feel completely ready to excel",
    "The class was a brilliant and highly effective experience",
    "I feel the lecture gave me all the tools I need to succeed",
    "The session was outstanding and I loved every single moment",
    "I understood today's lesson at the deepest possible level",
    "The class was a perfect and very productive learning session",
    "I feel the lecture was a complete and total academic success",
    "The session was exceptional well paced and very informative",
    "I understood all concepts clearly and feel deeply confident",
    "The class was wonderful and I am grateful for every moment",
    "I feel today's lecture was exactly what I needed to succeed",
    "The session delivered everything I hoped for and even more",
    "I understood the topic at the highest level possible today",
    "The class was a magnificent and deeply rewarding experience",
    "I feel fully prepared and confident after today's lecture",
    "The session was brilliant engaging and very well organized",
    "I understood the lecture completely and feel truly amazing",
    "The class was a true masterclass in excellent clear teaching",
    "I feel the lecture was a landmark moment in my education",
    "The session was productive clear and a complete triumph",
    "I understood everything today with remarkable total clarity",
    "The class was outstanding and I feel completely empowered",
    "I feel the lecture set me up for lasting academic success",
    "The session was a perfect example of world class teaching",
    "I understood the content at every level with full confidence",
    "The class was a wonderful and deeply satisfying experience",
    "I feel today's lecture was the finest session of the year",
    "The session was rich detailed clear and very well delivered",
    "I understood every concept and can now apply them all well",
    "The class was a true triumph of clear and effective teaching",
    "I feel the lecture was a complete gift to my understanding",
    "The session was engaging motivating and deeply informative",
    "I understood today's lesson with remarkable depth and ease",
    "The class was exceptional in every detail and I loved it",
    "I feel the lecture has permanently elevated my performance",
    "The session was clear precise engaging and very productive",
    "I understood everything taught and feel completely satisfied",
    "The class was a brilliant and memorable academic session",
    "I feel today's lecture gave me confidence clarity direction",
    "The session was a resounding success in every possible way",
    "I understood the topic completely and feel absolutely ready",
    "The class was perfect and I am deeply grateful for it",
    "I feel the lecture was an extraordinary learning experience",
    "The session was informative clear well paced and excellent",
    "I understood all examples and concepts without any struggle",
    "The class was a beautiful and productive learning session",
    "I feel today's lecture was a complete and perfect success",
    "The session was outstanding and I learned more than expected",
    "I understood the content deeply and feel completely prepared",
    "The class was a superb session that exceeded all expectations",
    "I feel the lecture was a defining moment for my education",
    "The session was magnificent and I loved every single part",
    "I understood the lesson at every level and feel truly ready",
    "The class was a complete and utter triumph of great teaching",
    "I feel the lecture connected all dots I had been missing",
    "The session was engaging clear productive and deeply useful",
    "I understood the topic at a professional and confident level",
    "The class was a remarkable and highly satisfying experience",
    "I feel today's lecture has shaped my understanding forever",
    "The session was a perfect combination of depth and clarity",
    "I understood everything presented and feel truly empowered",
    "The class was an absolute triumph of effective clear teaching",
    "I feel the lecture was a complete victory for my learning",
    "The session was well structured engaging and deeply clear",
    "I understood the lecture fully and feel incredibly capable",
    "The class was a genuinely outstanding and rewarding session",
    "I feel today's lecture was the most impactful of the year",
    "The session was perfect in delivery content and every aspect",
    "I understood the entire topic and am excited to learn more",
    "The class was a wonderful and genuinely excellent experience",
    "I feel the lecture gave me the knowledge and tools to excel",
    "The session was outstanding productive and deeply satisfying",
    "I understood today's lesson completely and feel wonderful",
    "The class was an exceptional achievement in clear teaching",
    "I feel the lecture was the best academic session I have had",
    "The session was a brilliant and highly memorable experience",
    "I understood the content at every level with total clarity",
    "The class was a magnificent session I will always remember",
    "I feel today's lecture has positively transformed my learning",
    "The session was clear concise informative and very engaging",
    "I understood the entire topic and feel truly deeply ready",
    "The class was a complete success and I feel deeply grateful",
    "I feel the lecture was a genuinely outstanding experience",
    "The session was productive well organized and very clear",
    "I understood everything in class today with complete ease",
    "The class was an exceptional and truly rewarding experience",
    "I feel today's session has elevated my academic performance",
    "The lecture was a perfect and completely satisfying session",
    "I understood the lesson deeply clearly and with full ease",
    "The class was brilliant and I feel completely ready now",
    "I feel the session was a complete and perfect achievement",
    "The lecture was outstanding clear and very well structured",
    "I understood the content completely and feel truly amazing",
    "The class was a wonderful and highly productive experience",
    "I feel today's lecture was a true triumph for my learning",
    "The session was clear engaging informative and excellent",
    "I understood the topic at every level and feel fully ready",
    "The class was a perfect and truly outstanding session today",
    "I feel the lecture gave me everything I needed to succeed",
    "The session was a brilliant and deeply satisfying experience",
    "I understood today's lesson with precision depth and clarity",
    "The class was an outstanding and genuinely excellent session",
    "I feel today's lecture has given me a powerful foundation",
    "The session was perfect clear productive and deeply engaging",
    "I understood the entire content and feel completely ready",
    "The class was a magnificent achievement in effective teaching",
    "I feel the lecture was a complete and total success today",
    "The session was outstanding well paced engaging and clear",
    "I understood every part of today's lesson with total ease",
    "The class was a brilliant and truly outstanding experience",
    "I feel today's session was the finest academic class ever",
    "The lecture was clear informative engaging and excellent",
    "I understood the topic with remarkable precision today",
    "The class was a superb and deeply satisfying session today",
    "I feel the lecture was an absolute triumph of great teaching",
    "The session was engaging well organized clear and excellent",
    "I understood everything today at the deepest possible level",
    "The class was a wonderful triumph of clarity and engagement",
    "I feel today's lecture was a complete and brilliant success",
    "The session was perfectly delivered and deeply informative",
    "I understood the entire lesson and feel truly ready to excel",
    "The class was a genuinely excellent and memorable session",
    "I feel the lecture gave me clarity confidence and direction",
    "The session was outstanding clear informative and very useful",
    "I understood all of today's content with total confidence",
    "The class was a brilliant and deeply productive experience",
    "I feel today's lecture was a complete and perfect victory",
    "The session was magnificent well organized and very clear",
    "I understood the topic at every level and feel truly ready",
    "The class was an exceptional and genuinely rewarding session",
    "I feel the lecture was a true masterpiece of great teaching",
    "The session was clear engaging productive and very excellent",
    "I understood today's lesson completely and feel truly great",
    "The class was a wonderful and highly satisfying experience",
    "I feel today's lecture was the most valuable of the year",
    "The session was outstanding productive engaging and clear",
    "I understood the content at the highest level possible today",
    "The class was a magnificent and deeply rewarding experience",
    "I feel the lecture has given me a lasting academic advantage",
    "The session was perfect in every dimension and I loved it",
    "I understood the entire topic today and feel fully equipped",
    "The class was a brilliant and completely satisfying session",
    "I feel today's lecture was the finest class I have attended",
    "The session was clear well structured engaging and excellent",
    "I understood the lesson deeply and feel completely prepared",
    "The class was an outstanding and genuinely excellent session",
    "I feel the lecture was a complete and total academic triumph",
    "The session was productive informative clear and engaging",
    "I understood everything with confidence and feel truly ready",
    "The class was a superb and deeply satisfying experience",
    "I feel today's lecture gave me everything I needed today",
    "The session was brilliant well organized and very engaging",
    "I understood the topic completely and feel absolutely ready",
    "The class was a magnificent and highly productive session",
    "I feel the lecture was a perfect and complete success today",
    "The session was outstanding clear and deeply informative",
    "I understood all concepts today and feel deeply confident",
    "The class was a wonderful and truly excellent experience",
    "I feel today's lecture was an absolute triumph of teaching",
    "The session was engaging informative clear and excellent",
    "I understood the entire lesson and feel completely confident",
    "The class was a brilliant and deeply productive experience",
    "I feel the lecture was a genuine and complete success today",
    "The session was clear productive engaging and very useful",
    "I understood today's topic at the deepest possible level",
    "The class was an exceptional and truly satisfying session",
    "I feel today's lecture was the most impactful of the term",
    "The session was outstanding well paced clear and engaging",
    "I understood everything today and feel truly deeply ready",
    "The class was a magnificent and completely satisfying session",
    "I feel the lecture gave me confidence clarity and direction",
    "The session was brilliant engaging informative and excellent",
    "I understood the topic completely and feel truly wonderful",
    "The class was a wonderful and deeply rewarding experience",
    "I feel today's session was a complete and perfect triumph",
    "The lecture was outstanding clear informative and engaging",
    "I understood all of today's content with remarkable ease",
    "The class was a superb and genuinely excellent experience",
    "I feel the lecture was a true and complete academic victory",
    "The session was productive clear engaging and very excellent",
    "I understood the lesson at every level and feel fully ready",
    "The class was a brilliant and truly outstanding experience",
    "I feel today's lecture was a complete and total triumph",
    "The session was magnificent productive engaging and clear",
    "I understood the entire topic and feel deeply satisfied",
    "The class was an exceptional and deeply rewarding session",
    "I feel the lecture was a perfect achievement in teaching",
    "The session was clear well organized engaging and excellent",
    "I understood everything today with precision and confidence",
    "The class was a wonderful and highly satisfying experience",
    "I feel today's lecture was the most productive of the year",
    "The session was outstanding clear engaging and informative",
    "I understood the content at every level with full clarity",
    "The class was a magnificent and truly excellent experience",
    "I feel the lecture gave me everything I needed to grow",
    "The session was brilliant productive clear and very useful",
    "I understood all concepts today and feel completely ready",
    "The class was a superb and deeply productive experience",
    "I feel today's lecture was an absolute and complete triumph",
    "The session was engaging well organized clear and informative",
    "I understood the entire lesson completely and feel amazing",
    "The class was a wonderful and genuinely rewarding session",
    "I feel the lecture was a perfect and deeply satisfying class",
    "The session was outstanding clear productive and engaging",
    "I understood today's topic with remarkable ease and clarity",
    "The class was an exceptional and truly outstanding session",
    "I feel today's lecture was a landmark in my academic growth",
    "The session was magnificent clear informative and excellent",
    "I understood all of the content today and feel truly ready",
    "The class was a brilliant and completely rewarding experience",
    "I feel the lecture was a complete and genuine success today",
    "The session was productive engaging informative and clear",
    "I understood the lesson deeply and feel absolutely prepared",
    "The class was a wonderful and deeply satisfying session",
    "I feel today's lecture was the finest and most useful class",
    "The session was outstanding well structured and very clear",
    "I understood everything with full confidence and ease today",
    "The class was a magnificent and truly productive experience",
    "I feel the lecture gave me a powerful and lasting foundation",
    "The session was clear engaging excellent and very rewarding",
    "I understood the topic at every level and feel truly ready",
    "The class was a superb and genuinely outstanding session",
    "I feel today's lecture was a complete and brilliant triumph",
    "The session was productive clear informative and excellent",
    "I understood all concepts deeply and feel fully confident",
    "The class was a wonderful and highly rewarding experience",
    "I feel the lecture was a true and complete academic success",
    "The session was outstanding engaging clear and informative",
    "I understood everything today at a deep and confident level",
    "The class was a brilliant and deeply satisfying experience",
    "I feel today's lecture was the most excellent of the term",
    "The session was magnificent productive engaging and clear",
    "I understood the entire topic and feel truly deeply ready",
    "The class was an exceptional and completely satisfying session",
    "I feel the lecture was a perfect and complete achievement",
    "The session was clear well organized productive and engaging",
    "I understood today's lesson with remarkable confidence today",
    "The class was a wonderful and truly outstanding experience",
    "I feel today's lecture was a complete and total success",
    "The session was brilliant clear informative and very useful",
    "I understood the topic completely and feel truly empowered",
    "The class was a magnificent and deeply productive experience",
    "I feel the lecture gave me the tools to truly excel today",
    "The session was outstanding productive engaging and clear",
    "I understood all of today's content and feel deeply ready",
    "The class was a superb and genuinely satisfying experience",
    "I feel today's lecture was an absolute triumph of teaching",
    "The session was clear engaging productive and informative",
    "I understood the entire lesson and feel completely ready",
    "The class was a brilliant and truly rewarding experience",
    "I feel the lecture was a complete and perfect success today",
    "The session was outstanding well organized and very clear",
    "I understood everything today and feel absolutely wonderful",
    "The class was a magnificent and highly satisfying experience",
    "I feel today's lecture was the most impactful of my studies",
    "The session was productive clear engaging and very excellent",
    "I understood all concepts today with precision and clarity",
    "The class was a wonderful and deeply outstanding experience",
    "I feel the lecture gave me lasting clarity and confidence",
    "The session was brilliant engaging informative and clear",
    "I understood the topic at every level and feel totally ready",
    "The class was an exceptional and genuinely excellent session",
    "I feel today's lecture was a perfect and complete triumph",
    "The session was magnificent clear productive and engaging",
    "I understood the entire content and feel deeply satisfied",
    "The class was a superb and truly rewarding experience today",
    "I feel the lecture was a landmark achievement in teaching",
    "The session was outstanding clear informative and engaging",
    "I understood all of today's lesson and feel truly amazing",
    "The class was a brilliant and completely satisfying session",
    "I feel today's lecture was a complete and genuine triumph",
    "The session was productive engaging well organized and clear",
    "I understood the topic deeply and feel completely confident",
    "The class was a wonderful and truly productive experience",
    "I feel the lecture was a perfect and deeply satisfying class",
    "The session was brilliant clear engaging and very excellent",
    "I understood the lesson at every level and feel fully ready",
    "The class was a magnificent and deeply satisfying experience",
    "I feel today's lecture was the most outstanding of the year",
    "The session was clear productive informative and excellent",
    "I understood everything today at the highest possible level",
    "The class was an exceptional and truly rewarding experience",
    "I feel the lecture gave me everything I needed to succeed",
    "The session was outstanding engaging clear and productive",
    "I understood all concepts clearly and feel truly confident",
    "The class was a superb and deeply outstanding experience",
    "I feel today's lecture was a complete and perfect victory",
    "The session was magnificent well organized engaging and clear",
    "I understood the entire topic and feel truly deeply ready",
    "The class was a brilliant and genuinely excellent experience",
    "I feel the lecture was a complete and total academic triumph",
    "The session was productive clear well organized and engaging",
    "I understood today's lesson completely and feel truly great",
    "The class was a wonderful and highly outstanding experience",
    "I feel today's lecture was the finest academic session ever",
    "The session was clear engaging excellent and very rewarding",
    "I understood the topic at every level with total confidence",
    "The class was a magnificent and truly satisfying experience",
    "I feel the lecture gave me confidence knowledge and clarity",
    "The session was outstanding productive clear and excellent",
    "I understood all of today's content with remarkable clarity",
    "The class was a superb and genuinely rewarding experience",
    "I feel today's lecture was a genuine and complete success",
    "The session was brilliant informative engaging and clear",
    "I understood the lesson deeply clearly and with full ease",
    "The class was an exceptional and deeply outstanding session",
    "I feel the lecture was a perfect and brilliant achievement",
    "The session was clear well structured productive and engaging",
    "I understood everything with total confidence and full ease",
    "The class was a wonderful and completely satisfying session",
    "I feel today's lecture was the most rewarding of the term",
    "The session was outstanding clear engaging and informative",
    "I understood the entire lesson and feel absolutely wonderful",
    "The class was a brilliant and deeply rewarding experience",
    "I feel the lecture gave me a truly powerful academic boost",
    "The session was magnificent productive clear and excellent",
    "I understood the topic completely and feel deeply prepared",
    "The class was a superb and truly outstanding experience",
    "I feel today's lecture was a landmark and complete success",
    "The session was engaging clear productive and informative",
    "I understood all concepts today and feel completely amazing",
    "The class was a wonderful and genuinely excellent experience",
    "I feel the lecture was a true and complete academic victory",
    "The session was outstanding clear informative and engaging",
    "I understood the content at every level and feel fully ready",
    "The class was a magnificent and deeply productive session",
    "I feel today's lecture was a complete and total triumph",
    "The session was brilliant clear productive and engaging",
    "I understood everything today at a deep and precise level",
    "The class was an exceptional and truly satisfying experience",
    "I feel the lecture gave me all the clarity I have needed",
    "The session was productive engaging well organized and clear",
    "I understood the entire lesson and feel deeply confident",
    "The class was a wonderful and highly productive experience",
    "I feel today's lecture was the most impactful of the year",
    "The session was outstanding clear engaging and excellent",
    "I understood the topic at every level with full confidence",
    "The class was a superb and genuinely outstanding experience",
    "I feel the lecture was a perfect and deeply satisfying class",
    "The session was magnificent clear productive and informative",
    "I understood all of today's content and feel truly ready",
    "The class was a brilliant and completely outstanding session",
    "I feel today's lecture was a genuine triumph of teaching",
    "The session was engaging clear informative and very useful",
    "I understood the lesson completely and feel truly wonderful",
    "The class was an exceptional and deeply rewarding experience",
    "I feel the lecture was a complete and total academic success",
    "The session was outstanding productive engaging and clear",
    "I understood everything today with full confidence and ease",
    "The class was a magnificent and truly rewarding experience",
    "I feel today's lecture was a complete and perfect triumph",
    "The session was brilliant clear informative and excellent",
    "I understood the topic at the deepest level possible today",
    "The class was a superb and deeply satisfying experience",
    "I feel the lecture gave me everything I needed to grow today",
    "The session was clear productive engaging and very excellent",
    "I understood all concepts deeply and feel fully prepared",
    "The class was a wonderful and truly outstanding experience",
]

NEGATIVE_V3 = [
    "The lecture was completely incomprehensible and deeply frustrating",
    "I could not understand a single thing despite my best effort",
    "The class was an utter disaster that left me feeling hopeless",
    "I feel deeply disappointed and lost after today's session",
    "The session was so disorganized I could not even begin to follow",
    "I left the class feeling more confused and defeated than before",
    "The lecturer showed no concern for whether we understood anything",
    "I struggled painfully through the entire session without relief",
    "The class was chaotic unclear and a complete waste of my time",
    "I have never felt so abandoned and confused in any class before",
    "The session left me feeling overwhelmed and completely hopeless",
    "I am profoundly disappointed by the quality of today's lecture",
    "The class failed completely to deliver any clear information",
    "I felt entirely unsupported by the lecturer during the session",
    "The lecture was a confusing disaster that taught me absolutely nothing",
    "I am significantly further behind after attending today's class",
    "The session was a deeply frustrating and poorly executed failure",
    "I could not connect any of the ideas presented during the class",
    "The class was the most unhelpful and confusing session I have had",
    "I feel the lecturer was completely indifferent to our understanding",
    "The lecture created chaos and confusion where clarity was needed",
    "I left the session feeling completely empty and utterly uninformed",
    "The class was a total failure in every conceivable dimension",
    "I am exhausted and demoralized from trying to follow today's class",
    "The session actively worsened my understanding of the topic",
    "I felt completely invisible and ignored throughout the entire class",
    "The lecture was excessively fast dense and completely disorganized",
    "I am going to need significant help after today's terrible session",
    "The session was an absolute and complete waste of my time",
    "I could not even identify the central point of the entire lecture",
    "The class was chaotic meaningless and deeply demoralizing",
    "I feel completely cheated out of a proper learning experience",
    "The lecture was delivered without any structure clarity or direction",
    "I struggled from the very beginning to the very end of the class",
    "The session felt more like a punishment than an educational class",
    "I am completely lost and have no idea how to begin catching up",
    "The class made me feel incapable and deeply deeply frustrated",
    "I feel the session made my academic situation far worse today",
    "The lecture was so poor it actively damaged my understanding",
    "I left the class feeling deeply ashamed that I understood nothing",
    "The session was completely incomprehensible from beginning to end",
    "I am devastated by how ineffective and confusing the class was",
    "The lecture was delivered with zero concern for the students",
    "I feel completely unprepared unsupported and abandoned after today",
    "The class was a complete disappointment and failure of teaching",
    "I could not write a single useful or coherent note during class",
    "The lecture left me with a deep and overwhelming sense of despair",
    "I am seriously questioning my ability to pass this course now",
    "The session was rushed incomprehensible and completely unhelpful",
    "I feel like the lecturer simply gave up on us during today's class",
    "The lecture was a nightmare experience from beginning to the end",
    "I feel completely and utterly broken after today's poor session",
    "The session was genuinely the worst educational experience I have had",
    "I cannot find any useful or meaningful value in today's class",
    "The class made me feel like giving up on the entire subject",
    "I am deeply and genuinely concerned about my future in this course",
    "The lecture was disorganized chaotic and profoundly confusing",
    "I feel the session was a complete and catastrophic failure today",
    "The class was confusing beyond measure and left me feeling helpless",
    "I struggled to understand even the most fundamental definitions",
    "The lecture was an embarrassing and deeply inadequate session",
    "I feel completely and utterly let down by today's terrible class",
    "The session left me feeling far more confused than I was before",
    "I am going home today feeling angry frustrated and totally defeated",
    "The lecture completely wasted my time and gave me nothing at all",
    "I feel the class set me back rather than moving me forward",
    "The session was an embarrassing failure of academic instruction",
    "I could not find any logical structure or direction in the lecture",
    "The class left me with a profound and lasting sense of hopelessness",
    "I feel the session treated every student with total disregard",
    "The lecture was so confusing and unclear that I completely gave up",
    "I am struggling deeply to see any path forward after today's class",
    "The session was a chaotic and profoundly demoralizing experience",
    "I feel completely unsupported and entirely lost after today",
    "The class made it painfully clear that I am very far behind now",
    "I left today's session feeling utterly and completely defeated",
    "The lecture was hard to follow and simply impossible to understand",
    "I feel the session was a deeply missed opportunity to help us learn",
    "The class was a frustrating and deeply and thoroughly unsatisfying experience",
    "I am dreading every future class after today's terrible session",
    "The lecture taught me absolutely nothing and confused me further",
    "I feel the class was poorly designed poorly delivered and unhelpful",
    "The session was an absolute disaster and I genuinely learned nothing",
    "I simply cannot make any sense of what was taught to us today",
    "The lecture left me feeling completely and devastatingly hopeless",
    "I am deeply and profoundly frustrated by the lack of clarity today",
    "The session was disorganized chaotic rushed and completely unhelpful",
    "I feel the lecturer failed absolutely every student in the room",
    "The class was a painful and deeply and completely unproductive experience",
    "I struggled throughout the entire session without any relief at all",
    "The lecture left me with no tools no strategies and no clarity",
    "I feel defeated demoralized and entirely lost after today's class",
    "The session was a massive failure that I deeply regret attending",
    "I found absolutely nothing useful or helpful in today's class",
    "The lecture was the most confusing and unhelpful session of the year",
    "I feel completely and entirely abandoned by the education today",
    "The class was a deeply and profoundly disappointing experience",
    "I cannot extract any meaningful knowledge whatsoever from today",
    "The lecture left me feeling like I am falling further behind daily",
    "I feel the session actively and directly worked against my learning",
    "The class was a complete disaster and I deeply regret attending it",
    "I am rapidly losing all confidence in my ability to succeed here",
    "The lecture was an absolute and complete failure of all teaching",
    "I feel completely overwhelmed and entirely unsupported after today",
    "The session was so terrible I seriously considered walking out early",
    "I found the class to be an incredibly deeply demoralizing experience",
    "The lecture was incompetent unclear and deeply and profoundly frustrating",
    "I feel the class was a complete betrayal of every attending student",
    "The session was a disorganized and deeply and completely unsatisfying mess",
    "I cannot believe how poorly and carelessly today's lecture was delivered",
    "The class was so confusing and unclear I genuinely felt like giving up",
    "I feel today's session was the absolute lowest point of my entire semester",
    "The lecture left me feeling completely and entirely and utterly defeated",
    "I am shocked and dismayed by how poorly today's class was organized",
    "The session was a complete disaster that taught me absolutely nothing",
    "I feel the lecturer had absolutely no plan or purpose during the class",
    "The class was an utter failure that left me entirely without direction",
    "I walked out of today's session feeling deeply and utterly without hope",
    "The lecture was confusing chaotic and profoundly deeply demoralizing",
    "I feel today's class was a complete and catastrophic academic failure",
    "The session was disorganized poorly paced and completely deeply unclear",
    "I could not follow a single concept throughout the entire awful class",
    "The lecture failed to meet even the most basic and minimal expectations",
    "I feel completely and entirely unprepared after today's disastrous session",
    "The class was a painful reminder of absolutely everything I do not know",
    "I am deeply discouraged and completely unsure how to proceed at all",
    "The lecture was a genuinely terrible experience that taught me nothing",
    "I feel the session was a complete failure on absolutely every level",
    "The class was disorganized confusing and completely and deeply unhelpful",
    "I left today's lecture feeling more deeply lost than I ever have before",
    "The session was a deeply frustrating and genuinely demoralizing disaster",
    "I cannot comprehend how today's terrible lecture was allowed to happen",
    "The class was an absolute nightmare and I feel completely and utterly lost",
    "I feel the lecture was a profound and deep disappointment on every level",
    "The session left me with absolutely nothing but confusion and frustration",
    "I am genuinely and deeply scared about my ability to pass after today",
    "The lecture was unclear disorganized and profoundly deeply discouraging",
    "I feel the class was a complete and utter and total waste of my time",
    "The session was chaotic poorly managed and deeply and profoundly confusing",
    "I left today's class with far more anxiety than understanding at all",
    "The lecture was a genuinely poor and deeply and profoundly frustrating experience",
    "I feel completely broken and devastated by the quality of today's session",
    "The class was a disaster from the very first to the very last moment",
    "I am struggling desperately to find any hope after today's terrible lecture",
    "The session was disorganized rushed and simply impossible to follow",
    "I could not extract a single meaningful and useful idea from today's class",
    "The lecture left me feeling completely and profoundly demoralized and lost",
    "I feel the class was a deeply missed and painful opportunity today",
    "The session was poor confusing deeply unhelpful and completely frustrating",
    "I am devastated by how much precious time I wasted in today's lecture",
    "The class was beyond disappointing and left me feeling completely hopeless",
    "I feel the session was a failure that set me significantly and deeply back",
    "The lecture was a chaotic and deeply and completely discouraging experience",
    "I could not follow the class no matter how hard and desperately I tried",
    "The session was the most demoralizing and confusing class I have ever had",
    "I feel completely and utterly and entirely failed by today's lecture",
    "The class was an absolute and complete failure of all academic teaching",
    "I left today's session feeling as though absolutely nothing was learned",
    "The lecture was disorganized confusing poorly paced and deeply unclear",
    "I feel the session was a profound and deeply disappointing failure today",
    "The class was a deeply frustrating and completely and utterly unhelpful session",
    "I am lost confused and deeply and profoundly discouraged after today",
    "The session was a complete disaster that I will not soon forget ever",
    "I feel the class was a complete failure that genuinely harmed my learning",
    "The lecture was the most unhelpful confusing and poor session I have seen",
    "I walked away from today's class with absolutely nothing whatsoever to show",
    "The session was deeply disorganized unhelpful and profoundly frustrating",
    "I feel the lecture was a complete disaster from every possible angle",
    "The class left me feeling like I will absolutely never understand this topic",
    "I am struggling deeply and profoundly after today's terribly unclear session",
    "The lecture was an absolute mess with absolutely no clear direction at all",
    "I feel completely and thoroughly and utterly let down by today's class",
    "The session was disorganized unclear rushed and completely and deeply unhelpful",
    "I could not understand anything today and feel deeply and profoundly lost",
    "The class was a genuinely terrible and deeply demoralizing experience today",
    "I feel the lecture has set my understanding back in a significant way",
    "The session was a painful chaotic and deeply confusing disaster today",
    "I am completely at a profound loss after today's incredibly poor lecture",
    "The class was a total disaster and I feel completely and utterly hopeless",
    "I feel the session was a failure that I will struggle deeply to recover from",
    "The lecture was confusing poorly structured and completely and deeply unhelpful",
    "I could not make any sense of anything whatsoever presented in today's class",
    "The session was an absolute disappointment that taught me absolutely nothing",
    "I feel completely defeated confused and deeply lost after today's lecture",
    "The class was a deeply demoralizing and completely and utterly unproductive experience",
    "I am going home today feeling more lost than I have ever possibly felt before",
    "The lecture was a terrible example of how absolutely not to teach a class",
    "I feel the session was a complete and utter and absolute academic catastrophe",
    "The class was disorganized chaotic poorly paced and completely deeply unclear",
    "I left today's lecture with no understanding no clarity and no direction at all",
    "The session was a deeply frustrating and completely and thoroughly unhelpful mess",
    "I feel completely and entirely and utterly hopeless after today's poor class",
    "The lecture was a disaster that left every student feeling completely lost",
    "I am struggling deeply after today's terribly disorganized and unclear session",
    "The class was an absolute failure that I deeply and profoundly regret attending",
    "I feel the lecture was the most demoralizing and devastating session of my life",
    "The session was chaotic confusing deeply unhelpful and completely frustrating",
    "I could not follow the class at any single point throughout the entire session",
    "The lecture left me feeling completely and entirely hopeless about this course",
    "I feel the class was a profound and deeply disappointing failure of teaching",
    "The session was an absolute nightmare that taught me absolutely nothing at all",
    "I am deeply and profoundly and genuinely discouraged after today's poor lecture",
    "The class was a total disaster that has left me feeling completely and utterly lost",
    "I feel completely and utterly and entirely defeated after today's awful session",
    "The lecture was disorganized unclear confusing and completely and deeply unhelpful",
    "I could not extract any value whatsoever from today's terrible class at all",
    "The session was a deeply discouraging and completely and utterly chaotic mess",
    "I feel the lecture was a complete failure that left me devastated and hopeless",
    "The class was an absolute and complete and total disaster from start to finish",
    "I am completely lost confused and utterly devastated after today's session",
    "The lecture was a genuinely terrible experience that I deeply and profoundly regret",
    "I feel the session was a profound and complete disaster for my learning today",
    "The class was chaotic disorganized poorly taught and completely deeply unclear",
    "I left today's lecture feeling completely and utterly and entirely destroyed",
    "The session was a deeply demoralizing disaster of an academic class today",
    "I feel completely lost demoralized and profoundly hopeless after today's class",
    "The lecture was the most disappointing and confusing session I have ever attended",
    "I am struggling after today's poorly delivered unclear and deeply unhelpful session",
    "The class was a complete and utter failure of academic teaching in every way",
    "I feel the lecture was a catastrophic failure in every possible dimension today",
    "The session was disorganized confusing unclear and completely and deeply unhelpful",
    "I could not follow the lecture at any point despite my absolute best effort",
    "The class was a genuinely devastating and profoundly demoralizing experience",
    "I feel completely and thoroughly and utterly broken after today's poor lecture",
    "The lecture was a complete disaster that left me feeling devastatingly hopeless",
    "I am deeply disappointed confused and profoundly lost after today's session",
    "The session was a chaotic poorly managed and deeply and profoundly frustrating mess",
    "I feel the class was a total and complete and absolute failure of teaching today",
    "The lecture was confusing poorly organized and deeply and profoundly discouraging",
    "I left today's class feeling more hopeless than I have ever felt in my entire life",
    "The session was a deeply unfortunate and genuinely demoralizing experience today",
    "I feel completely and utterly failed by the deeply poor quality of today's class",
    "The lecture was a genuinely terrible and deeply and profoundly frustrating session",
    "I am going home today feeling like I have completely wasted my entire precious time",
    "The class was a disaster and I am deeply and genuinely concerned about my future",
    "I feel the session was a complete and profound and total academic failure today",
    "The lecture was poorly planned poorly delivered and deeply and profoundly confusing",
    "I could not find any clarity structure or direction in today's terrible class",
    "The session was a deeply chaotic and completely and utterly demoralizing mess",
    "I feel completely and totally and utterly lost after today's disastrous lecture",
    "The class was an absolute failure that has left me feeling deeply discouraged",
    "I am struggling deeply and profoundly after today's poorly organized session",
    "The lecture was a complete disaster in absolutely every possible dimension",
    "I feel the class was the worst learning experience I have ever possibly had",
    "The session was disorganized chaotic poorly paced and deeply and profoundly unclear",
    "I could not understand a single thing taught during today's terrible class",
    "The lecture left me feeling completely and utterly and entirely without hope",
    "I feel the session was a catastrophic failure of academic instruction today",
    "The class was so terrible and confusing that I genuinely regret being there",
    "I am completely and profoundly and utterly lost after today's devastating class",
    "The lecture was a disaster of clarity organization delivery and overall quality",
    "I feel completely hopeless and deeply demoralized after today's awful session",
    "The session was an absolute and complete failure in absolutely every respect",
    "I left today's class feeling more defeated and hopeless than I ever have before",
    "The lecture was a deeply demoralizing and completely and utterly unhelpful mess",
    "I feel the class was a profound and complete and total failure of teaching today",
    "The session was chaotic confusing disorganized and completely and deeply unhelpful",
    "I could not make any sense whatsoever of what was presented during today's class",
    "The lecture left me feeling completely and devastatingly and utterly lost today",
    "I feel the session was the most demoralizing class I have ever possibly attended",
    "The class was a complete and utter disaster that genuinely taught me nothing",
    "I am deeply and completely and genuinely discouraged after today's terrible lecture",
    "The session was poorly organized poorly taught and completely and deeply confusing",
    "I feel completely lost confused and utterly and entirely defeated after today",
    "The lecture was a genuinely devastating experience I will absolutely not forget",
    "I am struggling desperately to find any hope or direction after today's class",
    "The session was an absolute catastrophe of teaching clarity and academic delivery",
    "I feel the lecture has deeply and permanently damaged my confidence in this subject",
    "The class was a complete failure that left me feeling utterly and truly hopeless",
    "I left today's terrible session feeling completely and absolutely and utterly lost",
    "The lecture was a deeply disappointing and profoundly demoralizing experience today",
    "I feel completely and entirely and thoroughly defeated by today's poor class",
    "The session was chaotic disorganized unclear and deeply and profoundly frustrating",
    "I could not follow anything today and feel completely and utterly overwhelmed",
    "The class was a genuinely terrible and deeply and completely unhelpful experience",
    "I feel the lecture was the worst and most demoralizing academic experience of my life",
    "The session was an absolute and complete disaster in every conceivable respect",
    "I am going home today feeling completely broken and genuinely and truly lost",
    "The lecture was poorly executed poorly organized and deeply and profoundly confusing",
    "I feel completely and utterly lost after today's deeply disastrous session",
    "The class was a profound failure that left me feeling utterly and completely hopeless",
    "I am deeply discouraged demoralized and profoundly lost after today's lecture",
    "The session was a terrible chaotic and deeply and profoundly demoralizing disaster",
    "I feel the class was a complete and utter and absolute failure from start to end",
    "The lecture was a disaster of the highest order and I learned absolutely nothing",
    "I left today's class feeling completely and utterly and entirely without direction",
]

NEUTRAL_V3 = [
    "The class was reasonable and I got the general idea today",
    "I followed the lecture moderately and understood some parts",
    "Today's session was okay and left me with basic knowledge",
    "I understood parts of today's lecture but struggled elsewhere",
    "The lecture was acceptable though some areas remain unclear",
    "I followed most of the session but felt confused occasionally",
    "The class was neither particularly good nor particularly bad",
    "I understood the basics but will need to review more later",
    "The session was average and matched my basic expectations",
    "I followed the lecture but would need extra study to excel",
    "The class was decent but some of my questions remain unanswered",
    "I understood some concepts clearly while others remain vague",
    "The lecture was acceptable and I feel basically informed",
    "I followed the session with a moderate level of attention",
    "The class was okay and I will review my notes carefully later",
    "I understood the broad outlines but not all the fine details",
    "The lecture was standard and I have a functional understanding",
    "I followed the class but cannot fully articulate everything learned",
    "The session was fine and I gained some though not much knowledge",
    "I understood the key ideas but missed some of the fine details",
    "The class was ordinary and left me feeling neither way about it",
    "I followed the lecture at a comfortable but not exceptional level",
    "The session was adequate and I feel reasonably well prepared",
    "I understood the topic at a functional and workable level today",
    "The class was fine though I feel I need more practice time",
    "I followed the lecture and kept the most essential points",
    "The session was unremarkable but gave me something to build on",
    "I understood the concept at a surface level and need more study",
    "The class was average and I have no strong feelings either way",
    "I followed the session without great difficulty or excitement",
    "The lecture was passable and I feel reasonably on track today",
    "I understood today's class well enough to keep moving forward",
    "The session was moderate and I have a partial basic understanding",
    "I followed the lecture and will review the less clear parts later",
    "The class was standard and delivered what was basically needed",
    "I understood the content well enough for basic level purposes",
    "The lecture was reasonable and I feel adequately but not deeply informed",
    "I followed the session at a satisfactory if not exceptional level",
    "The class was okay and I absorbed just enough to continue studying",
    "I understood the basics clearly but struggled with advanced material",
    "The lecture was acceptable and I have a fundamentally neutral impression",
    "I followed the class with moderate and acceptable comprehension",
    "The session was fine and I am neither particularly excited nor discouraged",
    "I understood enough of the lecture to feel reasonably okay about it",
    "The class was standard and I feel neutrally about it overall",
    "I followed the session and understood it to a reasonable degree",
    "The lecture was moderate and I have a workable basic understanding",
    "I understood the main ideas and will fill in the gaps later",
    "The class was decent and I feel mildly and adequately informed",
    "I followed the lecture with a balanced level of comprehension today",
    "The session was acceptable and gave me something reasonable to work with",
    "I understood the topic at a level that is just about enough for now",
    "The class was average with some sections clear and some less so",
    "I followed the lecture and can recall the most essential points",
    "The session was okay and I feel just about adequately prepared today",
    "I understood the lesson sufficiently to proceed with my studying",
    "The class was satisfactory and I have a neutral overall takeaway",
    "I followed the lecture with moderate success and reasonable attention",
    "The session was ordinary and gave me a reasonable if basic foundation",
    "I understood the topic at an intermediate and workable functional level",
    "The class was fine and I have a mixed but manageable reaction to it",
    "I followed the session without major difficulty or major confusion today",
    "The lecture was decent and met the basic standard I expected",
    "I understood enough from today to attempt the necessary next steps",
    "The class was okay and I am cautiously optimistic about my progress",
    "I followed the lecture and got a partial but reasonably adequate grasp",
    "The session was standard and I feel adequately informed for the moment",
    "I understood the main points but feel I need more detailed examples",
    "The class was reasonable and I have a moderate functional understanding",
    "I followed the lecture and absorbed the most basic and essential elements",
    "The session was acceptable and I feel just about on track today",
    "I understood the content at a level that works adequately for now",
    "The class was fine and I can build on what I learned in today's session",
    "I followed the session with a reasonable and acceptable level of attention",
    "The lecture was adequate and left me with a basic if workable grasp",
    "I understood the topic at a workable level for the current moment",
    "The class was okay and I am neither particularly impressed nor concerned",
    "I followed the lecture and retained a moderate and reasonable amount",
    "The session was decent and I feel reasonably and adequately informed",
    "I understood the main concepts but need more time to fully absorb them",
    "The class was standard and I have just enough to continue my studying",
    "I followed the lecture at an acceptable and moderately satisfying level",
    "The session was reasonable and I have a neutral and balanced impression",
    "I understood the topic sufficiently for a basic level of understanding",
    "The class was okay and I feel just about adequately prepared for now",
    "I followed the session with moderate comprehension and adequate ease",
    "The lecture was acceptable and I feel sufficiently if not deeply informed",
    "I understood enough today to proceed with this subject with some effort",
    "The class was fine and I have a workable if limited level of knowledge",
    "I followed the lecture and understood it to a fair and reasonable degree",
    "The session was decent and I have a partial but generally okay grasp",
    "I understood the topic at a level that meets my most basic needs",
    "The class was average and I feel moderately and adequately informed today",
    "I followed the lecture without much struggle but also without much depth",
    "The session was adequate and I feel just about ready to proceed forward",
    "I understood the main ideas but some important details are still unclear",
    "The class was okay and I expect to fill the gaps through self study",
    "I followed the session and have a moderate and satisfactory confidence level",
    "The lecture was standard and left me with an acceptable if basic grasp",
    "I understood enough of the topic to feel reasonably but not deeply informed",
    "The class was fine and I absorbed the most important and essential elements",
    "I followed the lecture at a comfortable and reasonably adequate level",
    "The session was adequate and gave me a workable foundation to build on",
    "I understood the topic well enough to complete the most basic tasks",
    "The class was decent and I have a workable and functional understanding now",
    "I followed the lecture and retained the core and essential ideas today",
    "The session was reasonable and I feel just about on track for now",
    "I understood the lesson at a level that is broadly satisfactory for now",
    "The class was okay though I genuinely wish it had been more detailed",
    "I followed the session with moderate and just acceptable success today",
    "The lecture was acceptable and left me feeling just adequately informed",
    "I understood the topic at a functional and reasonably adequate level",
    "The class was standard and I feel quite neutrally about it overall today",
    "I followed the lecture and absorbed a moderate and reasonable amount",
    "The session was okay and I can continue my studies reasonably from here",
    "I understood the lesson at a level that allows me to reasonably proceed",
    "The class was average and I have a basic but workable and functional grasp",
    "I followed the lecture and feel just about adequately and moderately prepared",
    "The session was decent and I have a moderate and functional understanding",
    "I understood the main points and will review the remaining gaps myself",
    "The class was okay and I have a neutral and generally calm feeling about it",
    "I followed the lecture with an average and generally acceptable comprehension",
    "The session was standard and left me feeling just about adequately informed",
    "I understood the topic at a level that meets my needs reasonably for now",
    "The class was fine and I feel moderately and reasonably confident after today",
    "I followed the lecture without issue but also without particular excitement",
    "The session was acceptable and I feel adequately if not deeply informed",
    "I understood the lesson at a satisfactory and workable functional level",
    "The class was average and I have everything I basically need to continue",
    "I followed the lecture and have a moderate and reasonable grasp of the topic",
    "The session was decent and I feel reasonably and adequately prepared today",
    "I understood the content well enough for my current and most basic purposes",
    "The class was okay and I feel just about ready to move cautiously forward",
    "I followed the session at a comfortable and adequately functional level",
    "The lecture was standard and I feel reasonably and adequately well informed",
    "I understood the topic at a moderate and broadly satisfactory level today",
    "The class was fine and I am neither particularly excited nor discouraged today",
    "I followed the lecture and feel a neutral and adequately balanced confidence",
    "The session was reasonable and I have a workable and satisfactory grasp today",
    "I understood enough of the content to feel just adequately okay today",
    "The class was okay and gave me the basics I needed to reasonably proceed",
    "I followed the lecture at a level that is just about adequately sufficient",
    "The session was average and I feel adequately but barely sufficiently informed",
    "I understood the topic at a level that broadly satisfies my basic needs",
    "The class was standard and I have a neutral and balanced overall impression",
    "I followed the session with adequate but not particularly exceptional focus",
    "The lecture was acceptable and I feel moderately and reasonably informed now",
    "I understood enough today to continue my studies with a moderate level of ease",
    "The class was decent and I have a partial and generally adequate understanding",
    "I followed the lecture and have the basics I need to reasonably move on",
    "The session was fine and I feel just about adequately and moderately prepared",
    "I understood the lesson at a level that broadly works for the current moment",
    "The class was average and I have a reasonable and functional level of clarity",
    "I followed the lecture with a satisfactory but not particularly deep grasp",
    "The session was okay and I feel reasonably but not fully and deeply informed",
    "I understood the topic at a level that is just barely but adequately enough",
    "The class was standard and I feel just about okay and adequate after today",
    "I followed the lecture and understood it at a moderate and functional level",
    "The session was decent and I feel adequately but not completely fully ready",
    "I understood the content at a level that allows basic and functional progress",
    "The class was fine and I have a moderate and workable and functional grasp",
    "I followed the session with reasonable but not particularly deep comprehension",
    "The lecture was acceptable and left me with a workable and functional foundation",
    "I understood the topic at a satisfactory level for the time being at least",
    "The class was average and I feel just about adequately informed after today",
    "I followed the lecture with a moderate and broadly satisfactory level of success",
    "The session was adequate and I have a reasonable and functional foundation now",
    "I understood the lesson well enough to feel moderately and adequately prepared",
    "The class was okay and I have a neutral and broadly calm impression overall",
    "I followed the lecture at a level that is just about broadly acceptable today",
    "The session was standard and left me feeling adequately if not deeply informed",
    "I understood the topic at a functional level that broadly works for my needs",
    "The class was fine and I feel just adequately and moderately ready to proceed",
    "I followed the session with a moderate and reasonably adequate level of ease",
    "The lecture was decent and I feel just about okay and adequate after class",
    "I understood enough of today's lesson to continue with a moderate level of effort",
    "The class was average and I am moderately and reasonably confident about it",
    "I followed the lecture and feel a neutral and broadly balanced impression",
    "The session was reasonable and I have a satisfactory and functional level of grasp",
    "I understood the content at a basic but workable and functional level today",
    "The class was standard and I feel just about moderately and adequately informed",
    "I followed the lecture with just enough comprehension to reasonably proceed",
    "The session was adequate and I have a workable but broadly limited grasp",
    "I understood the topic at a level that is broadly satisfactory for right now",
    "The class was okay and I absorbed the most essentially important basics",
    "I followed the lecture and have a neutral and broadly functional takeaway today",
    "The session was fine and I feel adequately but not particularly deeply informed",
    "I understood the lesson at a moderate level with some remaining gaps to fill",
    "The class was average and I plan to review carefully before my next class",
    "I followed the lecture with an average and broadly reasonable comprehension",
    "The session was decent and I feel just about adequately and reasonably prepared",
    "I understood the topic at a level that meets the most basic minimum standard",
    "The class was standard and I feel just about adequately informed overall today",
    "I followed the lecture with a workable and broadly satisfactory level of understanding",
    "The session was okay and I have a moderate and broadly neutral feeling overall",
    "I understood enough from today to feel just about and adequately prepared",
    "The class was fine and I feel just about okay and adequate after attending",
    "I followed the lecture at a satisfactory but not particularly impressive level",
    "The session was adequate and I feel just about and adequately informed enough",
    "I understood the topic at a level that broadly works for basic level purposes",
    "The class was average and I have a moderate but workable and functional grasp",
    "I followed the lecture with just enough focus to broadly get the basic points",
    "The session was decent and left me feeling adequately and reasonably informed",
    "I understood the lesson at a level that is just broadly satisfactory overall",
    "The class was okay and I have what I basically need to continue my studying",
    "I followed the session with a reasonable and broadly balanced comprehension",
    "The lecture was standard and I feel just about moderately and adequately prepared",
    "I understood the topic at a workable level for my most current basic needs",
    "The class was fine and I have a neutral and broadly calm impression today",
    "I followed the lecture and understood it at a broadly satisfactory level",
    "The session was acceptable and I feel just about adequately on track now",
    "I understood enough today to feel moderately and broadly confident overall",
    "The class was average and I feel just about and adequately informed today",
    "I followed the lecture with a moderate and broadly satisfactory level of grasp",
    "The session was standard and I feel reasonably and adequately informed today",
    "I understood the topic at a workable level that is broadly sufficient for now",
    "The class was fine and I can build on this broadly adequate foundation forward",
    "I followed the session and feel adequately but not particularly fully prepared",
    "The lecture was decent and I have a moderate and broadly functional understanding",
    "I understood the lesson well enough to proceed with a moderate level of effort",
    "The class was okay and I have a balanced and broadly neutral impression overall",
    "I followed the lecture at a level that broadly satisfies my basic learning needs",
    "The session was adequate and left me feeling just about and adequately informed",
    "I understood the topic at a moderate level and feel just about okay today",
    "The class was average and I have a workable if broadly basic understanding",
    "I followed the lecture with moderate effort and broadly adequate success today",
    "The session was reasonable and I feel just about and adequately prepared today",
    "I understood the content at a broadly satisfactory level for the current moment",
    "The class was standard and I feel just about and broadly confident today",
    "I followed the lecture and absorbed a broadly reasonable amount today",
    "The session was okay and I have a neutral and broadly balanced feeling overall",
    "I understood the topic at a level that is just about broadly workable for now",
    "The class was fine and I am broadly and adequately informed after today",
    "I followed the session at a moderate and broadly functional level of comprehension",
    "The lecture was acceptable and I feel just about and broadly adequately informed",
    "I understood enough from today's class to broadly proceed with my studying",
    "The class was average and I have a moderate and broadly functional understanding",
    "I followed the lecture at a level that is just about broadly sufficient today",
    "The session was decent and I feel just and broadly adequately informed today",
    "I understood the topic at a workable and broadly satisfactory level today",
    "The class was standard and I feel just about and broadly adequately prepared",
    "I followed the session and understood it to a broadly moderate functional degree",
    "The lecture was fine and I feel just about and broadly reasonably okay today",
    "I understood enough of today to feel moderately and broadly adequately ready",
    "The class was okay and I have a workable if broadly moderate understanding",
    "I followed the lecture with a moderate and just broadly acceptable grasp today",
    "The session was adequate and I feel broadly and reasonably informed after today",
    "I understood the lesson at a level that broadly meets the minimum standard",
    "The class was average and I plan to study broadly more on my own today",
    "I followed the lecture and absorbed just broadly enough to continue forward",
    "The session was standard and left me feeling just about broadly okay overall",
    "I understood the topic at a level that is broadly workable and functional",
    "The class was fine and I feel broadly and adequately informed for the moment",
    "I followed the session with a moderate and broadly functional level of success",
    "The lecture was reasonable and I feel just about broadly on track today",
    "I understood the content at a broadly workable level with some gaps remaining",
    "The class was decent and I feel broadly and moderately informed after today",
    "I followed the lecture with broadly adequate comprehension and reasonable attention",
    "The session was okay and I have a just about broadly sufficient understanding",
    "I understood the topic at a level that is just broadly adequate for right now",
    "The class was standard and I feel just about broadly ready to continue today",
    "I followed the lecture and feel broadly and moderately and adequately informed",
    "The session was acceptable and gave me just broadly enough to work reasonably with",
    "I understood enough of today's lesson to broadly proceed with some basic effort",
    "The class was average and I feel just about broadly okay after attending today",
    "I followed the session with a workable and broadly moderate comprehension today",
    "The lecture was decent and I feel adequately if not deeply and broadly ready",
    "I understood the topic at a level that broadly satisfies my most basic needs",
    "The class was fine and I have a moderate and broadly satisfactory functional grasp",
    "I followed the lecture at a broadly adequate and workable level today",
    "The session was standard and I feel just broadly adequately prepared for now",
    "I understood the content at a level that broadly allows me to study more today",
    "The class was okay and I have a neutral and broadly workable impression overall",
    "I followed the session with a just about broadly adequate level of ease today",
    "The lecture was acceptable and I feel just about broadly and reasonably ready",
    "I understood the lesson at a broadly satisfactory but moderate level today",
    "The class was average and I am just about broadly okay after attending today",
    "I followed the lecture with a broadly reasonable and moderate comprehension today",
    "The session was decent and I feel broadly and adequately informed for right now",
    "I understood the topic at a level that is just about broadly workable today",
    "The class was standard and I feel just about broadly and moderately confident",
    "I followed the session and understood it at a broadly satisfactory functional level",
    "The lecture was fine and I feel just about broadly adequately and reasonably informed",
    "I understood enough today to continue with a broadly moderate and adequate ease",
]

# ─────────────────────────────────────────────
# BUILD AND SAVE
# ─────────────────────────────────────────────
def build_and_save():
    print("=" * 55)
    print("   SENTIMENT DATASET EXPANSION v3")
    print("   Target: ~1500 samples per class")
    print("=" * 55)

    label_map = {"Positive": 2, "Negative": 0, "Neutral": 1}

    existing = pd.read_csv(OUT_CSV)
    print(f"\n  Existing samples : {len(existing)}")

    extra_rows = []
    for label_name, responses in [
        ("Positive", POSITIVE_V3),
        ("Negative", NEGATIVE_V3),
        ("Neutral",  NEUTRAL_V3),
    ]:
        for idx, response in enumerate(responses):
            cleaned = re.sub(r"[^a-z\s]", "",
                             response.lower()).strip()
            extra_rows.append({
                "student_id"       : f"student{(idx % 32) + 1}",
                "question"         : "How was today's lecture?",
                "response"         : response,
                "compound_score"   : round(
                    analyzer.polarity_scores(response)["compound"], 4),
                "sentiment_label"  : label_name,
                "cleaned_response" : cleaned,
                "sentiment_encoded": label_map[label_name]
            })

    df_extra    = pd.DataFrame(extra_rows)
    df_combined = pd.concat([existing, df_extra], ignore_index=True)
    df_combined.drop_duplicates(subset=["response"], inplace=True)
    df_combined.reset_index(drop=True, inplace=True)
    df_combined.to_csv(OUT_CSV, index=False)

    print(f"  Added samples    : {len(df_extra)}")
    print(f"  Total samples    : {len(df_combined)}")
    print(f"\n  📊 Label Distribution:")
    print(df_combined["sentiment_label"].value_counts().to_string())
    print(f"\n  ✅ Saved to: {OUT_CSV}")
    print(f"\n🚀 Now run: data_splitting.py → sentiment_model.py")

# ─────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────
TEXT_DIR = "outputs/features/text"
OUT_CSV  = os.path.join(TEXT_DIR, "sentiment_preprocessed.csv")

if __name__ == "__main__":
    os.makedirs(TEXT_DIR, exist_ok=True)
    build_and_save()