import os
import re
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# ─────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────
TEXT_DIR  = "outputs/features/text"
OUT_CSV   = os.path.join(TEXT_DIR, "sentiment_preprocessed.csv")

analyzer  = SentimentIntensityAnalyzer()

# ─────────────────────────────────────────────
# LARGE DIVERSE RESPONSE POOL
# 200 per class = 600 total
# ─────────────────────────────────────────────
POSITIVE = [
    "The lecture was absolutely brilliant today",
    "I had no trouble understanding the content",
    "Superb teaching made this topic very simple",
    "I grasped everything taught in class today",
    "Very insightful lecture that clarified a lot",
    "The class was perfectly paced and very clear",
    "I walked out of class feeling very confident",
    "Excellent delivery and very relatable examples",
    "The topic was simplified in an amazing way",
    "I thoroughly enjoyed every minute of class",
    "The lesson flowed smoothly from start to end",
    "Outstanding session with very helpful visuals",
    "I could follow every explanation without effort",
    "The class boosted my confidence in this subject",
    "Very well structured and easy to understand",
    "I left class today feeling fully satisfied",
    "The teaching was top notch and very engaging",
    "All my doubts were cleared during the lecture",
    "I appreciated how the topic was broken down",
    "Fantastic class that exceeded all expectations",
    "The lecture motivated me to study more today",
    "Everything was explained with great precision",
    "I understood even the most complex parts today",
    "The class was lively and very informative",
    "I feel fully prepared after today's lecture",
    "Wonderful experience in class this morning",
    "The examples resonated with me very well",
    "I feel empowered to tackle this topic now",
    "The lecture was inspiring and well delivered",
    "Best lecture I have attended this semester",
    "I absorbed everything taught today with ease",
    "The content was engaging and easy to process",
    "The lecture answered all my previous questions",
    "I now have a thorough grasp of this topic",
    "The class was perfect in every single way",
    "Today's lecture was clear and well organized",
    "I enjoyed the way concepts were introduced",
    "The teacher made everything easy to follow",
    "I feel ready to tackle any exam on this topic",
    "Excellent session that kept me fully engaged",
    "Today I learned something I will never forget",
    "The lecture connected theory to practice well",
    "I have never understood this topic this well",
    "The class made me excited about this subject",
    "I could ask questions and get clear answers",
    "The pace was perfect for taking good notes",
    "The visual aids used today were very helpful",
    "I feel like an expert on this topic now",
    "The lecturer was enthusiastic and inspiring",
    "I would love every class to be like today",
    "The session was both educational and enjoyable",
    "I appreciated the real world examples given",
    "This was one of the most productive classes",
    "My understanding of the topic has improved greatly",
    "The lecturer broke down complex ideas simply",
    "I feel much more prepared for assessments now",
    "The class was dynamic and kept my attention",
    "Everything clicked for me during today's class",
    "The session reinforced my understanding well",
    "I found the class very relevant to my studies",
    "The explanation style was perfect for learning",
    "I am genuinely excited to learn more now",
    "The class built on previous knowledge perfectly",
    "I had zero confusion throughout the lecture",
    "The content delivery was smooth and effective",
    "I took thorough notes because it was so clear",
    "The lecturer showed genuine passion for teaching",
    "I walked away with complete confidence today",
    "The topic finally makes complete sense to me",
    "I will definitely revisit my notes from today",
    "The class exceeded everything I hoped for",
    "My interest in this subject has grown today",
    "The lecture was comprehensive and well paced",
    "I understood every example given in class",
    "The class structure was logical and clear",
    "I feel inspired to explore this topic further",
    "The lecturer checked for understanding often",
    "I would rate today's lecture ten out of ten",
    "Everything taught was relevant and practical",
    "The class was a great use of my time today",
    "I learned more today than in any other session",
    "The teaching approach really worked for me",
    "I left class feeling energized and motivated",
    "The lecture connected well with past lessons",
    "I enjoyed every part of today without exception",
    "The session was thorough detailed and clear",
    "I feel completely on top of this subject now",
    "The class gave me clarity I have needed for weeks",
    "The lecturer handled every question perfectly",
    "I understood all the diagrams and examples",
    "The session has made me love this subject more",
    "I could follow the entire class without struggle",
    "I appreciate the effort put into today's class",
    "The explanations were logical and well ordered",
    "I now feel confident to attempt difficult tasks",
    "The class has set a great foundation for exams",
    "I will remember today's lesson for a long time",
    "The lecture was informative fun and engaging",
    "I came confused and left feeling very certain",
    "Best explanation of this topic I have heard",
    "The lecturer taught with clarity and purpose",
    "I understood the lesson better than I expected",
    "Everything made sense from the very beginning",
    "I feel the class was tailored for my learning",
    "The session improved my view of this subject",
    "I appreciated the step by step explanations",
    "The class gave me tools I can use immediately",
    "Today was a breakthrough moment for my studies",
    "The lecture cleared up all my misconceptions",
    "I feel confident enough to teach others now",
    "The class had the right mix of depth and clarity",
    "I found every section of the lecture valuable",
    "The session was so engaging time flew by fast",
    "I could connect today's lesson to real life",
    "The lecturer made me feel included and supported",
    "I understood everything the first time it was said",
    "The lecture built my interest in the subject",
    "I feel this class has improved my academic path",
    "The content was fresh relevant and well taught",
    "I got answers to questions I did not even ask",
    "The class left me wanting to study more today",
    "I now have a clear mental map of this topic",
    "The lecturer communicated complex ideas simply",
    "I feel prepared motivated and fully informed",
    "Everything in today's class was worth my time",
    "The session brought the subject to life for me",
    "I understood both the theory and its application",
    "The class gave me a new appreciation for learning",
    "I feel smarter and more capable after today",
    "The lecturer made every student feel important",
    "I understood every transition between topics",
    "The class gave me the confidence I was missing",
    "Today was a turning point in my understanding",
    "The session was so well planned and executed",
    "I never lost focus or interest at any point",
    "The lecture helped me overcome my confusion",
    "I feel today's class was exactly what I needed",
    "The content was accessible despite being complex",
    "The lecturer kept me engaged from start to finish",
    "I am grateful for the clarity provided today",
    "The session answered all my lingering questions",
    "I understood the subject at a much deeper level",
    "The lecture delivery was confident and smooth",
    "I found the class both challenging and rewarding",
    "The session made me feel capable and prepared",
    "I have full understanding of today's topic now",
    "The class was a masterclass in good teaching",
    "I walked in uncertain and walked out confident",
    "The lecture helped me connect all the dots",
    "I found today's class incredibly useful overall",
    "The session set the right tone for my studies",
    "I now understand concepts I struggled with before",
    "The class was organized informative and clear",
    "I could tell the lecturer prepared thoroughly",
    "The lecture left me feeling capable and ready",
    "I enjoyed the interactive elements of the class",
    "The teaching made the material feel manageable",
    "I am leaving today's class with zero doubts",
    "The session gave me exactly the clarity I needed",
    "I feel fully equipped to handle this subject now",
    "The class reminded me why I love learning",
    "Today's lesson was both insightful and practical",
    "The lecture made every concept feel achievable",
    "I will carry today's lesson with me going forward",
    "The session was the highlight of my academic week",
    "I understood all the difficult sections today",
    "The class was a great balance of content and pace",
    "I left with more knowledge than I came with",
    "The lecture was a perfect example of great teaching",
    "I now feel fully ready for assessments on this",
    "The class gave me skills I can apply immediately",
    "I feel today's lecture will change my results",
    "The session delivered exactly what I expected",
    "I have never felt this confident in a subject",
    "The class was worth every minute of attention",
    "The lecture was impactful clear and memorable",
    "I understood the topic better than I ever have",
    "Today's session was absolutely worth attending",
    "The class was a brilliant example of clear teaching",
    "I feel energized and ready to tackle this subject",
    "The lecture gave me everything I needed to succeed",
    "I can confidently say I mastered today's content",
    "The session was smooth engaging and productive",
    "I now have complete clarity on this entire topic",
    "The class was wonderful from beginning to end",
    "I feel the best I have ever felt about this course",
    "The lecturer inspired me with today's class",
    "I understand the topic inside out after today",
    "The session was exceptional in every single way",
    "I walked out of class with a smile and confidence",
    "The class gave me hope and motivation to excel",
    "Today's lecture will definitely improve my grades",
    "I feel that today was the best class of the term",
]

NEGATIVE = [
    "I completely zoned out during the lecture",
    "The topic was rushed through without explanation",
    "I left class more confused than when I arrived",
    "The lecture was poorly planned and confusing",
    "I could not grasp a single concept today",
    "The delivery was monotonous and very boring",
    "I struggled throughout the entire lecture today",
    "The class was chaotic and hard to follow",
    "Nothing was explained clearly during the session",
    "I felt overwhelmed by the pace of the class",
    "The session was a complete waste of my time",
    "I am extremely frustrated after today's class",
    "The concepts introduced were never fully explained",
    "I have never been this lost in a lecture before",
    "The class left me with more questions unanswered",
    "I struggled to even write down proper notes",
    "The lecture made no sense to me whatsoever",
    "I feel demotivated after today's terrible lecture",
    "The teaching style was very ineffective today",
    "I could not follow the logic of the explanations",
    "The class was painfully difficult to sit through",
    "I need a complete re-teaching of today's topic",
    "The session was too theoretical with no examples",
    "Very poor classroom management ruined the lecture",
    "I was completely disengaged for the whole class",
    "The lecture skipped too many foundational concepts",
    "I am deeply confused after today's session",
    "The content was irrelevant and poorly delivered",
    "I have no idea what was taught in class today",
    "The class was the most unproductive session yet",
    "I felt ignored and lost throughout the lecture",
    "The explanation style did not work for me at all",
    "I am disappointed with how today's class went",
    "The session moved too fast for anyone to follow",
    "I struggled to stay awake during the dull lecture",
    "The class left me feeling hopeless about this topic",
    "I feel this subject is becoming impossible for me",
    "The lecturer failed to explain even the basics",
    "I am going home more confused than I came",
    "The lecture was disorganized from start to finish",
    "I could not keep up with the speed of the class",
    "The session felt like a waste of valuable time",
    "I understood absolutely nothing that was taught",
    "The lecturer did not check if anyone understood",
    "I am completely demoralized by today's lecture",
    "The class was a disaster and I learned nothing",
    "I feel like giving up after today's session",
    "The teaching approach was completely ineffective",
    "I am lost and I do not know where to begin",
    "The lecture left me feeling stupid and confused",
    "Nothing about today's class made any sense",
    "I am frustrated because I expected better today",
    "The session made the subject feel impossible",
    "I feel the lecturer did not prepare adequately",
    "The class added to my confusion rather than helping",
    "I have never felt so lost in an academic setting",
    "The lecture was too abstract with no application",
    "I walked out of class feeling defeated today",
    "The session did nothing to help my understanding",
    "I cannot believe how poorly the class was handled",
    "The lecturer spoke too fast and explained nothing",
    "I am struggling to find motivation after today",
    "The class made me dread this subject even more",
    "I feel like the session was not designed for us",
    "The lecture left me with a complete mental block",
    "I could not connect any of the ideas presented",
    "The session was the worst learning experience yet",
    "I feel unsupported and completely left behind",
    "The class gave me anxiety rather than clarity",
    "I am not sure what the point of today was",
    "The lecturer seemed uninterested in teaching us",
    "I felt invisible and unheard throughout the class",
    "The session made my confusion ten times worse",
    "I have never left a class feeling this hopeless",
    "The lecture was full of jargon with no explanation",
    "I am behind now because today made no sense",
    "The session left me questioning my ability to learn",
    "I struggled to follow a single sentence today",
    "The lecture was so bad I could not take any notes",
    "I feel the class set me back rather than forward",
    "The session ignored the needs of struggling students",
    "I cannot explain what was taught today at all",
    "The lecture felt rushed incomplete and unhelpful",
    "I am exhausted from trying to understand today",
    "The class was absolutely nothing like I expected",
    "I regret attending because I learned nothing useful",
    "The session destroyed my confidence in this topic",
    "I feel completely unprepared for any assessment",
    "The lecture left me with more doubt than before",
    "I wasted time trying to follow an unclear lesson",
    "The class failed to address even the basics today",
    "I am going to need serious help after this session",
    "The lecturer made the topic harder than it needs to be",
    "I feel like the class worked against my learning",
    "The session was too fast too dense and too confusing",
    "I am deeply discouraged by today's poor lecture",
    "The class taught me nothing I did not already know",
    "I feel completely overwhelmed and lost right now",
    "The lecture was the most confusing one this year",
    "I am starting to dread attending this class",
    "The session made it impossible to learn anything",
    "I feel the lecturer did not care if we understood",
    "The class was an incredibly frustrating experience",
    "I left today's session feeling angry and confused",
    "The lecture went over my head from the first minute",
    "I need someone to explain everything from scratch",
    "The session was too chaotic to extract any learning",
    "I am struggling to see the purpose of this class",
    "The lecture made me feel like I am falling behind",
    "I did not understand a single diagram shown today",
    "The class was long boring and completely unclear",
    "I felt like the lecturer was speaking another language",
    "The session reinforced nothing and confused everything",
    "I have serious doubts about passing this course now",
    "The lecture gave me no tools to work with at all",
    "I feel like I am completely alone in my confusion",
    "The class was delivered in the worst possible way",
    "I am dreading the next session after today's disaster",
    "The lecture was more harmful than helpful today",
    "I left class more stressed than when I arrived",
    "The session made the topic feel out of my reach",
    "I have never struggled this much to follow a class",
    "The lecture was absolutely terrible from start to finish",
    "I feel like I am failing this subject already",
    "The class was disorganized slow and very unhelpful",
    "I regret not studying alone instead of attending",
    "The session was a painful reminder of what I do not know",
    "I feel like the lecturer assumed too much knowledge",
    "The class made me lose all my confidence today",
    "I found the session to be a complete disappointment",
    "The lecture made zero effort to engage the students",
    "I could not extract any useful information today",
    "The session was one of the worst I have attended",
    "I feel completely burned out after today's lecture",
    "The class left me with no direction or understanding",
    "I am discouraged and unsure how to move forward",
    "The lecture lacked structure clarity and relevance",
    "I feel the session was poorly targeted and rushed",
    "The class failed me as a student today completely",
    "I am not sure I can recover from this session's loss",
    "The lecture was the lowest point of my semester",
    "I walked out feeling embarrassed that I understood nothing",
    "The session was a total failure in every sense",
    "I feel the class actively made my learning worse",
    "The lecture was the most unhelpful I have ever sat through",
    "I have given up trying to make sense of today's class",
    "The session left me feeling completely and utterly lost",
    "I am devastated by how poorly today's lecture went",
    "The class made me question if I belong in this course",
    "I feel cheated out of a proper learning experience",
    "The lecture added chaos where clarity was needed",
    "I feel like today was a step backward in my education",
    "The session destroyed any confidence I had left",
    "I am completely frustrated and disheartened today",
    "The class was a waste of effort for everyone present",
    "I feel that today's lecture hurt my understanding",
    "The session left me in a worse position than before",
    "I cannot make sense of anything taught today",
    "The lecture was an absolute failure of teaching",
    "I am leaving today's class with nothing to show",
    "The session felt like reading without comprehension",
    "I am completely undone by how bad the class was",
    "The lecture did not connect to any prior knowledge",
    "I feel robbed of a proper learning opportunity today",
    "The session was the hardest I have ever had to endure",
    "I have no idea how to study for this topic now",
    "The class made me feel hopeless about my future here",
    "I am dreading assessments after today's poor session",
    "The lecture was a mess that left me fully defeated",
    "I feel like the class set impossible expectations",
    "The session was so bad I could not even take notes",
    "I am going to need external help after today's class",
    "The lecture was exhausting confusing and unhelpful",
    "I feel this subject is becoming impossible to learn",
    "The session taught me nothing and confused me more",
    "I am genuinely concerned about my performance now",
    "The class left me questioning my academic ability",
    "I feel today's lecture was the worst of the year",
    "The session made the course feel unmanageable",
    "I have lost all motivation to study after today",
    "The lecture left a deeply negative impression on me",
    "I feel like the class did more harm than good today",
    "The session was deeply unsatisfying and confusing",
    "I am completely at a loss after today's lecture",
    "The class failed to achieve any of its learning goals",
]

NEUTRAL = [
    "The class was reasonable but nothing outstanding",
    "I followed most of it but lost track near the end",
    "Today's lecture was okay with a few unclear spots",
    "The session was fine but I still have questions",
    "I understood the basics but missed the advanced part",
    "The class was average with some good moments",
    "I got the main idea but need to review my notes",
    "The lecture was decent though a bit hard at times",
    "Some parts were engaging while others were dull",
    "I partially followed the class but need more help",
    "The session was acceptable but not very memorable",
    "I understood seventy percent of today's content",
    "The class was standard without anything surprising",
    "I neither loved nor hated today's lecture at all",
    "The session was satisfactory but lacked some depth",
    "I learned something today but still feel uncertain",
    "The class was moderate and somewhat informative",
    "I followed along but the ending was a bit unclear",
    "The lecture was passable but left me wanting more",
    "Some concepts clicked but others still confuse me",
    "The class was okay though pacing could improve",
    "I got a general understanding but need more review",
    "The session was mixed with good and unclear parts",
    "I understood the topic at a surface level today",
    "The lecture was alright but not particularly helpful",
    "I followed most steps but struggled with examples",
    "The class covered the topic but lacked elaboration",
    "I grasped the concept briefly but need more time",
    "The session was fair with room for improvement",
    "I understood today's class at a beginner level",
    "The lecture was okay though I expected much more",
    "I followed the introduction but got lost midway",
    "The class was mediocre but had a few good points",
    "I understand the basics but advanced parts elude me",
    "The lecture was so-so and left a mixed impression",
    "The session was neither great nor terrible today",
    "I understood some parts but not the whole picture",
    "The class was average and met basic expectations",
    "I followed the lecture with moderate difficulty",
    "The session gave me partial understanding at best",
    "I needed more examples to fully understand today",
    "The class was fine though I expected more detail",
    "I understood the outline but not the full content",
    "The lecture moved at a pace that was just manageable",
    "I followed without fully grasping every section",
    "The class was straightforward but a bit shallow",
    "I understood the key points but missed the details",
    "The session had good moments but also unclear ones",
    "I followed the lecture but still need to review",
    "The class was passable but could have been clearer",
    "I understood the lesson at a moderate level today",
    "The session was neither impressive nor disappointing",
    "I grasped the surface of what was taught today",
    "The class addressed the topic without going deep",
    "I understood enough to get by but not to excel",
    "The lecture was okay but not engaging enough",
    "I took some notes but missed key explanations",
    "The session was consistent but not very inspiring",
    "I followed with some effort but managed overall",
    "The class was adequate and met my basic needs",
    "I understood some sections clearly and others less",
    "The session was unremarkable but not bad overall",
    "I understood the topic at a functional level today",
    "The class was decent without being exceptional",
    "I grasped the overall message but lack full clarity",
    "The lecture was average and left me feeling neutral",
    "I understood enough but there were gaps in clarity",
    "The class was okay and I managed to follow along",
    "I understood the lesson sufficiently for now",
    "The session was fine though some parts were unclear",
    "I got the gist of the lecture but missed the nuance",
    "The class was manageable though not fully satisfying",
    "I understood today's lecture to a reasonable degree",
    "The session covered the basics without much depth",
    "I followed the lecture but cannot fully explain it",
    "The class was straightforward but left gaps for me",
    "I understood parts clearly but others were vague",
    "The session was average in quality and delivery",
    "I grasped the main ideas but not the finer points",
    "The class was okay overall without standout moments",
    "I understood enough to participate if asked",
    "The lecture was moderate and met my expectations",
    "I followed the session but would benefit from review",
    "The class was sufficient though not particularly good",
    "I understood more than I expected but less than hoped",
    "The session was fair with both strengths and gaps",
    "I got something out of today's class but not enough",
    "The lecture was neither inspiring nor discouraging",
    "I followed the class but feel I need more practice",
    "The session had value but also had room to improve",
    "I understood the basics clearly but struggled later",
    "The class was acceptable and I did not struggle much",
    "I followed the lecture at an adequate level today",
    "The session was decent and delivered what was needed",
    "I understood the topic partially and need revision",
    "The class had a balanced mix of clarity and confusion",
    "I followed the lecture with average comprehension",
    "The session was reasonable though not outstanding",
    "I understood the content to a satisfactory level",
    "The class was fine and I managed to get the basics",
    "I followed today's lecture with a moderate grasp",
    "The session was neutral with no strong impressions",
    "I understood the material at an intermediate level",
    "The class was average and I have mixed feelings",
    "I followed the class but could not summarize it well",
    "The session was okay and I expect to review my notes",
    "I understood some of the lecture but not all of it",
    "The class was neither too difficult nor too easy",
    "I followed most of the session with moderate effort",
    "The lecture was adequate without being impressive",
    "I understood the content but still have open questions",
    "The class was standard and I have no strong feelings",
    "I followed the lecture and got a basic understanding",
    "The session was satisfactory at a surface level",
    "I understood the lesson just enough to feel okay",
    "The class was acceptable with a few unclear moments",
    "I followed the lecture but it did not excite me",
    "The session was passable and left a neutral impact",
    "I understood today's class well enough to proceed",
    "The lecture was moderate and I have neutral feelings",
    "I followed the session with an average level of ease",
    "The class was fine though it lacked memorable moments",
    "I understood the material to a basic satisfactory level",
    "The session was decent though I still have questions",
    "I followed the lecture with neither joy nor frustration",
    "The class was okay and I was neither lost nor excited",
    "I understood the topic at a workable level today",
    "The lecture was alright and met the minimum standard",
    "I followed the session and understood it moderately",
    "The class was acceptable and I learned some basics",
    "I grasped enough to complete tasks but not excel",
    "The session was ordinary with average comprehension",
    "I followed the lecture and have a partial grasp now",
    "The class was neither bad nor great in any way",
    "I understood the session to a reasonable extent",
    "The lecture was standard and I have no complaints",
    "I followed the class with an average level of interest",
    "The session was okay and I am neither lost nor confident",
    "I understood enough from today to continue studying",
    "The class was moderate and left me with mixed results",
    "I followed the lecture without strong positive feelings",
    "The session was fine though I need further reading",
    "I understood the topic at a level that is just enough",
    "The class was acceptable though not inspiring at all",
    "I followed the session with average comprehension overall",
    "The lecture was moderate and gave me partial clarity",
    "I understood some concepts but the rest need revision",
    "The session was satisfactory but nothing more today",
    "I followed the lecture and retained the core ideas",
    "The class was standard and I feel neither way about it",
    "I understood today's lesson at a comfortable level",
    "The lecture was okay and I have a neutral takeaway",
    "I followed the session and managed to keep up overall",
    "The class was decent and I have a basic understanding",
    "I understood the lecture to a moderate and fair degree",
    "The session was fine and I feel adequately informed",
    "I followed the class and absorbed the essential points",
    "The lecture was average and I have no strong reaction",
    "I understood the content well enough for now at least",
    "The class was satisfactory and met expected standards",
    "I followed the session with a balanced level of effort",
    "The lecture left me with a moderate level of clarity",
    "I understood the basics and feel reasonably prepared",
    "The class was acceptable and I feel okay about it",
    "I followed the lecture though I still have questions",
    "The session was fine and I will review before exams",
    "I understood most parts but there are gaps to fill",
    "The class was passable and I feel adequately informed",
    "I followed the session at a satisfactory level today",
    "The lecture was moderate and left a neutral impression",
    "I understood the content at a reasonable level today",
    "The class was standard and I am not deeply moved",
    "I followed the lecture with a reasonable level of ease",
    "The session was fine and gave me enough to work with",
    "I understood the lesson at a level I am okay with",
    "The class was decent and I plan to review my notes",
    "I followed the lecture and absorbed the key concepts",
    "The session was satisfactory though not outstanding",
    "I understood the material and feel moderately prepared",
    "The class was average and I have a neutral impression",
]

# ─────────────────────────────────────────────
# BUILD DATASET
# ─────────────────────────────────────────────
def label_sentiment(text):
    score = analyzer.polarity_scores(text)["compound"]
    if score >= 0.05:   return "Positive"
    elif score <= -0.05: return "Negative"
    else:                return "Neutral"

def build_dataset():
    label_map = {"Positive": 2, "Negative": 0, "Neutral": 1}
    rows      = []

    for label_name, responses in [
        ("Positive", POSITIVE),
        ("Negative", NEGATIVE),
        ("Neutral",  NEUTRAL)
    ]:
        for idx, response in enumerate(responses):
            cleaned = re.sub(r"[^a-z\s]", "",
                             response.lower()).strip()
            rows.append({
                "student_id"       : f"student{(idx % 32) + 1}",
                "question"         : "How was today's lecture?",
                "response"         : response,
                "compound_score"   : round(
                    analyzer.polarity_scores(response)["compound"], 4),
                "sentiment_label"  : label_name,
                "cleaned_response" : cleaned,
                "sentiment_encoded": label_map[label_name]
            })

    df = pd.DataFrame(rows)
    df.drop_duplicates(subset=["response"], inplace=True)
    df.reset_index(drop=True, inplace=True)
    return df

# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────
if __name__ == "__main__":
    print("=" * 55)
    print("   SENTIMENT DATASET EXPANSION")
    print("=" * 55)

    os.makedirs(TEXT_DIR, exist_ok=True)
    df = build_dataset()
    df.to_csv(OUT_CSV, index=False)

    print(f"\n  📊 Dataset Summary:")
    print(f"     Total samples : {len(df)}")
    print(f"\n  📊 Label Distribution:")
    print(df["sentiment_label"].value_counts().to_string())
    print(f"\n  ✅ Saved to: {OUT_CSV}")
    print(f"\n🚀 Now run: data_splitting.py → sentiment_model.py")